const fs = require('fs');
const path = require('path');

const keys = require('./keys_compact.json');

const enMap = {
"auto_quan_ly_danh_muc_mon_an_va_cac":"Manage categories, menu items and buffet/set menu packages.",
"auto_them_mon":"+ Add Item",
"auto_them_goi_menu":"Add Menu Package",
"auto_goi_menu":"Menu Package",
"auto_chua_co_goi_menu_nao":"No menu packages yet.",
"auto_tao_goi_dau_tien":"Create first package",
"auto_sua":"Edit",
"auto_chu_thich_danh_muc":"Category Notes",
"auto_mon_an":"Menu Item",
"auto_tat_ca":"All",
"auto_moi_nhom_con":"Any sub-category",
"auto_bat":"On",
"auto_ten_mon":"Item Name",
"auto_don_vi":"Unit *",
"auto_gia":"Price",
"auto_them":"+ Add",
"auto_chua_co_mon_nao_trong_nhom_nay":"No items in this sub-category.",
"auto_chua_co_mon_nao_trong_danh_muc":"No items in this category.",
"auto_chua_co_danh_muc_mon_an_nao":"No categories yet.",
"auto_ten_goi":"Package Name *",
"auto_loai_goi":"Package Type *",
"auto_khac":"Other",
"auto_gia_vnd":"Price (VND) *",
"auto_gioi_han_mon":"Item Limit",
"auto_de_trong_neu_khong_gioi_han":"Leave empty if no limit.",
"auto_thoi_luong_phut":"Duration (mins)",
"auto_ap_dung_cho_buffet":"Applies to buffet.",
"auto_dang_hoat_dong":"Active",
"auto_huy":"Cancel",
"auto_danh_muc":"Category *",
"auto_nhom_con":"Sub-category",
"auto_khong_co":"— None —",
"auto_hien_thi_gia":"Display Price",
"auto_tuy_chon_chi_de_hien_thi_khong":"Optional — for display only, not used in calculation.",
"auto_mo_ta":"Description",
"auto_dang_ban_con_mon":"Available / In Stock",
"auto_tim_mon_goi_danh_muc":"Search items, packages, categories…",
"auto_mo_ta_ngan":"Short description…",
"auto_sua_goi_menu":"Edit Menu Package",
"auto_sua_mon":"Edit Item",
"auto_nguu_cat":"Nguu Cat",
"auto_he_thong_quan_ly_nha_hang":"Restaurant Management System",
"auto_ghi_nho_dang_nhap":"Remember me",
"auto_tai_khoan_duoc_cap_boi_quan_ly":"Account is provided by manager. Contact admin if you don't have one.",
"auto_showpassword_an_mat_khau_hien":"showPassword ? 'Hide password' : 'Show password'",
"auto_ca_hien_tai_dang_mo":"Current active shift",
"auto_chua_co_ca_nao_dang_mo_tai_chi":"No active shift in this branch. Clock in first.",
"auto_quyen_truy_cap_bi_tu_choi":"Access Denied",
"auto_vui_long_chon_mot_ban_an_dang":"Please select an active table from Floor Plan before ordering.",
"auto_di_toi_so_do_ban":"🗺️ Go to Floor Plan",
"auto_hoa_don":"Invoice",
"auto_khach_hang":"Customer",
"auto_gio_mo":"Open Time",
"auto_thoi_gian":"Time:",
"auto_thoi_gian_do_uong_premium_da_k":"Premium drink time is over. Only Group A drinks can be ordered.",
"auto_mo_khoa_pin":"Unlock PIN",
"auto_xoa_het":"🗑️ Clear all",
"auto_don_gia":"Unit Price",
"auto_thanh_tien":"Total",
"auto_hoa_don_trong":"Empty Invoice",
"auto_vui_long_chon_mon_an_tu_thuc_d":"Please select items from the menu on the right to order",
"auto_trong_goi":"In Package",
"auto_0d":"0 VND",
"auto_tam_tinh_mon_goi":"Subtotal (items + package):",
"auto_phi_dich_vu_5":"Service Fee (5%):",
"auto_thue_gtgt_vat_10":"VAT (10%):",
"auto_tong_so_luong_mon":"Total Items:",
"auto_tam_luu":"⏸️ Save Draft",
"auto_gui_bep":"🍳 Send to Kitchen",
"auto_tat_ca_mon":"All Items",
"auto_con_mon":"In Stock",
"auto_het_mon":"Out of Stock",
"auto_khong_sap_xep":"No sort",
"auto_gia_thap_cao":"Price Low → High",
"auto_gia_cao_thap":"Price High → Low",
"auto_dang_loc_danh_muc_san_pham":"Filtering products...",
"auto_khong_tim_thay_mon_an_nao_khop":"No matching items found",
"auto_thuc_don_hien_tai_khong_co_mon":"Item not found in current menu. Try clearing filters or search another name.",
"auto_chi_tiet_mon_an":"ℹ️ Item Details",
"auto_het_hang":"Out of Stock",
"auto_ma_mon":"Item Code",
"auto_don_vi_tinh":"Unit",
"auto_so_luong":"Quantity",
"auto_don_gia_vnd":"Unit Price (VND)",
"auto_bao_gom_vat":"Includes VAT (%)",
"auto_bao_gom_ppv":"Includes Service Fee (%)",
"auto_loai_tien_te":"Currency",
"auto_vnd_viet_nam_dong":"VND (Vietnamese Dong)",
"auto_usd_do_la_my":"USD (US Dollar)",
"auto_ty_gia":"Exchange Rate",
"auto_ghi_chu":"Notes",
"auto_phan_nhom_thuc_don_he_thong":"Menu Classification (System)",
"auto_nhom_san_pham":"Product Group:",
"auto_goi_buffet":"Buffet Package:",
"auto_goi_set_menu":"Set Menu Package:",
"auto_goi_do_uong":"Drink Package:",
"auto_tien_te":"Currency",
"auto_ghi_chu_chung":"General Notes",
"auto_huy_bo_esc":"Cancel (Esc)",
"auto_them_vao_gio_hang":"Add to Cart",
"auto_1_chon_goi_an_phuc_vu_course_p":"1. Select Food Package (Course Pack):",
"auto_2_chon_nhom_do_uong_kem_theo_d":"2. Select Drink Package (Drink Group):",
"auto_nhom_a_soft_drink":"Group A - Soft Drink",
"auto_nuoc_ngot_uong_khong_gioi_han":"Unlimited Soft Drinks (Free)",
"auto_nhom_b_premium_drink":"Group B - Premium Drink",
"auto_ruou_bia_cao_cap_uong_trong_2":"Premium Alcohol for 2 Hours (Free)",
"auto_nhom_c_premium_alt":"Group C - Premium Alt",
"auto_ruou_bia_thay_the_dung_2_gio_f":"Alternative Alcohol for 2 Hours (Free)",
"auto_nhom_d_a_la_carte":"Group D - A La Carte",
"auto_goi_do_uong_le_tinh_tien_rieng":"Order drinks individually",
"auto_3_ngon_ngu_giao_dien_hien_thi":"3. Tablet Interface Language:",
"auto_tieng_viet":"🇻🇳 Tiếng Việt",
"auto_huy_bo_quay_lai":"Cancel / Go Back",
"auto_pin_sua_cau_hinh":"🔓 Configuration PIN",
"auto_xac_nhan_khoa_course":"🔒 Confirm & Lock Course",
"auto_ma_pin_xac_thuc_quan_ly":"Manager Verification PIN",
"auto_nhap_ma_pin_cua_quan_ly_de_mo":"Enter Manager PIN to unlock course configuration.",
"auto_tim_kiem":"Search...",
"auto_them_ghi_chu_dac_thu_it_da_nhi":"Add specific notes (less ice, more water, no onion...)...",
"auto_them_ghi_chu_cho_ca_mon_an":"Add notes for the whole dish...",
"auto_them_ghi_chu_rieng_cho_lua_cho":"Add individual notes for this choice...",
"auto_xem_hoa_don_tam_tinh":"View provisional invoice",
"auto_cau_hinh_goi_ngon_ngu":"Package/Language Config",
"auto_xoa_mon_khoi_gio":"Remove from cart",
"auto_favoriteids_includes_product_i":"favoriteIds.includes(product.id) ? 'Remove favorite' : 'Add to favorite'",
"auto_xem_chi_tiet_tuy_chon":"View details & Options",
"auto_he_thong":"System",
"auto_tong_quan_he_thong":"System Overview",
"auto_quan_ly_tai_khoan":"Account Management",
"auto_cau_hinh_du_lieu":"Data Configuration",
"auto_thuc_don_goi_menu":"Menu & Packages",
"auto_so_do_ban":"Floor Plan",
"auto_cau_hinh_kpi_kgi":"KPI/KGI Configuration",
"auto_nhat_ky_he_thong_audit":"System Audit Log",
"auto_dang_xuat":"Log Out",
"auto_quan_tri_he_thong":"System Admin",
"auto_chi_nhanh_quan_1":"Branch District 1",
"auto_quan_ly_het_mon":"Out of Stock Management",
"auto_bao_cao_phan_tich":"Reports & Analytics",
"auto_bang_dieu_khien":"Dashboard",
"auto_bao_cao_doanh_thu":"Revenue Report",
"auto_gia_von_cogs":"COGS",
"auto_phan_tich_marketing":"Marketing Analytics",
"auto_khach_hang_crm":"Customer (CRM)",
"auto_ton_kho":"Inventory",
"auto_nghiep_vu":"Operations",
"auto_thu_ngan":"Cashier",
"auto_ung_dung_phuc_vu":"Service App",
"auto_quan_ly_ca":"Shift Management",
"auto_chi_nhanh_nguu_cat_q_1":"Branch: Nguu Cat D.1",
"auto_hoat_dong":"Operations",
"auto_chon_mon":"Order Item",
"auto_tong_ket_ca":"Shift Summary",
"auto_thu_ngan_01":"Cashier 01",
"auto_chi_nhanh_1":"Branch 1",
"auto_nghiep_vu_phuc_vu":"Service Ops",
"auto_dang_phuc_vu":"Serving",
"auto_nguyen_van_a":"Nguyen Van A",
"auto_nhan_vien_phuc_vu_nv01":"Waiter (NV01)"
};

const jaMap = {
"auto_quan_ly_danh_muc_mon_an_va_cac":"カテゴリー、メニュー、パッケージを管理します。",
"auto_them_mon":"+ メニューを追加",
"auto_them_goi_menu":"パッケージを追加",
"auto_goi_menu":"パッケージ",
"auto_chua_co_goi_menu_nao":"パッケージがありません。",
"auto_tao_goi_dau_tien":"最初のパッケージを作成",
"auto_sua":"編集",
"auto_chu_thich_danh_muc":"カテゴリーメモ",
"auto_mon_an":"メニュー",
"auto_tat_ca":"すべて",
"auto_moi_nhom_con":"すべてのサブカテゴリー",
"auto_bat":"オン",
"auto_ten_mon":"メニュー名",
"auto_don_vi":"単位 *",
"auto_gia":"価格",
"auto_them":"+ 追加",
"auto_chua_co_mon_nao_trong_nhom_nay":"このサブカテゴリーにはメニューがありません。",
"auto_chua_co_mon_nao_trong_danh_muc":"このカテゴリーにはメニューがありません。",
"auto_chua_co_danh_muc_mon_an_nao":"カテゴリーがありません。",
"auto_ten_goi":"パッケージ名 *",
"auto_loai_goi":"パッケージタイプ *",
"auto_khac":"その他",
"auto_gia_vnd":"価格（VND） *",
"auto_gioi_han_mon":"メニュー制限",
"auto_de_trong_neu_khong_gioi_han":"制限なしの場合は空欄。",
"auto_thoi_luong_phut":"時間（分）",
"auto_ap_dung_cho_buffet":"ビュッフェに適用。",
"auto_dang_hoat_dong":"有効",
"auto_huy":"キャンセル",
"auto_danh_muc":"カテゴリー *",
"auto_nhom_con":"サブカテゴリー",
"auto_khong_co":"— なし —",
"auto_hien_thi_gia":"表示価格",
"auto_tuy_chon_chi_de_hien_thi_khong":"オプション — 表示用であり、計算には使用されません。",
"auto_mo_ta":"説明",
"auto_dang_ban_con_mon":"販売中 / 在庫あり",
"auto_tim_mon_goi_danh_muc":"メニュー、パッケージ、カテゴリーを検索…",
"auto_mo_ta_ngan":"短い説明…",
"auto_sua_goi_menu":"パッケージを編集",
"auto_sua_mon":"メニューを編集",
"auto_nguu_cat":"Nguu Cat",
"auto_he_thong_quan_ly_nha_hang":"レストラン管理システム",
"auto_ghi_nho_dang_nhap":"ログインを記憶する",
"auto_tai_khoan_duoc_cap_boi_quan_ly":"アカウントは管理者が提供します。お持ちでない場合は管理者にお問い合わせください。",
"auto_showpassword_an_mat_khau_hien":"showPassword ? 'パスワードを隠す' : 'パスワードを表示'",
"auto_ca_hien_tai_dang_mo":"現在開いているシフト",
"auto_chua_co_ca_nao_dang_mo_tai_chi":"この店舗には開いているシフトがありません。シフトを開始してください。",
"auto_quyen_truy_cap_bi_tu_choi":"アクセス拒否",
"auto_vui_long_chon_mot_ban_an_dang":"注文する前に、フロアマップから開いているテーブルを選択してください。",
"auto_di_toi_so_do_ban":"🗺️ フロアマップへ",
"auto_hoa_don":"請求書",
"auto_khach_hang":"お客様",
"auto_gio_mo":"開始時間",
"auto_thoi_gian":"時間:",
"auto_thoi_gian_do_uong_premium_da_k":"プレミアムドリンクの時間が終了しました。グループAのドリンクのみ注文できます。",
"auto_mo_khoa_pin":"PINを解除",
"auto_xoa_het":"🗑️ すべてクリア",
"auto_don_gia":"単価",
"auto_thanh_tien":"合計",
"auto_hoa_don_trong":"空の請求書",
"auto_vui_long_chon_mon_an_tu_thuc_d":"右側のメニューから注文を選択してください",
"auto_trong_goi":"パッケージ内",
"auto_0d":"0 VND",
"auto_tam_tinh_mon_goi":"小計（メニュー + パッケージ）:",
"auto_phi_dich_vu_5":"サービス料（5%）:",
"auto_thue_gtgt_vat_10":"消費税（VAT 10%）:",
"auto_tong_so_luong_mon":"総アイテム数:",
"auto_tam_luu":"⏸️ 下書き保存",
"auto_gui_bep":"🍳 キッチンに送る",
"auto_tat_ca_mon":"すべてのメニュー",
"auto_con_mon":"在庫あり",
"auto_het_mon":"品切れ",
"auto_khong_sap_xep":"並べ替えなし",
"auto_gia_thap_cao":"価格が低い順",
"auto_gia_cao_thap":"価格が高い順",
"auto_dang_loc_danh_muc_san_pham":"製品をフィルタリング中...",
"auto_khong_tim_thay_mon_an_nao_khop":"一致するメニューが見つかりません",
"auto_thuc_don_hien_tai_khong_co_mon":"現在のメニューにはこのアイテムがありません。フィルターをクリアするか、別の名前を検索してください。",
"auto_chi_tiet_mon_an":"ℹ️ メニューの詳細",
"auto_het_hang":"在庫切れ",
"auto_ma_mon":"メニューコード",
"auto_don_vi_tinh":"単位",
"auto_so_luong":"数量",
"auto_don_gia_vnd":"単価（VND）",
"auto_bao_gom_vat":"VATを含む（%）",
"auto_bao_gom_ppv":"サービス料を含む（%）",
"auto_loai_tien_te":"通貨",
"auto_vnd_viet_nam_dong":"VND（ベトナムドン）",
"auto_usd_do_la_my":"USD（米ドル）",
"auto_ty_gia":"為替レート",
"auto_ghi_chu":"メモ",
"auto_phan_nhom_thuc_don_he_thong":"メニュー分類（システム）",
"auto_nhom_san_pham":"製品グループ:",
"auto_goi_buffet":"ビュッフェパッケージ:",
"auto_goi_set_menu":"セットメニューパッケージ:",
"auto_goi_do_uong":"ドリンクパッケージ:",
"auto_tien_te":"通貨",
"auto_ghi_chu_chung":"一般メモ",
"auto_huy_bo_esc":"キャンセル（Esc）",
"auto_them_vao_gio_hang":"カートに追加",
"auto_1_chon_goi_an_phuc_vu_course_p":"1. フードパッケージを選択（Course Pack）:",
"auto_2_chon_nhom_do_uong_kem_theo_d":"2. ドリンクパッケージを選択（Drink Group）:",
"auto_nhom_a_soft_drink":"グループA - ソフトドリンク",
"auto_nuoc_ngot_uong_khong_gioi_han":"ソフトドリンク飲み放題（無料）",
"auto_nhom_b_premium_drink":"グループB - プレミアムドリンク",
"auto_ruou_bia_cao_cap_uong_trong_2":"プレミアムアルコール2時間（無料）",
"auto_nhom_c_premium_alt":"グループC - プレミアム代替",
"auto_ruou_bia_thay_the_dung_2_gio_f":"代替アルコール2時間（無料）",
"auto_nhom_d_a_la_carte":"グループD - アラカルト",
"auto_goi_do_uong_le_tinh_tien_rieng":"ドリンクを個別に注文する",
"auto_3_ngon_ngu_giao_dien_hien_thi":"3. タブレットインターフェース言語:",
"auto_tieng_viet":"🇻🇳 Tiếng Việt",
"auto_huy_bo_quay_lai":"キャンセル / 戻る",
"auto_pin_sua_cau_hinh":"🔓 設定PIN",
"auto_xac_nhan_khoa_course":"🔒 確認とコースロック",
"auto_ma_pin_xac_thuc_quan_ly":"マネージャー確認PIN",
"auto_nhap_ma_pin_cua_quan_ly_de_mo":"コース設定のロックを解除するにはマネージャーのPINを入力してください。",
"auto_tim_kiem":"検索...",
"auto_them_ghi_chu_dac_thu_it_da_nhi":"特定のメモを追加（氷少なめ、水多め、ネギ抜きなど）...",
"auto_them_ghi_chu_cho_ca_mon_an":"料理全体にメモを追加...",
"auto_them_ghi_chu_rieng_cho_lua_cho":"この選択肢に個別のメモを追加...",
"auto_xem_hoa_don_tam_tinh":"仮請求書を表示",
"auto_cau_hinh_goi_ngon_ngu":"パッケージ/言語設定",
"auto_xoa_mon_khoi_gio":"カートから削除",
"auto_favoriteids_includes_product_i":"favoriteIds.includes(product.id) ? 'お気に入りから削除' : 'お気に入りに追加'",
"auto_xem_chi_tiet_tuy_chon":"詳細とオプションを表示",
"auto_he_thong":"システム",
"auto_tong_quan_he_thong":"システム概要",
"auto_quan_ly_tai_khoan":"アカウント管理",
"auto_cau_hinh_du_lieu":"データ設定",
"auto_thuc_don_goi_menu":"メニューとパッケージ",
"auto_so_do_ban":"フロアマップ",
"auto_cau_hinh_kpi_kgi":"KPI/KGI設定",
"auto_nhat_ky_he_thong_audit":"システム監査ログ",
"auto_dang_xuat":"ログアウト",
"auto_quan_tri_he_thong":"システム管理",
"auto_chi_nhanh_quan_1":"1区支店",
"auto_quan_ly_het_mon":"在庫切れ管理",
"auto_bao_cao_phan_tich":"レポートと分析",
"auto_bang_dieu_khien":"ダッシュボード",
"auto_bao_cao_doanh_thu":"収益レポート",
"auto_gia_von_cogs":"売上原価",
"auto_phan_tich_marketing":"マーケティング分析",
"auto_khach_hang_crm":"顧客管理（CRM）",
"auto_ton_kho":"在庫",
"auto_nghiep_vu":"業務",
"auto_thu_ngan":"レジ",
"auto_ung_dung_phuc_vu":"サービスアプリ",
"auto_quan_ly_ca":"シフト管理",
"auto_chi_nhanh_nguu_cat_q_1":"支店：Nguu Cat 1区",
"auto_hoat_dong":"オペレーション",
"auto_chon_mon":"メニュー選択",
"auto_tong_ket_ca":"シフトサマリー",
"auto_thu_ngan_01":"レジ 01",
"auto_chi_nhanh_1":"支店 1",
"auto_nghiep_vu_phuc_vu":"サービス業務",
"auto_dang_phuc_vu":"サービス中",
"auto_nguyen_van_a":"Nguyen Van A",
"auto_nhan_vien_phuc_vu_nv01":"ウェイター (NV01)"
};

function inject(filePath, obj, lang) {
    let content = fs.readFileSync(filePath, 'utf8');
    let lines = content.split('\n');
    let exportIdx = lines.findIndex(l => l.includes('export default {'));
    
    let added = 0;
    for(const [k, v] of Object.entries(keys)) {
        if (!content.includes(k + ':')) {
            let translated = v; // fallback to vi
            if (lang === 'en' && enMap[k]) translated = enMap[k];
            if (lang === 'ja' && jaMap[k]) translated = jaMap[k];
            lines.splice(exportIdx + 1, 0, `  ${k}: '${translated.replace(/'/g, "\\'")}',`);
            added++;
        }
    }
    fs.writeFileSync(filePath, lines.join('\n'));
    console.log(`Injected ${added} keys into ${filePath}`);
}

inject('src/locales/vi.ts', keys, 'vi');
inject('src/locales/en.ts', keys, 'en');
inject('src/locales/ja.ts', keys, 'ja');

