import { defineStore } from 'pinia';
import { setI18nLocale, i18n } from '@/locales';

export type Lang = 'vi' | 'en' | 'ja';

const dict: Record<Lang, Record<string, string>> = {
  vi: {
    // Hall / Checkout
    'hall.title':              'Tiền Sảnh',
    'hall.dashboard':          'Bảng Điều Khiển',
    'hall.floor_plan':         'Sơ Đồ Bàn',
    'hall.service_requests':   'Yêu Cầu Phục Vụ',
    'hall.checkout':           'Thanh Toán',
    'checkout.subtotal':       'Tạm tính',
    'checkout.discount_tier':  'Ưu đãi hội viên',
    'checkout.discount_voucher':'Mã giảm giá',
    'checkout.discount_points':'Đổi điểm',
    'checkout.service_charge': 'Phụ thu dịch vụ',
    'checkout.vat':            'Thuế VAT',
    'checkout.grand_total':    'Tổng cộng',
    'checkout.payment_method': 'Phương thức thanh toán',
    'checkout.points_preview': '{points} điểm = -{amount}đ',
    'checkout.confirm':        'Xác nhận thanh toán',
    'checkout.success':        'Thanh toán thành công!',
    'checkout.receipt.print':  'In hóa đơn',
    // Service Requests
    'service.call_waiter':     'Gọi nhân viên',
    'service.request_bill':    'Yêu cầu thanh toán',
    'service.condiment':       'Yêu cầu gia vị',
    'service.complaint':       'Phản hồi',
    'service.open':            'Mới',
    'service.in_progress':     'Đang xử lý',
    'service.resolved':        'Đã xử lý',
    'service.urgent':          'Khẩn cấp',
    'service.sent':            'Yêu cầu đã được gửi!',
    // Reservations
    'reservation.title':       'Đặt Bàn',
    'reservation.create':      'Đặt bàn mới',
    'reservation.date':        'Ngày',
    'reservation.time':        'Giờ',
    'reservation.guests':      'Số khách',
    'reservation.status.pending':  'Chờ xác nhận',
    'reservation.status.confirmed':'Đã xác nhận',
    'reservation.status.seated':   'Đã vào bàn',
    'reservation.status.completed':'Hoàn thành',
    'reservation.status.no_show':  'Không đến',
    'reservation.confirm_table':   'Xác nhận bàn',
    'reservation.seat_now':        'Cho khách vào bàn',
    'reservation.no_show':         'Đánh dấu không đến',
    // Purchasing
    'purchasing.title':          'Mua Hàng',
    'purchasing.purchase_order': 'Đơn Đặt Hàng',
    'purchasing.po_number':      'Số PO',
    'purchasing.supplier':       'Nhà cung cấp',
    'purchasing.expected_delivery':'Ngày giao dự kiến',
    'purchasing.receive':        'Xác nhận nhận hàng',
    'purchasing.status.draft':   'Bản nháp',
    'purchasing.status.submitted':'Đã gửi',
    'purchasing.status.received':'Đã nhận',
    'purchasing.status.partial': 'Nhận một phần',
    // Accounting
    'accounting.title':          'Kế Toán',
    'accounting.revenue':        'Doanh Thu',
    'accounting.expense':        'Chi Phí',
    'accounting.profit_loss':    'Lợi Nhuận & Lỗ',
    'accounting.tax':            'Thuế',
    'accounting.gross_revenue':  'Doanh thu gộp',
    'accounting.net_revenue':    'Doanh thu thuần',
    'accounting.gross_profit':   'Lợi nhuận gộp',
    'accounting.profit_margin':  'Biên lợi nhuận',
    'accounting.vat_collected':  'VAT thu được',
    'accounting.generate_tax':   'Lập tờ khai thuế',
    'accounting.void_invoice':   'Hủy hóa đơn',
    // Campaigns
    'campaign.title':            'Chiến Dịch',
    'campaign.create':           'Tạo chiến dịch',
    'campaign.type.seasonal':    'Theo mùa',
    'campaign.type.loyalty':     'Khách thân thiết',
    'campaign.type.flash':       'Flash Sale',
    'campaign.status.draft':     'Bản nháp',
    'campaign.status.pending':   'Chờ phê duyệt',
    'campaign.status.approved':  'Đã phê duyệt',
    'campaign.status.active':    'Đang chạy',
    'campaign.submit_approval':  'Gửi phê duyệt',
    // BOD
    'bod.title':               'Ban Giám Đốc',
    'bod.dashboard':           'Tổng Quan',
    'bod.approvals':           'Phê Duyệt',
    'bod.kpi':                 'Chỉ Tiêu KPI',
    'bod.budget':              'Ngân Sách',
    'bod.revenue_target':      'Mục tiêu doanh thu',
    'bod.breakeven':           'Điểm hòa vốn',
    'bod.vs_target':           'Thực tế / Mục tiêu',
    'bod.approve':             'Phê duyệt',
    'bod.reject':              'Từ chối',
    // Feedback
    'feedback.title':          'Đánh Giá',
    'feedback.overall':        'Đánh giá tổng thể',
    'feedback.food':           'Chất lượng món ăn',
    'feedback.service':        'Chất lượng phục vụ',
    'feedback.ambiance':       'Không gian',
    'feedback.comment':        'Nhận xét',
    'feedback.submit':         'Gửi đánh giá',
    'feedback.thank_you':      'Cảm ơn bạn đã đánh giá!',
    'feedback.respond':        'Phản hồi',
    // Inventory
    'inventory.title':                'Quản Lý Kho',
    'inventory.lowStock':             'Tồn kho thấp',
    'inventory.expiryWarning':        'Sắp hết hạn',
    'inventory.addStock':             'Nhập kho',
    'inventory.adjust':               'Điều chỉnh',
    'inventory.unit':                 'ĐVT',
    'inventory.quantity':             'Số lượng',
    'inventory.threshold':            'Ngưỡng cảnh báo',
    'inventory.search':               'Tìm nguyên liệu...',
    // Requisition
    'req.title':                      'Phiếu Yêu Cầu',
    'req.create':                     'Tạo phiếu',
    'req.status.pending':             'Chờ duyệt',
    'req.status.approved':            'Đã duyệt',
    'req.status.rejected':            'Từ chối',
    'req.status.processing':          'Đang xử lý',
    'req.status.completed':           'Hoàn thành',
    'req.status.cancelled':           'Đã hủy',
    'req.type.outbound':              'Xuất kho',
    'req.type.inbound':               'Nhập kho',
    'req.type.return':                'Trả hàng',
    'req.approve':                    'Duyệt',
    'req.reject':                     'Từ chối',
    'req.confirm_delivery':           'Xác nhận nhận hàng',
    'req.rejection_reason':           'Lý do từ chối',
    'req.needed_by':                  'Cần trước ngày',
    // Shift
    'shift.start':                    'Bắt đầu ca',
    'shift.close':                    'Đóng ca',
    'shift.handover':                 'Bàn giao ca',
    'shift.type.morning':             'Ca Sáng',
    'shift.type.afternoon':           'Ca Chiều',
    'shift.type.evening':             'Ca Tối',
    'shift.count_ingredients':        'Kiểm kê nguyên liệu',
    'shift.discrepancy':              'Chênh lệch',
    // Tablet
    'tablet.touch_to_start':          'Chạm để bắt đầu',
    'tablet.select_language':         'Chọn ngôn ngữ',
    // Branch
    'branch.title':                   'Chi Nhánh',
    'branch.add':                     'Thêm chi nhánh',
    'branch.edit':                    'Chỉnh sửa',
    'branch.deactivate':              'Vô hiệu hóa',
    'branch.capacity':                'Sức chứa',
    'branch.manager':                 'Quản lý',
    // Integrations
    'integration.title':              'Tích hợp',
    'integration.payment':            'Thanh toán',
    'integration.delivery':           'Giao hàng',
    'integration.test_connection':    'Kiểm tra kết nối',
    'integration.api_key':            'API Key',
    'integration.webhook':            'Webhook URL',
    // Common
    'common.save':                    'Lưu',
    'common.cancel':                  'Hủy',
    'common.confirm':                 'Xác nhận',
    'common.loading':                 'Đang tải...',
    'common.error':                   'Lỗi',
    'common.success':                 'Thành công',
    'common.search':                  'Tìm kiếm',
    'common.no_data':                 'Không có dữ liệu',
  
    // Reception Keys
    'reception.checkout.title': 'Tiêu đề',
    'reception.checkout.no_open_invoice': 'No open invoice',
    'reception.checkout.script_title': 'Script Tiêu đề',
    'reception.checkout.script_content': 'Script content',
    'reception.checkout.step1_title': 'Step1 Tiêu đề',
    'reception.checkout.phone_placeholder': 'Số điện thoại placeholder',
    'reception.checkout.search': 'Tìm kiếm',
    'reception.checkout.member': 'Thành viên',
    'reception.checkout.customer_not_found': 'Customer not found',
    'reception.checkout.step2_title': 'Step2 Tiêu đề',
    'reception.checkout.revenue_type': 'Doanh thu type',
    'reception.checkout.dinner': 'Dinner',
    'reception.checkout.lunch': 'Lunch',
    'reception.checkout.wine': 'Wine',
    'reception.checkout.delivery': 'Delivery',
    'reception.checkout.other': 'Other',
    'reception.checkout.enter_voucher': 'Enter voucher',
    'reception.checkout.voucher_placeholder': 'Voucher placeholder',
    'reception.checkout.apply': 'Áp dụng',
    'reception.checkout.voucher_applied_notice': 'Voucher applied notice',
    'reception.checkout.step3_title': 'Step3 Tiêu đề',
    'reception.checkout.received_amount': 'Received Số tiền',
    'reception.checkout.change_amount': 'Tiền thừa Số tiền',
    'reception.checkout.insufficient_amount': 'Insufficient Số tiền',
    'reception.checkout.reference_code': 'Reference code',
    'reception.checkout.card_last_4': 'Card last 4',
    'reception.checkout.transaction_code': 'Transaction code',
    'reception.checkout.simulation_notice': 'Simulation notice',
    'reception.checkout.voucher_payment_notice': 'Voucher payment notice',
    'reception.checkout.invoice_summary': 'Invoice summary',
    'reception.checkout.guest_count': 'Khách count',
    'reception.checkout.loading_invoice': 'Đang tải invoice',
    'reception.checkout.no_items': 'Không có món',
    'reception.checkout.subtotal': 'SubTổng cộng',
    'reception.checkout.vat': 'VAT',
    'reception.checkout.voucher': 'Voucher',
    'reception.checkout.will_apply': 'Will Áp dụng',
    'reception.checkout.total_amount': 'Tổng cộng Số tiền',
    'reception.checkout.processing': 'Processing',
    'reception.checkout.print_invoice_close_table': 'Print invoice close Bàn',
    'reception.checkout.enter_amount_warning': 'Enter Số tiền warning',
    'reception.checkout.cash': 'Tiền mặt',
    'reception.checkout.card': 'Card',
    'reception.checkout.transfer': 'Transfer',
    'reception.checkout.voucher_label': 'Voucher label',
    'reception.checkout.loading': 'Đang tải',
    'reception.checkout.no_open_order': 'No open Gọi món',
    'reception.checkout.processing_payment': 'Processing payment',
    'reception.checkout.ready_to_pay': 'Ready to pay',
    'reception.checkout.voucher_will_be_checked': 'Voucher will be checked',
    'reception.checkout.voucher_check_msg': 'Voucher check msg',
    'reception.checkout.no_branch_error': 'No branch Lỗi',
    'reception.checkout.payment_condition_not_met': 'Payment condition not met',
    'reception.checkout.payment_success': 'Payment success',
    'reception.checkout.invoice_label': 'Invoice label',
    'reception.checkout.total_label': 'Tổng cộng label',
    'reception.checkout.change_label': 'Tiền thừa label',
    'reception.checkout.error': 'Lỗi',
    'reception.checkout.payment_failed': 'Payment failed',
    'reception.close_shift.title': 'Tiêu đề',
    'reception.close_shift.subtitle': 'SubTiêu đề',
    'reception.close_shift.export_csv': 'Export csv',
    'reception.close_shift.closing_shift': 'Closing shift',
    'reception.close_shift.confirm_close_shift': 'Confirm Đóng ca',
    'reception.close_shift.active_shift': 'Active shift',
    'reception.close_shift.opened_at': 'Opened at',
    'reception.close_shift.opening_cash': 'Opening Tiền mặt',
    'reception.close_shift.no_active_shift': 'No active shift',
    'reception.close_shift.revenue_by_type': 'Doanh thu by type',
    'reception.close_shift.loading': 'Đang tải',
    'reception.close_shift.dinner': 'Dinner',
    'reception.close_shift.bill_count': 'Bill count',
    'reception.close_shift.lunch': 'Lunch',
    'reception.close_shift.wine': 'Wine',
    'reception.close_shift.delivery': 'Delivery',
    'reception.close_shift.order_count': 'Gọi món count',
    'reception.close_shift.total_daily_revenue': 'Tổng cộng daily Doanh thu',
    'reception.close_shift.cash_reconciliation': 'Tiền mặt reconciliation',
    'reception.close_shift.initial_cash': 'Initial Tiền mặt',
    'reception.close_shift.cash_revenue': 'Tiền mặt Doanh thu',
    'reception.close_shift.expected_cash': 'Expected Tiền mặt',
    'reception.close_shift.non_cash_revenue': 'Non Tiền mặt Doanh thu',
    'reception.close_shift.payment_history': 'Payment Lịch sử',
    'reception.close_shift.turn_count': 'Turn count',
    'reception.close_shift.time': 'Time',
    'reception.close_shift.payment_method': 'Payment method',
    'reception.close_shift.revenue_category': 'Doanh thu category',
    'reception.close_shift.amount': 'Số tiền',
    'reception.close_shift.received_from_guest': 'Received from Khách',
    'reception.close_shift.change': 'Tiền thừa',
    'reception.close_shift.no_data': 'No data',
    'reception.close_shift.cash_label': 'Tiền mặt label',
    'reception.close_shift.card_label': 'Card label',
    'reception.close_shift.transfer_label': 'Transfer label',
    'reception.close_shift.voucher_label': 'Voucher label',
    'reception.close_shift.other_label': 'Other label',
    'reception.close_shift.dinner_label': 'Dinner label',
    'reception.close_shift.lunch_label': 'Lunch label',
    'reception.close_shift.wine_label': 'Wine label',
    'reception.close_shift.delivery_label': 'Delivery label',
    'reception.close_shift.notification': 'Notification',
    'reception.close_shift.no_active_shift_alert': 'No active shift alert',
    'reception.close_shift.close_shift_title': 'Đóng ca Tiêu đề',
    'reception.close_shift.expected_cash_sys': 'Expected Tiền mặt sys',
    'reception.close_shift.actual_cash_placeholder': 'Actual Tiền mặt placeholder',
    'reception.close_shift.handover_notes': 'Handover notes',
    'reception.close_shift.confirm_close_btn': 'Confirm close btn',
    'reception.close_shift.cancel_btn': 'Cancel btn',
    'reception.close_shift.enter_actual_cash_warning': 'Enter actual Tiền mặt warning',
    'reception.close_shift.close_shift_success': 'Đóng ca success',
    'reception.close_shift.cash_diff': 'Tiền mặt diff',
    'reception.close_shift.expected_label': 'Expected label',
    'reception.close_shift.actual_label': 'Actual label',
    'reception.close_shift.error_title': 'Lỗi Tiêu đề',
    'reception.close_shift.close_shift_error': 'Đóng ca Lỗi',
    'reception.close_shift.no_shift_export_alert': 'No shift export alert',
    'reception.close_shift.success_title': 'Success Tiêu đề',
    'reception.close_shift.csv_downloaded': 'Csv downloaded',
    'reception.close_shift.export_csv_error': 'Export csv Lỗi',
    'reception_order.quyen_truy_cap_bi_tu_choi': 'Quyen truy cap bi tu choi',
    'reception_order.vui_long_chon_mot_ban_an_dang': 'Vui long chon mot ban an dang',
    'reception_order.di_toi_so_do_ban': 'Di toi so do ban',
    'reception_order.quay_lai_aria': 'Quay lai aria',
    'reception_order.quay_lai': 'Quay lai',
    'reception_order.nguu_cat_pos': 'Nguu cat pos',
    'reception_order.hoa_don': 'Hoa don',
    'reception_order.khach_hang': 'Khach hang',
    'reception_order.gio_mo': 'Gio mo',
    'reception_order.thoi_gian': 'Thoi gian',
    'reception_order.tim_kiem': 'Tim kiem',
    'reception_order.xem_hoa_don_tam_tinh': 'Xem hoa don tam tinh',
    'reception_order.cau_hinh_goi_ngon_ngu': 'Cau hinh goi ngon ngu',
    'reception_order.thoi_gian_do_uong_premium_da_k': 'Thoi gian do uong premium da k',
    'reception_order.mo_khoa_pin': 'Mo khoa pin',
    'reception_order.ban_phuc_vu': 'Ban phuc vu',
    'reception_order.ban_text': 'Ban text',
    'reception_order.xoa_het': 'Xoa het',
    'reception_order.ten_mon': 'Ten mon',
    'reception_order.don_gia': 'Don gia',
    'reception_order.thanh_tien': 'Thanh tien',
    'reception_order.hoa_don_trong': 'Hoa don trong',
    'reception_order.vui_long_chon_mon_an_tu_thuc_d': 'Vui long chon mon an tu thuc d',
    'reception_order.dvt': 'Dvt',
    'reception_order.xoa_mon_khoi_gio': 'Xoa mon khoi gio',
    'reception_order.trong_goi': 'Trong goi',
    'reception_order.0d': '0d',
    'reception_order.tam_tinh_mon_goi': 'Tam tinh mon goi',
    'reception_order.phi_dich_vu_5': 'Phi dich vu 5',
    'reception_order.thue_gtgt_vat_10': 'Thue gtgt VAT 10',
    'reception_order.tong_so_luong_mon': 'Tong so luong mon',
    'reception_order.mon': 'Mon',
    'reception_order.tong_thanh_toan_label': 'Tong thanh toan label',
    'reception_order.tam_luu': 'Tam luu',
    'reception_order.gui_bep': 'Gui bep',
    'reception_order.in_thanh_toan_bill': 'In thanh toan bill',
    'reception_order.yeu_thich_star': 'Yeu thich star',
    'reception_order.ban_chay_fire': 'Ban chay fire',
    'reception_order.moi_goi_clock': 'Moi goi clock',
    'reception_order.tat_ca_mon': 'Tat ca mon',
    'reception_order.con_mon': 'Con mon',
    'reception_order.het_mon': 'Het mon',
    'reception_order.khong_sap_xep': 'Khong sap xep',
    'reception_order.gia_thap_cao': 'Gia thap cao',
    'reception_order.gia_cao_thap': 'Gia cao thap',
    'reception_order.chi_mon_trong_goi': 'Chi mon trong goi',
    'reception_order.dang_loc_danh_muc_san_pham': 'Dang loc danh muc san pham',
    'reception_order.khong_tim_thay_mon_an_nao_khop': 'Khong tim thay mon an nao khop',
    'reception_order.thuc_don_hien_tai_khong_co_mon': 'Thuc don hien tai khong co mon',
    'reception_order.trong_goi_upper': 'Trong goi upper',
    'reception_order.chi_tiet_title': 'Chi tiet Tiêu đề',
    'reception_order.het_upper': 'Het upper',
    'reception_order.tat_ca': 'Tat ca',
    'reception_order.chi_tiet_mon_an': 'Chi tiet mon an',
    'reception_order.het_hang': 'Het hang',
    'reception_order.con_hang_phuc_vu_text': 'Con hang phuc vu text',
    'reception_order.het_hang_text': 'Het hang text',
    'reception_order.ma_mon': 'Ma mon',
    'reception_order.don_vi_tinh': 'Don vi tinh',
    'reception_order.so_luong': 'So luong',
    'reception_order.don_gia_vnd': 'Don gia vnd',
    'reception_order.0d_trong_goi': '0d trong goi',
    'reception_order.bao_gom_vat': 'Bao gom VAT',
    'reception_order.bao_gom_ppv': 'Bao gom ppv',
    'reception_order.loai_tien_te': 'Loai tien te',
    'reception_order.vnd_viet_nam_dong': 'Vnd viet nam dong',
    'reception_order.usd_do_la_my': 'Usd do la my',
    'reception_order.ty_gia': 'Ty gia',
    'reception_order.ghi_chu': 'Ghi chu',
    'reception_order.them_ghi_chu_dac_thu_it_da_nhi': 'Them ghi chu dac thu it da nhi',
    'reception_order.phan_nhom_thuc_don_he_thong': 'Phan nhom thuc don he thong',
    'reception_order.nhom_san_pham': 'Nhom san pham',
    'reception_order.goi_buffet': 'Goi buffet',
    'reception_order.goi_set_menu': 'Goi set menu',
    'reception_order.goi_do_uong': 'Goi do uong',
    'reception_order.ma': 'Ma',
    'reception_order.don_vi': 'Don vi',
    'reception_order.vat_percent': 'VAT percent',
    'reception_order.ppv_percent': 'Ppv percent',
    'reception_order.tien_te': 'Tien te',
    'reception_order.ghi_chu_chung': 'Ghi chu chung',
    'reception_order.them_ghi_chu_cho_ca_mon_an': 'Them ghi chu cho ca mon an',
    'reception_order.toi_thieu': 'Toi thieu',
    'reception_order.toi_da': 'Toi da',
    'reception_order.them_ghi_chu_rieng_cho_lua_cho': 'Them ghi chu rieng cho lua cho',
    'reception_order.vui_long_chon_them_it_nhat': 'Vui long chon them it nhat',
    'reception_order.lua_chon_nua': 'Lua chon nua',
    'reception_order.da_vuot_qua_gioi_han_toi_da': 'Da vuot qua gioi han toi da',
    'reception_order.lua_chon': 'Lua chon',
    'reception_order.da_chon_du_so_luong': 'Da chon du so luong',
    'reception_order.huy_bo_esc': 'Huy bo esc',
    'reception_order.them_vao_gio_hang': 'Them vao gio hang',
    'reception_order.cau_hinh_goi_course_phuc_vu': 'Cau hinh goi course phuc vu',
    'reception_order.1_chon_goi_an_phuc_vu_course_p': '1 chon goi an phuc vu course p',
    'reception_order.thoi_luong_phuc_vu_2_tieng': 'Thoi luong phuc vu 2 tieng',
    'reception_order.menu_goi_theo_bua_tiec': 'Menu goi theo bua tiec',
    'reception_order.ve': 'Ve',
    'reception_order.2_chon_nhom_do_uong_kem_theo_d': '2 chon nhom do uong kem theo d',
    'reception_order.nhom_a_soft_drink': 'Nhom a soft drink',
    'reception_order.nuoc_ngot_uong_khong_gioi_han': 'Nuoc ngot uong khong gioi han',
    'reception_order.nhom_b_premium_drink': 'Nhom b premium drink',
    'reception_order.ruou_bia_cao_cap_uong_trong_2': 'Ruou bia cao cap uong trong 2',
    'reception_order.nhom_c_premium_alt': 'Nhom c premium alt',
    'reception_order.ruou_bia_thay_the_dung_2_gio_f': 'Ruou bia thay the dung 2 gio f',
    'reception_order.nhom_d_a_la_carte': 'Nhom d a la carte',
    'reception_order.goi_do_uong_le_tinh_tien_rieng': 'Goi do uong le tinh tien rieng',
    'reception_order.3_ngon_ngu_giao_dien_hien_thi': '3 ngon ngu giao dien hien thi',
    'reception_order.tieng_viet': 'Tieng viet',
    'reception_order.huy_bo_quay_lai': 'Huy bo quay lai',
    'reception_order.pin_sua_cau_hinh': 'Pin sua cau hinh',
    'reception_order.xac_nhan_khoa_course': 'Xac nhan khoa course',
    'reception_order.ma_pin_xac_thuc_quan_ly': 'Ma pin xac thuc quan ly',
    'reception_order.nhap_ma_pin_cua_quan_ly_de_mo': 'Nhap ma pin cua quan ly de mo',
    'reception_order.khach_text': 'Khach text',
    'reception_order.gio_mo_text': 'Gio mo text',
    'reception_order.con_lai_text': 'Con lai text',
    'reception_order.tam_tinh_text': 'Tam tinh text',
    'reception_order.thue_gtgt_10_text': 'Thue gtgt 10 text',
    'reception_order.phi_phuc_vu_text': 'Phi phuc vu text',
    'reception_order.tong_cong_text': 'Tong cong text',
    'reception_order.thanh_toan_text': 'Thanh toan text',
    'reception_order.xem_tam_tinh_text': 'Xem tam tinh text',
    'reception_order.gio_hang_trong_text': 'Gio hang trong text',
    'reception_order.hay_chon_mon_tu_menu_text': 'Hay chon mon tu menu text',
    'reception_order.mon_yeu_thich_text': 'Mon yeu thich text',
    'reception_order.moi_goi_text': 'Moi goi text',
    'reception_order.ban_chay_text': 'Ban chay text',
    'reception_order.tim_mon_an_theo_ten_text': 'Tim mon an theo ten text',
    'reception_order.con_hang_text': 'Con hang text',
    'reception_order.tat_ca_text': 'Tat ca text',
    'reception_order.quay_lai_text': 'Quay lai text',
    'reception_order.luu_thay_doi_text': 'Luu thay doi text',
    'reception_order.tam_luu_text': 'Tam luu text',
    'reception_order.gui_vao_bep_text': 'Gui vao bep text',
    'reception_order.huy_thay_doi_text': 'Huy thay doi text',
    'reception_order.khoa_course_text': 'Khoa course text',
    'reception_order.khach_vang_lai_text': 'Khach vang lai text',
    'reception_order.khoa_course_thanh_cong': 'Khoa course thanh cong',
    'reception_order.nuoc_lau_di_kem': 'Nuoc lau di kem',
    'reception_order.lau_sukiyaki_ngot_thanh': 'Lau sukiyaki ngot thanh',
    'reception_order.lau_kimchi_chua_cay': 'Lau kimchi chua cay',
    'reception_order.lau_mala_tu_xuyen': 'Lau mala tu xuyen',
    'reception_order.lau_nam_thao_duoc': 'Lau nam thao duoc',
    'reception_order.lau_sua_dau_nanh': 'Lau sua dau nanh',
    'reception_order.chon_nuoc_lau_goi_buffet': 'Chon nuoc lau goi buffet',
    'reception_order.lau_sukiyaki_tieu_chuan': 'Lau sukiyaki tieu chuan',
    'reception_order.lau_kimchi_han_quoc': 'Lau kimchi han quoc',
    'reception_order.lau_nam_thao_moc': 'Lau nam thao moc',
    'reception_order.chon_mon_tang_kem': 'Chon mon tang kem',
    'reception_order.than_vai_bo_uc': 'Than vai bo uc',
    'reception_order.lon_bia_sapporo': 'Lon bia sapporo',
    'reception_order.dia_salad_bap_cai': 'Dia salad bap cai',
    'reception_order.mon_an_kem_chon_1': 'Mon an kem chon 1',
    'reception_order.canh_rong_bien': 'Canh rong bien',
    'reception_order.dia_kimchi_cai_thao': 'Dia kimchi cai thao',
    'reception_order.ly_hong_tra': 'Ly hong tra',
    'reception_order.khu_vuc': 'Khu vuc',
    'reception_order.trong_text': 'Trong text',
    'reception_order.da_dat_text': 'Da dat text',
    'reception_order.khach_den_text': 'Khach den text',
    'reception_order.dang_an_text': 'Dang an text',
    'reception_order.thoi_gian_an_con_lai_30_phut': 'Thoi gian an con lai 30 phut',
    'reception_order.thoi_gian_sap_het_10_phut': 'Thoi gian sap het 10 phut',
    'reception_order.phien_an_2_gio_da_ket_thuc': 'Phien an 2 gio da ket thuc',
    'reception_order.buffet_lau_upper': 'Buffet lau upper',
    'reception_order.khong_ap_dung': 'Khong ap dung',
    'reception_order.mon_tam_thoi_het_hang': 'Mon tam thoi het hang',
    'reception_order.da_dat_gioi_han_toi_da_10_phan': 'Da dat gioi han toi da 10 phan',
    'reception_order.da_them_vao_hoa_don': 'Da them vao hoa don',
    'reception_order.moi_luot_goi_toi_da_10_phan': 'Moi luot goi toi da 10 phan',
    'reception_order.xoa_mon_nay_khoi_don': 'Xoa mon nay khoi don',
    'reception_order.da_xoa_mon_khoi_gio': 'Da xoa mon khoi gio',
    'reception_order.ban_co_chac_muon_xoa_toan_bo_mon': 'Ban co chac muon xoa toan bo mon',
    'reception_order.da_xoa_toan_bo_mon': 'Da xoa toan bo mon',
    'reception_order.da_chon_gioi_han_toi_da': 'Da chon gioi han toi da',
    'reception_order.so_luong_goi_mon_vuot_qua': 'So luong goi mon vuot qua',
    'reception_order.da_them_mon_phan': 'Da them mon phan',
    'reception_order.vui_long_hoan_thanh_lua_chon': 'Vui long hoan thanh lua chon',
    'reception_order.da_them_mon_co_tuy_chon': 'Da them mon co tuy chon',
    'reception_order.da_bo_yeu_thich_mon': 'Da bo yeu thich mon',
    'reception_order.da_luu_mon_vao_yeu_thich': 'Da luu mon vao yeu thich',
    'reception_order.cau_hinh_da_bi_khoa': 'Cau hinh da bi khoa',
    'reception_order.nhom_thuc_uong_da_bi_khoa': 'Nhom thuc uong da bi khoa',
    'reception_order.vui_long_chon_goi_buffet': 'Vui long chon goi buffet',
    'reception_order.guestWalkIn': 'KháchWalkIn',
    'reception_order.courseLockedSuccess': 'CourseLockedSuccess',
    'reception_order.mo_khoa_cau_hinh_thanh_cong': 'Mo khoa cau hinh thanh cong',
    'reception_order.ma_pin_sai': 'Ma pin sai',
    'reception_order.hoa_don_tam_tinh_alert': 'Hoa don tam tinh alert',
    'reception_order.da_gui_lenh_in_tam_tinh': 'Da gui lenh in tam tinh',
    'reception_order.xac_nhan_thanh_toan': 'Xac nhan thanh toan',
    'reception_order.dong_ban_tam_tinh': 'Dong ban tam tinh',
    'reception_order.tien_hanh_thanh_toan': 'Tien hanh thanh toan',
    'reception_order.huy_text': 'Huy text',
    'reception_order.tai_khoan_chua_gan_chi_nhanh': 'Tai khoan chua gan chi nhanh',
    'reception_order.khong_tim_thay_ban': 'Khong tim thay ban',
    'reception_order.loi_text': 'Loi text',
    'reception_order.huy_bo_toan_bo_mon_an': 'Huy bo toan bo mon an',
    'reception_order.da_lam_trong_gio_hang': 'Da lam trong gio hang',
    'reception_order.da_luu_tam_don_hang': 'Da luu tam don hang',
    'reception_order.chua_co_mon_an_de_gui_bep': 'Chua co mon an de gui bep',
    'reception_order.chua_chon_ban': 'Chua chon ban',
    'reception_order.da_gui_mon_den_kds': 'Da gui mon den kds',
    'reception_order.bo_qua_mon_chua_map_db': 'Bo qua mon chua map db',
    'reception_order.gui_bep_that_bai': 'Gui bep that bai',
    'reception_order.mot_phut': 'Mot phut',
    'reception_order.da_luu_cau_hinh_mon_an': 'Da luu cau hinh mon an',
    'reception_order.buffet_lau': 'Buffet lau',
    'reception_order.da_cau_hinh_goi': 'Da cau hinh goi',
  
    // Dashboard Keys
    'reception.dashboard.loading_data': 'Loading data',
    'reception.dashboard.shift_overview': 'Ca làm việc Tổng quan',
    'reception.dashboard.today': 'Hôm nay',
    'reception.dashboard.tables_in_use': 'Bàns in use',
    'reception.dashboard.pending_checkout': 'Pending Thanh toán',
    'reception.dashboard.today_reservations': 'Hôm nay Đặt bàns',
    'reception.dashboard.active_shift': 'Active Ca làm việc',
    'reception.dashboard.opened_at': 'Opened at',
    'reception.dashboard.opening_cash': 'Opening cash',
    'reception.dashboard.needs_action_now': 'Needs Hành động now',
    'reception.dashboard.checkout_request': 'Thanh toán request',
    'reception.dashboard.guests': 'Kháchs',
    'reception.dashboard.proceed_to_checkout': 'Proceed to Thanh toán',
    'reception.dashboard.no_checkout_requests': 'No Thanh toán requests',
    'reception.dashboard.tables_serving_list': 'Bàns serving list',
    'reception.dashboard.table_code': 'Bàn Mã',
    'reception.dashboard.guest_col': 'Khách col',
    'reception.dashboard.time_col': 'Thời gian col',
    'reception.dashboard.status_col': 'Trạng thái col',
    'reception.dashboard.invoice_col': 'Hóa đơn col',
    'reception.dashboard.dining': 'Dining',
    'reception.dashboard.checkout_action': 'Thanh toán Hành động',
    'reception.dashboard.no_tables_serving': 'No Bàns serving',
    'reception.dashboard.booking_code': 'Booking Mã',
    'reception.dashboard.hour': 'Hour',
    'reception.dashboard.num_guests': 'Num Kháchs',
    'reception.dashboard.no_bookings_today': 'No bookings Hôm nay',
    'reception.dashboard.no_branch_error': 'No branch error',

    // Purchasing
    'purchasing.title': 'Mua Hàng',
    'purchasing.po_list': 'Đơn Đặt Hàng',
    'purchasing.create_po': 'Tạo Đơn Hàng',
    'purchasing.requisitions': 'Yêu Cầu Mua Hàng',
    'purchasing.suppliers': 'Nhà Cung Cấp',

    // Accounting
    'accounting.title': 'Kế Toán',
    'accounting.invoices': 'Hóa Đơn',
    'accounting.tax_export': 'Xuất Thuế',
    'accounting.inventory_valuation': 'Giá Trị Tồn Kho',

    // CRM
    'crm.title': 'Khách Hàng',
    'crm.customers': 'Danh Sách KH',
    'crm.vouchers': 'Khuyến Mãi',
    'crm.feedback': 'Phản Hồi',

    // Marketing
    'marketing.title': 'Marketing',
    'marketing.campaigns': 'Chiến Dịch',
    'marketing.analytics': 'Phân Tích',

    // BOD
    'bod.title': 'Ban Giám Đốc',
    'bod.hq_dashboard': 'Tổng Quan HQ',
    'bod.branch_performance': 'Hiệu Suất CN',
    'bod.audit_logs': 'Nhật Ký Hệ Thống',
    'bod.system_config': 'Cấu Hình',
  },
  en: {
    // Hall / Checkout
    'hall.title':              'Hall',
    'hall.dashboard':          'Dashboard',
    'hall.floor_plan':         'Floor Plan',
    'hall.service_requests':   'Service Requests',
    'hall.checkout':           'Checkout',
    'checkout.subtotal':       'Subtotal',
    'checkout.discount_tier':  'Member Discount',
    'checkout.discount_voucher':'Voucher',
    'checkout.discount_points':'Redeem Points',
    'checkout.service_charge': 'Service Charge',
    'checkout.vat':            'VAT',
    'checkout.grand_total':    'Grand Total',
    'checkout.payment_method': 'Payment Method',
    'checkout.points_preview': '{points} points = -{amount}đ',
    'checkout.confirm':        'Confirm Payment',
    'checkout.success':        'Payment successful!',
    'checkout.receipt.print':  'Print Receipt',
    // Service Requests
    'service.call_waiter':     'Call Waiter',
    'service.request_bill':    'Request Bill',
    'service.condiment':       'Request Condiment',
    'service.complaint':       'Feedback',
    'service.open':            'New',
    'service.in_progress':     'In Progress',
    'service.resolved':        'Resolved',
    'service.urgent':          'Urgent',
    'service.sent':            'Request sent!',
    // Reservations
    'reservation.title':       'Reservations',
    'reservation.create':      'New Reservation',
    'reservation.date':        'Date',
    'reservation.time':        'Time',
    'reservation.guests':      'Guests',
    'reservation.status.pending':  'Pending',
    'reservation.status.confirmed':'Confirmed',
    'reservation.status.seated':   'Seated',
    'reservation.status.completed':'Completed',
    'reservation.status.no_show':  'No Show',
    'reservation.confirm_table':   'Confirm Table',
    'reservation.seat_now':        'Seat Now',
    'reservation.no_show':         'Mark No Show',
    // Purchasing
    'purchasing.title':          'Purchasing',
    'purchasing.purchase_order': 'Purchase Order',
    'purchasing.po_number':      'PO Number',
    'purchasing.supplier':       'Supplier',
    'purchasing.expected_delivery':'Expected Delivery',
    'purchasing.receive':        'Receive Goods',
    'purchasing.status.draft':   'Draft',
    'purchasing.status.submitted':'Submitted',
    'purchasing.status.received':'Received',
    'purchasing.status.partial': 'Partial',
    // Accounting
    'accounting.title':          'Accounting',
    'accounting.revenue':        'Revenue',
    'accounting.expense':        'Expense',
    'accounting.profit_loss':    'Profit & Loss',
    'accounting.tax':            'Tax',
    'accounting.gross_revenue':  'Gross Revenue',
    'accounting.net_revenue':    'Net Revenue',
    'accounting.gross_profit':   'Gross Profit',
    'accounting.profit_margin':  'Profit Margin',
    'accounting.vat_collected':  'VAT Collected',
    'accounting.generate_tax':   'Generate Tax Record',
    'accounting.void_invoice':   'Void Invoice',
    // Campaigns
    'campaign.title':            'Campaigns',
    'campaign.create':           'Create Campaign',
    'campaign.type.seasonal':    'Seasonal',
    'campaign.type.loyalty':     'Loyalty',
    'campaign.type.flash':       'Flash Sale',
    'campaign.status.draft':     'Draft',
    'campaign.status.pending':   'Pending Approval',
    'campaign.status.approved':  'Approved',
    'campaign.status.active':    'Active',
    'campaign.submit_approval':  'Submit for Approval',
    // BOD
    'bod.title':               'Board of Directors',
    'bod.dashboard':           'Dashboard',
    'bod.approvals':           'Approvals',
    'bod.kpi':                 'KPI Target',
    'bod.budget':              'Budget',
    'bod.revenue_target':      'Revenue Target',
    'bod.breakeven':           'Break-even',
    'bod.vs_target':           'Actual / Target',
    'bod.approve':             'Approve',
    'bod.reject':              'Reject',
    // Feedback
    'feedback.title':          'Feedback',
    'feedback.overall':        'Overall',
    'feedback.food':           'Food Quality',
    'feedback.service':        'Service Quality',
    'feedback.ambiance':       'Ambiance',
    'feedback.comment':        'Comment',
    'feedback.submit':         'Submit Feedback',
    'feedback.thank_you':      'Thank you for your feedback!',
    'feedback.respond':        'Respond',
    'inventory.title':                'Inventory Management',
    'inventory.lowStock':             'Low Stock',
    'inventory.expiryWarning':        'Expiring Soon',
    'inventory.addStock':             'Add Stock',
    'inventory.adjust':               'Adjust Count',
    'inventory.unit':                 'Unit',
    'inventory.quantity':             'Quantity',
    'inventory.threshold':            'Alert Threshold',
    'inventory.search':               'Search ingredients...',
    'req.title':                      'Requisitions',
    'req.create':                     'New Requisition',
    'req.status.pending':             'Pending Approval',
    'req.status.approved':            'Approved',
    'req.status.rejected':            'Rejected',
    'req.status.processing':          'Processing',
    'req.status.completed':           'Completed',
    'req.status.cancelled':           'Cancelled',
    'req.type.outbound':              'Outbound',
    'req.type.inbound':               'Inbound',
    'req.type.return':                'Return',
    'req.approve':                    'Approve',
    'req.reject':                     'Reject',
    'req.confirm_delivery':           'Confirm Delivery',
    'req.rejection_reason':           'Reason for rejection',
    'req.needed_by':                  'Needed by',
    'shift.start':                    'Start Shift',
    'shift.close':                    'Close Shift',
    'shift.handover':                 'Shift Handover',
    'shift.type.morning':             'Morning Shift',
    'shift.type.afternoon':           'Afternoon Shift',
    'shift.type.evening':             'Evening Shift',
    'shift.count_ingredients':        'Count Ingredients',
    'shift.discrepancy':              'Discrepancy',
    'tablet.touch_to_start':          'Touch to Begin',
    'tablet.select_language':         'Select Language',
    'branch.title':                   'Branches',
    'branch.add':                     'Add Branch',
    'branch.edit':                    'Edit',
    'branch.deactivate':              'Deactivate',
    'branch.capacity':                'Capacity',
    'branch.manager':                 'Manager',
    'integration.title':              'Integrations',
    'integration.payment':            'Payment',
    'integration.delivery':           'Delivery',
    'integration.test_connection':    'Test Connection',
    'integration.api_key':            'API Key',
    'integration.webhook':            'Webhook URL',
    'common.save':                    'Save',
    'common.cancel':                  'Cancel',
    'common.confirm':                 'Confirm',
    'common.loading':                 'Loading...',
    'common.error':                   'Error',
    'common.success':                 'Success',
    'common.search':                  'Search',
    'common.no_data':                 'No data',
  
    // Reception Keys
    'reception.checkout.title': 'Title',
    'reception.checkout.no_open_invoice': 'No open invoice',
    'reception.checkout.script_title': 'Script title',
    'reception.checkout.script_content': 'Script content',
    'reception.checkout.step1_title': 'Step1 title',
    'reception.checkout.phone_placeholder': 'Phone placeholder',
    'reception.checkout.search': 'Search',
    'reception.checkout.member': 'Member',
    'reception.checkout.customer_not_found': 'Customer not found',
    'reception.checkout.step2_title': 'Step2 title',
    'reception.checkout.revenue_type': 'Revenue type',
    'reception.checkout.dinner': 'Dinner',
    'reception.checkout.lunch': 'Lunch',
    'reception.checkout.wine': 'Wine',
    'reception.checkout.delivery': 'Delivery',
    'reception.checkout.other': 'Other',
    'reception.checkout.enter_voucher': 'Enter voucher',
    'reception.checkout.voucher_placeholder': 'Voucher placeholder',
    'reception.checkout.apply': 'Apply',
    'reception.checkout.voucher_applied_notice': 'Voucher applied notice',
    'reception.checkout.step3_title': 'Step3 title',
    'reception.checkout.received_amount': 'Received amount',
    'reception.checkout.change_amount': 'Change amount',
    'reception.checkout.insufficient_amount': 'Insufficient amount',
    'reception.checkout.reference_code': 'Reference code',
    'reception.checkout.card_last_4': 'Card last 4',
    'reception.checkout.transaction_code': 'Transaction code',
    'reception.checkout.simulation_notice': 'Simulation notice',
    'reception.checkout.voucher_payment_notice': 'Voucher payment notice',
    'reception.checkout.invoice_summary': 'Invoice summary',
    'reception.checkout.guest_count': 'Guest count',
    'reception.checkout.loading_invoice': 'Loading invoice',
    'reception.checkout.no_items': 'No items',
    'reception.checkout.subtotal': 'Subtotal',
    'reception.checkout.vat': 'Vat',
    'reception.checkout.voucher': 'Voucher',
    'reception.checkout.will_apply': 'Will apply',
    'reception.checkout.total_amount': 'Total amount',
    'reception.checkout.processing': 'Processing',
    'reception.checkout.print_invoice_close_table': 'Print invoice close table',
    'reception.checkout.enter_amount_warning': 'Enter amount warning',
    'reception.checkout.cash': 'Cash',
    'reception.checkout.card': 'Card',
    'reception.checkout.transfer': 'Transfer',
    'reception.checkout.voucher_label': 'Voucher label',
    'reception.checkout.loading': 'Loading',
    'reception.checkout.no_open_order': 'No open order',
    'reception.checkout.processing_payment': 'Processing payment',
    'reception.checkout.ready_to_pay': 'Ready to pay',
    'reception.checkout.voucher_will_be_checked': 'Voucher will be checked',
    'reception.checkout.voucher_check_msg': 'Voucher check msg',
    'reception.checkout.no_branch_error': 'No branch error',
    'reception.checkout.payment_condition_not_met': 'Payment condition not met',
    'reception.checkout.payment_success': 'Payment success',
    'reception.checkout.invoice_label': 'Invoice label',
    'reception.checkout.total_label': 'Total label',
    'reception.checkout.change_label': 'Change label',
    'reception.checkout.error': 'Error',
    'reception.checkout.payment_failed': 'Payment failed',
    'reception.close_shift.title': 'Title',
    'reception.close_shift.subtitle': 'Subtitle',
    'reception.close_shift.export_csv': 'Export csv',
    'reception.close_shift.closing_shift': 'Closing shift',
    'reception.close_shift.confirm_close_shift': 'Confirm close shift',
    'reception.close_shift.active_shift': 'Active shift',
    'reception.close_shift.opened_at': 'Opened at',
    'reception.close_shift.opening_cash': 'Opening cash',
    'reception.close_shift.no_active_shift': 'No active shift',
    'reception.close_shift.revenue_by_type': 'Revenue by type',
    'reception.close_shift.loading': 'Loading',
    'reception.close_shift.dinner': 'Dinner',
    'reception.close_shift.bill_count': 'Bill count',
    'reception.close_shift.lunch': 'Lunch',
    'reception.close_shift.wine': 'Wine',
    'reception.close_shift.delivery': 'Delivery',
    'reception.close_shift.order_count': 'Order count',
    'reception.close_shift.total_daily_revenue': 'Total daily revenue',
    'reception.close_shift.cash_reconciliation': 'Cash reconciliation',
    'reception.close_shift.initial_cash': 'Initial cash',
    'reception.close_shift.cash_revenue': 'Cash revenue',
    'reception.close_shift.expected_cash': 'Expected cash',
    'reception.close_shift.non_cash_revenue': 'Non cash revenue',
    'reception.close_shift.payment_history': 'Payment history',
    'reception.close_shift.turn_count': 'Turn count',
    'reception.close_shift.time': 'Time',
    'reception.close_shift.payment_method': 'Payment method',
    'reception.close_shift.revenue_category': 'Revenue category',
    'reception.close_shift.amount': 'Amount',
    'reception.close_shift.received_from_guest': 'Received from guest',
    'reception.close_shift.change': 'Change',
    'reception.close_shift.no_data': 'No data',
    'reception.close_shift.cash_label': 'Cash label',
    'reception.close_shift.card_label': 'Card label',
    'reception.close_shift.transfer_label': 'Transfer label',
    'reception.close_shift.voucher_label': 'Voucher label',
    'reception.close_shift.other_label': 'Other label',
    'reception.close_shift.dinner_label': 'Dinner label',
    'reception.close_shift.lunch_label': 'Lunch label',
    'reception.close_shift.wine_label': 'Wine label',
    'reception.close_shift.delivery_label': 'Delivery label',
    'reception.close_shift.notification': 'Notification',
    'reception.close_shift.no_active_shift_alert': 'No active shift alert',
    'reception.close_shift.close_shift_title': 'Close shift title',
    'reception.close_shift.expected_cash_sys': 'Expected cash sys',
    'reception.close_shift.actual_cash_placeholder': 'Actual cash placeholder',
    'reception.close_shift.handover_notes': 'Handover notes',
    'reception.close_shift.confirm_close_btn': 'Confirm close btn',
    'reception.close_shift.cancel_btn': 'Cancel btn',
    'reception.close_shift.enter_actual_cash_warning': 'Enter actual cash warning',
    'reception.close_shift.close_shift_success': 'Close shift success',
    'reception.close_shift.cash_diff': 'Cash diff',
    'reception.close_shift.expected_label': 'Expected label',
    'reception.close_shift.actual_label': 'Actual label',
    'reception.close_shift.error_title': 'Error title',
    'reception.close_shift.close_shift_error': 'Close shift error',
    'reception.close_shift.no_shift_export_alert': 'No shift export alert',
    'reception.close_shift.success_title': 'Success title',
    'reception.close_shift.csv_downloaded': 'Csv downloaded',
    'reception.close_shift.export_csv_error': 'Export csv error',
    'reception_order.quyen_truy_cap_bi_tu_choi': 'Quyen truy cap bi tu choi',
    'reception_order.vui_long_chon_mot_ban_an_dang': 'Vui long chon mot ban an dang',
    'reception_order.di_toi_so_do_ban': 'Di toi so do ban',
    'reception_order.quay_lai_aria': 'Quay lai aria',
    'reception_order.quay_lai': 'Quay lai',
    'reception_order.nguu_cat_pos': 'Nguu cat pos',
    'reception_order.hoa_don': 'Hoa don',
    'reception_order.khach_hang': 'Khach hang',
    'reception_order.gio_mo': 'Gio mo',
    'reception_order.thoi_gian': 'Thoi gian',
    'reception_order.tim_kiem': 'Tim kiem',
    'reception_order.xem_hoa_don_tam_tinh': 'Xem hoa don tam tinh',
    'reception_order.cau_hinh_goi_ngon_ngu': 'Cau hinh goi ngon ngu',
    'reception_order.thoi_gian_do_uong_premium_da_k': 'Thoi gian do uong premium da k',
    'reception_order.mo_khoa_pin': 'Mo khoa pin',
    'reception_order.ban_phuc_vu': 'Ban phuc vu',
    'reception_order.ban_text': 'Ban text',
    'reception_order.xoa_het': 'Xoa het',
    'reception_order.ten_mon': 'Ten mon',
    'reception_order.don_gia': 'Don gia',
    'reception_order.thanh_tien': 'Thanh tien',
    'reception_order.hoa_don_trong': 'Hoa don trong',
    'reception_order.vui_long_chon_mon_an_tu_thuc_d': 'Vui long chon mon an tu thuc d',
    'reception_order.dvt': 'Dvt',
    'reception_order.xoa_mon_khoi_gio': 'Xoa mon khoi gio',
    'reception_order.trong_goi': 'Trong goi',
    'reception_order.0d': '0d',
    'reception_order.tam_tinh_mon_goi': 'Tam tinh mon goi',
    'reception_order.phi_dich_vu_5': 'Phi dich vu 5',
    'reception_order.thue_gtgt_vat_10': 'Thue gtgt vat 10',
    'reception_order.tong_so_luong_mon': 'Tong so luong mon',
    'reception_order.mon': 'Mon',
    'reception_order.tong_thanh_toan_label': 'Tong thanh toan label',
    'reception_order.tam_luu': 'Tam luu',
    'reception_order.gui_bep': 'Gui bep',
    'reception_order.in_thanh_toan_bill': 'In thanh toan bill',
    'reception_order.yeu_thich_star': 'Yeu thich star',
    'reception_order.ban_chay_fire': 'Ban chay fire',
    'reception_order.moi_goi_clock': 'Moi goi clock',
    'reception_order.tat_ca_mon': 'Tat ca mon',
    'reception_order.con_mon': 'Con mon',
    'reception_order.het_mon': 'Het mon',
    'reception_order.khong_sap_xep': 'Khong sap xep',
    'reception_order.gia_thap_cao': 'Gia thap cao',
    'reception_order.gia_cao_thap': 'Gia cao thap',
    'reception_order.chi_mon_trong_goi': 'Chi mon trong goi',
    'reception_order.dang_loc_danh_muc_san_pham': 'Dang loc danh muc san pham',
    'reception_order.khong_tim_thay_mon_an_nao_khop': 'Khong tim thay mon an nao khop',
    'reception_order.thuc_don_hien_tai_khong_co_mon': 'Thuc don hien tai khong co mon',
    'reception_order.trong_goi_upper': 'Trong goi upper',
    'reception_order.chi_tiet_title': 'Chi tiet title',
    'reception_order.het_upper': 'Het upper',
    'reception_order.tat_ca': 'Tat ca',
    'reception_order.chi_tiet_mon_an': 'Chi tiet mon an',
    'reception_order.het_hang': 'Het hang',
    'reception_order.con_hang_phuc_vu_text': 'Con hang phuc vu text',
    'reception_order.het_hang_text': 'Het hang text',
    'reception_order.ma_mon': 'Ma mon',
    'reception_order.don_vi_tinh': 'Don vi tinh',
    'reception_order.so_luong': 'So luong',
    'reception_order.don_gia_vnd': 'Don gia vnd',
    'reception_order.0d_trong_goi': '0d trong goi',
    'reception_order.bao_gom_vat': 'Bao gom vat',
    'reception_order.bao_gom_ppv': 'Bao gom ppv',
    'reception_order.loai_tien_te': 'Loai tien te',
    'reception_order.vnd_viet_nam_dong': 'Vnd viet nam dong',
    'reception_order.usd_do_la_my': 'Usd do la my',
    'reception_order.ty_gia': 'Ty gia',
    'reception_order.ghi_chu': 'Ghi chu',
    'reception_order.them_ghi_chu_dac_thu_it_da_nhi': 'Them ghi chu dac thu it da nhi',
    'reception_order.phan_nhom_thuc_don_he_thong': 'Phan nhom thuc don he thong',
    'reception_order.nhom_san_pham': 'Nhom san pham',
    'reception_order.goi_buffet': 'Goi buffet',
    'reception_order.goi_set_menu': 'Goi set menu',
    'reception_order.goi_do_uong': 'Goi do uong',
    'reception_order.ma': 'Ma',
    'reception_order.don_vi': 'Don vi',
    'reception_order.vat_percent': 'Vat percent',
    'reception_order.ppv_percent': 'Ppv percent',
    'reception_order.tien_te': 'Tien te',
    'reception_order.ghi_chu_chung': 'Ghi chu chung',
    'reception_order.them_ghi_chu_cho_ca_mon_an': 'Them ghi chu cho ca mon an',
    'reception_order.toi_thieu': 'Toi thieu',
    'reception_order.toi_da': 'Toi da',
    'reception_order.them_ghi_chu_rieng_cho_lua_cho': 'Them ghi chu rieng cho lua cho',
    'reception_order.vui_long_chon_them_it_nhat': 'Vui long chon them it nhat',
    'reception_order.lua_chon_nua': 'Lua chon nua',
    'reception_order.da_vuot_qua_gioi_han_toi_da': 'Da vuot qua gioi han toi da',
    'reception_order.lua_chon': 'Lua chon',
    'reception_order.da_chon_du_so_luong': 'Da chon du so luong',
    'reception_order.huy_bo_esc': 'Huy bo esc',
    'reception_order.them_vao_gio_hang': 'Them vao gio hang',
    'reception_order.cau_hinh_goi_course_phuc_vu': 'Cau hinh goi course phuc vu',
    'reception_order.1_chon_goi_an_phuc_vu_course_p': '1 chon goi an phuc vu course p',
    'reception_order.thoi_luong_phuc_vu_2_tieng': 'Thoi luong phuc vu 2 tieng',
    'reception_order.menu_goi_theo_bua_tiec': 'Menu goi theo bua tiec',
    'reception_order.ve': 'Ve',
    'reception_order.2_chon_nhom_do_uong_kem_theo_d': '2 chon nhom do uong kem theo d',
    'reception_order.nhom_a_soft_drink': 'Nhom a soft drink',
    'reception_order.nuoc_ngot_uong_khong_gioi_han': 'Nuoc ngot uong khong gioi han',
    'reception_order.nhom_b_premium_drink': 'Nhom b premium drink',
    'reception_order.ruou_bia_cao_cap_uong_trong_2': 'Ruou bia cao cap uong trong 2',
    'reception_order.nhom_c_premium_alt': 'Nhom c premium alt',
    'reception_order.ruou_bia_thay_the_dung_2_gio_f': 'Ruou bia thay the dung 2 gio f',
    'reception_order.nhom_d_a_la_carte': 'Nhom d a la carte',
    'reception_order.goi_do_uong_le_tinh_tien_rieng': 'Goi do uong le tinh tien rieng',
    'reception_order.3_ngon_ngu_giao_dien_hien_thi': '3 ngon ngu giao dien hien thi',
    'reception_order.tieng_viet': 'Tieng viet',
    'reception_order.huy_bo_quay_lai': 'Huy bo quay lai',
    'reception_order.pin_sua_cau_hinh': 'Pin sua cau hinh',
    'reception_order.xac_nhan_khoa_course': 'Xac nhan khoa course',
    'reception_order.ma_pin_xac_thuc_quan_ly': 'Ma pin xac thuc quan ly',
    'reception_order.nhap_ma_pin_cua_quan_ly_de_mo': 'Nhap ma pin cua quan ly de mo',
    'reception_order.khach_text': 'Khach text',
    'reception_order.gio_mo_text': 'Gio mo text',
    'reception_order.con_lai_text': 'Con lai text',
    'reception_order.tam_tinh_text': 'Tam tinh text',
    'reception_order.thue_gtgt_10_text': 'Thue gtgt 10 text',
    'reception_order.phi_phuc_vu_text': 'Phi phuc vu text',
    'reception_order.tong_cong_text': 'Tong cong text',
    'reception_order.thanh_toan_text': 'Thanh toan text',
    'reception_order.xem_tam_tinh_text': 'Xem tam tinh text',
    'reception_order.gio_hang_trong_text': 'Gio hang trong text',
    'reception_order.hay_chon_mon_tu_menu_text': 'Hay chon mon tu menu text',
    'reception_order.mon_yeu_thich_text': 'Mon yeu thich text',
    'reception_order.moi_goi_text': 'Moi goi text',
    'reception_order.ban_chay_text': 'Ban chay text',
    'reception_order.tim_mon_an_theo_ten_text': 'Tim mon an theo ten text',
    'reception_order.con_hang_text': 'Con hang text',
    'reception_order.tat_ca_text': 'Tat ca text',
    'reception_order.quay_lai_text': 'Quay lai text',
    'reception_order.luu_thay_doi_text': 'Luu thay doi text',
    'reception_order.tam_luu_text': 'Tam luu text',
    'reception_order.gui_vao_bep_text': 'Gui vao bep text',
    'reception_order.huy_thay_doi_text': 'Huy thay doi text',
    'reception_order.khoa_course_text': 'Khoa course text',
    'reception_order.khach_vang_lai_text': 'Khach vang lai text',
    'reception_order.khoa_course_thanh_cong': 'Khoa course thanh cong',
    'reception_order.nuoc_lau_di_kem': 'Nuoc lau di kem',
    'reception_order.lau_sukiyaki_ngot_thanh': 'Lau sukiyaki ngot thanh',
    'reception_order.lau_kimchi_chua_cay': 'Lau kimchi chua cay',
    'reception_order.lau_mala_tu_xuyen': 'Lau mala tu xuyen',
    'reception_order.lau_nam_thao_duoc': 'Lau nam thao duoc',
    'reception_order.lau_sua_dau_nanh': 'Lau sua dau nanh',
    'reception_order.chon_nuoc_lau_goi_buffet': 'Chon nuoc lau goi buffet',
    'reception_order.lau_sukiyaki_tieu_chuan': 'Lau sukiyaki tieu chuan',
    'reception_order.lau_kimchi_han_quoc': 'Lau kimchi han quoc',
    'reception_order.lau_nam_thao_moc': 'Lau nam thao moc',
    'reception_order.chon_mon_tang_kem': 'Chon mon tang kem',
    'reception_order.than_vai_bo_uc': 'Than vai bo uc',
    'reception_order.lon_bia_sapporo': 'Lon bia sapporo',
    'reception_order.dia_salad_bap_cai': 'Dia salad bap cai',
    'reception_order.mon_an_kem_chon_1': 'Mon an kem chon 1',
    'reception_order.canh_rong_bien': 'Canh rong bien',
    'reception_order.dia_kimchi_cai_thao': 'Dia kimchi cai thao',
    'reception_order.ly_hong_tra': 'Ly hong tra',
    'reception_order.khu_vuc': 'Khu vuc',
    'reception_order.trong_text': 'Trong text',
    'reception_order.da_dat_text': 'Da dat text',
    'reception_order.khach_den_text': 'Khach den text',
    'reception_order.dang_an_text': 'Dang an text',
    'reception_order.thoi_gian_an_con_lai_30_phut': 'Thoi gian an con lai 30 phut',
    'reception_order.thoi_gian_sap_het_10_phut': 'Thoi gian sap het 10 phut',
    'reception_order.phien_an_2_gio_da_ket_thuc': 'Phien an 2 gio da ket thuc',
    'reception_order.buffet_lau_upper': 'Buffet lau upper',
    'reception_order.khong_ap_dung': 'Khong ap dung',
    'reception_order.mon_tam_thoi_het_hang': 'Mon tam thoi het hang',
    'reception_order.da_dat_gioi_han_toi_da_10_phan': 'Da dat gioi han toi da 10 phan',
    'reception_order.da_them_vao_hoa_don': 'Da them vao hoa don',
    'reception_order.moi_luot_goi_toi_da_10_phan': 'Moi luot goi toi da 10 phan',
    'reception_order.xoa_mon_nay_khoi_don': 'Xoa mon nay khoi don',
    'reception_order.da_xoa_mon_khoi_gio': 'Da xoa mon khoi gio',
    'reception_order.ban_co_chac_muon_xoa_toan_bo_mon': 'Ban co chac muon xoa toan bo mon',
    'reception_order.da_xoa_toan_bo_mon': 'Da xoa toan bo mon',
    'reception_order.da_chon_gioi_han_toi_da': 'Da chon gioi han toi da',
    'reception_order.so_luong_goi_mon_vuot_qua': 'So luong goi mon vuot qua',
    'reception_order.da_them_mon_phan': 'Da them mon phan',
    'reception_order.vui_long_hoan_thanh_lua_chon': 'Vui long hoan thanh lua chon',
    'reception_order.da_them_mon_co_tuy_chon': 'Da them mon co tuy chon',
    'reception_order.da_bo_yeu_thich_mon': 'Da bo yeu thich mon',
    'reception_order.da_luu_mon_vao_yeu_thich': 'Da luu mon vao yeu thich',
    'reception_order.cau_hinh_da_bi_khoa': 'Cau hinh da bi khoa',
    'reception_order.nhom_thuc_uong_da_bi_khoa': 'Nhom thuc uong da bi khoa',
    'reception_order.vui_long_chon_goi_buffet': 'Vui long chon goi buffet',
    'reception_order.guestWalkIn': 'GuestWalkIn',
    'reception_order.courseLockedSuccess': 'CourseLockedSuccess',
    'reception_order.mo_khoa_cau_hinh_thanh_cong': 'Mo khoa cau hinh thanh cong',
    'reception_order.ma_pin_sai': 'Ma pin sai',
    'reception_order.hoa_don_tam_tinh_alert': 'Hoa don tam tinh alert',
    'reception_order.da_gui_lenh_in_tam_tinh': 'Da gui lenh in tam tinh',
    'reception_order.xac_nhan_thanh_toan': 'Xac nhan thanh toan',
    'reception_order.dong_ban_tam_tinh': 'Dong ban tam tinh',
    'reception_order.tien_hanh_thanh_toan': 'Tien hanh thanh toan',
    'reception_order.huy_text': 'Huy text',
    'reception_order.tai_khoan_chua_gan_chi_nhanh': 'Tai khoan chua gan chi nhanh',
    'reception_order.khong_tim_thay_ban': 'Khong tim thay ban',
    'reception_order.loi_text': 'Loi text',
    'reception_order.huy_bo_toan_bo_mon_an': 'Huy bo toan bo mon an',
    'reception_order.da_lam_trong_gio_hang': 'Da lam trong gio hang',
    'reception_order.da_luu_tam_don_hang': 'Da luu tam don hang',
    'reception_order.chua_co_mon_an_de_gui_bep': 'Chua co mon an de gui bep',
    'reception_order.chua_chon_ban': 'Chua chon ban',
    'reception_order.da_gui_mon_den_kds': 'Da gui mon den kds',
    'reception_order.bo_qua_mon_chua_map_db': 'Bo qua mon chua map db',
    'reception_order.gui_bep_that_bai': 'Gui bep that bai',
    'reception_order.mot_phut': 'Mot phut',
    'reception_order.da_luu_cau_hinh_mon_an': 'Da luu cau hinh mon an',
    'reception_order.buffet_lau': 'Buffet lau',
    'reception_order.da_cau_hinh_goi': 'Da cau hinh goi',
  
    // Dashboard Keys
    'reception.dashboard.loading_data': 'Loading data',
    'reception.dashboard.shift_overview': 'Shift overview',
    'reception.dashboard.today': 'Today',
    'reception.dashboard.tables_in_use': 'Tables in use',
    'reception.dashboard.pending_checkout': 'Pending checkout',
    'reception.dashboard.today_reservations': 'Today reservations',
    'reception.dashboard.active_shift': 'Active shift',
    'reception.dashboard.opened_at': 'Opened at',
    'reception.dashboard.opening_cash': 'Opening cash',
    'reception.dashboard.needs_action_now': 'Needs action now',
    'reception.dashboard.checkout_request': 'Checkout request',
    'reception.dashboard.guests': 'Guests',
    'reception.dashboard.proceed_to_checkout': 'Proceed to checkout',
    'reception.dashboard.no_checkout_requests': 'No checkout requests',
    'reception.dashboard.tables_serving_list': 'Tables serving list',
    'reception.dashboard.table_code': 'Table code',
    'reception.dashboard.guest_col': 'Guest col',
    'reception.dashboard.time_col': 'Time col',
    'reception.dashboard.status_col': 'Status col',
    'reception.dashboard.invoice_col': 'Invoice col',
    'reception.dashboard.dining': 'Dining',
    'reception.dashboard.checkout_action': 'Checkout action',
    'reception.dashboard.no_tables_serving': 'No tables serving',
    'reception.dashboard.booking_code': 'Booking code',
    'reception.dashboard.hour': 'Hour',
    'reception.dashboard.num_guests': 'Num guests',
    'reception.dashboard.no_bookings_today': 'No bookings today',
    'reception.dashboard.no_branch_error': 'No branch error',

    // Purchasing
    'purchasing.title': 'Purchasing',
    'purchasing.po_list': 'Purchase Orders',
    'purchasing.create_po': 'Create PO',
    'purchasing.requisitions': 'Requisitions',
    'purchasing.suppliers': 'Suppliers',

    // Accounting
    'accounting.title': 'Accounting',
    'accounting.invoices': 'Invoices',
    'accounting.tax_export': 'Tax Export',
    'accounting.inventory_valuation': 'Inventory Val.',

    // CRM
    'crm.title': 'CRM',
    'crm.customers': 'Customers',
    'crm.vouchers': 'Vouchers',
    'crm.feedback': 'Feedback',

    // Marketing
    'marketing.title': 'Marketing',
    'marketing.campaigns': 'Campaigns',
    'marketing.analytics': 'Analytics',

    // BOD
    'bod.title': 'B.O.D',
    'bod.hq_dashboard': 'HQ Dashboard',
    'bod.branch_performance': 'Performance',
    'bod.audit_logs': 'Audit Logs',
    'bod.system_config': 'System Config',
  },
  ja: {
    // Hall / Checkout
    'hall.title':              'ホール',
    'hall.dashboard':          'ダッシュボード',
    'hall.floor_plan':         'フロアマップ',
    'hall.service_requests':   'サービスリクエスト',
    'hall.checkout':           'お会計',
    'checkout.subtotal':       '小計',
    'checkout.discount_tier':  '会員割引',
    'checkout.discount_voucher':'クーポン',
    'checkout.discount_points':'ポイント利用',
    'checkout.service_charge': 'サービス料',
    'checkout.vat':            '消費税',
    'checkout.grand_total':    '合計',
    'checkout.payment_method': '支払方法',
    'checkout.points_preview': '{points} ポイント = -{amount}đ',
    'checkout.confirm':        '支払確認',
    'checkout.success':        '支払完了！',
    'checkout.receipt.print':  'レシート印刷',
    // Service Requests
    'service.call_waiter':     '店員を呼ぶ',
    'service.request_bill':    'お会計をお願い',
    'service.condiment':       '調味料をお願い',
    'service.complaint':       'フィードバック',
    'service.open':            '新規',
    'service.in_progress':     '対応中',
    'service.resolved':        '完了',
    'service.urgent':          '緊急',
    'service.sent':            'リクエスト送信済み！',
    // Reservations
    'reservation.title':       '予約',
    'reservation.create':      '新規予約',
    'reservation.date':        '日付',
    'reservation.time':        '時間',
    'reservation.guests':      '人数',
    'reservation.status.pending':  '確認待ち',
    'reservation.status.confirmed':'確認済み',
    'reservation.status.seated':   '着席',
    'reservation.status.completed':'完了',
    'reservation.status.no_show':  '来店なし',
    'reservation.confirm_table':   'テーブル確認',
    'reservation.seat_now':        'ご案内',
    'reservation.no_show':         '来店なしにする',
    // Purchasing
    'purchasing.title':          '購買',
    'purchasing.purchase_order': '発注書',
    'purchasing.po_number':      'PO番号',
    'purchasing.supplier':       '仕入先',
    'purchasing.expected_delivery':'納品予定日',
    'purchasing.receive':        '受取確認',
    'purchasing.status.draft':   '下書き',
    'purchasing.status.submitted':'提出済み',
    'purchasing.status.received':'受取済み',
    'purchasing.status.partial': '一部受取',
    // Accounting
    'accounting.title':          '経理',
    'accounting.revenue':        '収益',
    'accounting.expense':        '費用',
    'accounting.profit_loss':    '損益',
    'accounting.tax':            '税務',
    'accounting.gross_revenue':  '総収益',
    'accounting.net_revenue':    '純収益',
    'accounting.gross_profit':   '粗利',
    'accounting.profit_margin':  '利益率',
    'accounting.vat_collected':  '消費税預り',
    'accounting.generate_tax':   '税務書類作成',
    'accounting.void_invoice':   '請求書無効',
    // Campaigns
    'campaign.title':            'キャンペーン',
    'campaign.create':           'キャンペーン作成',
    'campaign.type.seasonal':    '季節',
    'campaign.type.loyalty':     'ロイヤルティ',
    'campaign.type.flash':       'フラッシュセール',
    'campaign.status.draft':     '下書き',
    'campaign.status.pending':   '承認待ち',
    'campaign.status.approved':  '承認済み',
    'campaign.status.active':    'アクティブ',
    'campaign.submit_approval':  '承認申請',
    // BOD
    'bod.title':               '役員会',
    'bod.dashboard':           'ダッシュボード',
    'bod.approvals':           '承認',
    'bod.kpi':                 'KPI目標',
    'bod.budget':              '予算',
    'bod.revenue_target':      '収益目標',
    'bod.breakeven':           '損益分岐点',
    'bod.vs_target':           '実績 / 目標',
    'bod.approve':             '承認',
    'bod.reject':              '拒否',
    // Feedback
    'feedback.title':          'フィードバック',
    'feedback.overall':        '全体評価',
    'feedback.food':           '料理',
    'feedback.service':        'サービス',
    'feedback.ambiance':       '雰囲気',
    'feedback.comment':        'コメント',
    'feedback.submit':         '送信',
    'feedback.thank_you':      'ありがとうございます！',
    'feedback.respond':        '返信',
    'inventory.title':                '在庫管理',
    'inventory.lowStock':             '在庫不足',
    'inventory.expiryWarning':        '期限切れ間近',
    'inventory.addStock':             '在庫追加',
    'inventory.adjust':               '在庫調整',
    'inventory.unit':                 '単位',
    'inventory.quantity':             '数量',
    'inventory.threshold':            '警告閾値',
    'inventory.search':               '食材を検索...',
    'req.title':                      '請求書',
    'req.create':                     '請求書作成',
    'req.status.pending':             '承認待ち',
    'req.status.approved':            '承認済み',
    'req.status.rejected':            '却下',
    'req.status.processing':          '処理中',
    'req.status.completed':           '完了',
    'req.status.cancelled':           'キャンセル',
    'req.type.outbound':              '出庫',
    'req.type.inbound':               '入庫',
    'req.type.return':                '返品',
    'req.approve':                    '承認',
    'req.reject':                     '却下',
    'req.confirm_delivery':           '納品確認',
    'req.rejection_reason':           '却下理由',
    'req.needed_by':                  '必要な日付',
    'shift.start':                    'シフト開始',
    'shift.close':                    'シフト終了',
    'shift.handover':                 '引き継ぎ',
    'shift.type.morning':             '朝番',
    'shift.type.afternoon':           '昼番',
    'shift.type.evening':             '夜番',
    'shift.count_ingredients':        '在庫確認',
    'shift.discrepancy':              '差異',
    'tablet.touch_to_start':          'タッチしてください',
    'tablet.select_language':         '言語を選択',
    'branch.title':                   '店舗管理',
    'branch.add':                     '店舗を追加',
    'branch.edit':                    '編集',
    'branch.deactivate':              '無効化',
    'branch.capacity':                '収容人数',
    'branch.manager':                 '店長',
    'integration.title':              '外部連携',
    'integration.payment':            '決済',
    'integration.delivery':           '配達',
    'integration.test_connection':    '接続テスト',
    'integration.api_key':            'APIキー',
    'integration.webhook':            'Webhook URL',
    'common.save':                    '保存',
    'common.cancel':                  'キャンセル',
    'common.confirm':                 '確認',
    'common.loading':                 '読み込み中...',
    'common.error':                   'エラー',
    'common.success':                 '成功',
    'common.search':                  '検索',
    'common.no_data':                 'データなし',
  
    // Reception Keys
    'reception.checkout.title': 'タイトル',
    'reception.checkout.no_open_invoice': 'No open invoice',
    'reception.checkout.script_title': 'タイトル',
    'reception.checkout.script_content': 'Script content',
    'reception.checkout.step1_title': 'タイトル',
    'reception.checkout.phone_placeholder': 'Phone placeholder',
    'reception.checkout.search': 'Search',
    'reception.checkout.member': 'Member',
    'reception.checkout.customer_not_found': 'Customer not found',
    'reception.checkout.step2_title': 'タイトル',
    'reception.checkout.revenue_type': 'Revenue type',
    'reception.checkout.dinner': 'Dinner',
    'reception.checkout.lunch': 'Lunch',
    'reception.checkout.wine': 'Wine',
    'reception.checkout.delivery': 'Delivery',
    'reception.checkout.other': 'Other',
    'reception.checkout.enter_voucher': 'Enter voucher',
    'reception.checkout.voucher_placeholder': 'Voucher placeholder',
    'reception.checkout.apply': 'Apply',
    'reception.checkout.voucher_applied_notice': 'Voucher applied notice',
    'reception.checkout.step3_title': 'タイトル',
    'reception.checkout.received_amount': 'Received amount',
    'reception.checkout.change_amount': 'Change amount',
    'reception.checkout.insufficient_amount': 'Insufficient amount',
    'reception.checkout.reference_code': 'Reference code',
    'reception.checkout.card_last_4': 'Card last 4',
    'reception.checkout.transaction_code': 'Transaction code',
    'reception.checkout.simulation_notice': 'Simulation notice',
    'reception.checkout.voucher_payment_notice': 'Voucher payment notice',
    'reception.checkout.invoice_summary': 'Invoice summary',
    'reception.checkout.guest_count': 'Guest count',
    'reception.checkout.loading_invoice': 'Loading invoice',
    'reception.checkout.no_items': 'アイテムなし',
    'reception.checkout.subtotal': '合計',
    'reception.checkout.vat': 'Vat',
    'reception.checkout.voucher': 'Voucher',
    'reception.checkout.will_apply': 'Will apply',
    'reception.checkout.total_amount': '合計',
    'reception.checkout.processing': 'Processing',
    'reception.checkout.print_invoice_close_table': 'テーブル',
    'reception.checkout.enter_amount_warning': 'Enter amount warning',
    'reception.checkout.cash': 'Cash',
    'reception.checkout.card': 'Card',
    'reception.checkout.transfer': 'Transfer',
    'reception.checkout.voucher_label': 'Voucher label',
    'reception.checkout.loading': 'Loading',
    'reception.checkout.no_open_order': '注文',
    'reception.checkout.processing_payment': 'Processing payment',
    'reception.checkout.ready_to_pay': 'Ready to pay',
    'reception.checkout.voucher_will_be_checked': 'Voucher will be checked',
    'reception.checkout.voucher_check_msg': 'Voucher check msg',
    'reception.checkout.no_branch_error': 'No branch error',
    'reception.checkout.payment_condition_not_met': 'Payment condition not met',
    'reception.checkout.payment_success': 'Payment success',
    'reception.checkout.invoice_label': 'Invoice label',
    'reception.checkout.total_label': '合計',
    'reception.checkout.change_label': 'Change label',
    'reception.checkout.error': 'Error',
    'reception.checkout.payment_failed': 'Payment failed',
    'reception.close_shift.title': 'タイトル',
    'reception.close_shift.subtitle': 'タイトル',
    'reception.close_shift.export_csv': 'Export csv',
    'reception.close_shift.closing_shift': 'Closing shift',
    'reception.close_shift.confirm_close_shift': 'シフト終了',
    'reception.close_shift.active_shift': 'Active shift',
    'reception.close_shift.opened_at': 'Opened at',
    'reception.close_shift.opening_cash': 'Opening cash',
    'reception.close_shift.no_active_shift': 'No active shift',
    'reception.close_shift.revenue_by_type': 'Revenue by type',
    'reception.close_shift.loading': 'Loading',
    'reception.close_shift.dinner': 'Dinner',
    'reception.close_shift.bill_count': 'Bill count',
    'reception.close_shift.lunch': 'Lunch',
    'reception.close_shift.wine': 'Wine',
    'reception.close_shift.delivery': 'Delivery',
    'reception.close_shift.order_count': '注文',
    'reception.close_shift.total_daily_revenue': '合計',
    'reception.close_shift.cash_reconciliation': 'Cash reconciliation',
    'reception.close_shift.initial_cash': 'Initial cash',
    'reception.close_shift.cash_revenue': 'Cash revenue',
    'reception.close_shift.expected_cash': 'Expected cash',
    'reception.close_shift.non_cash_revenue': 'Non cash revenue',
    'reception.close_shift.payment_history': 'Payment history',
    'reception.close_shift.turn_count': 'Turn count',
    'reception.close_shift.time': 'Time',
    'reception.close_shift.payment_method': 'Payment method',
    'reception.close_shift.revenue_category': 'Revenue category',
    'reception.close_shift.amount': 'Amount',
    'reception.close_shift.received_from_guest': 'Received from guest',
    'reception.close_shift.change': 'Change',
    'reception.close_shift.no_data': 'No data',
    'reception.close_shift.cash_label': 'Cash label',
    'reception.close_shift.card_label': 'Card label',
    'reception.close_shift.transfer_label': 'Transfer label',
    'reception.close_shift.voucher_label': 'Voucher label',
    'reception.close_shift.other_label': 'Other label',
    'reception.close_shift.dinner_label': 'Dinner label',
    'reception.close_shift.lunch_label': 'Lunch label',
    'reception.close_shift.wine_label': 'Wine label',
    'reception.close_shift.delivery_label': 'Delivery label',
    'reception.close_shift.notification': 'Notification',
    'reception.close_shift.no_active_shift_alert': 'No active shift alert',
    'reception.close_shift.close_shift_title': 'タイトル',
    'reception.close_shift.expected_cash_sys': 'Expected cash sys',
    'reception.close_shift.actual_cash_placeholder': 'Actual cash placeholder',
    'reception.close_shift.handover_notes': 'Handover notes',
    'reception.close_shift.confirm_close_btn': 'Confirm close btn',
    'reception.close_shift.cancel_btn': 'Cancel btn',
    'reception.close_shift.enter_actual_cash_warning': 'Enter actual cash warning',
    'reception.close_shift.close_shift_success': 'シフト終了',
    'reception.close_shift.cash_diff': 'Cash diff',
    'reception.close_shift.expected_label': 'Expected label',
    'reception.close_shift.actual_label': 'Actual label',
    'reception.close_shift.error_title': 'タイトル',
    'reception.close_shift.close_shift_error': 'シフト終了',
    'reception.close_shift.no_shift_export_alert': 'No shift export alert',
    'reception.close_shift.success_title': 'タイトル',
    'reception.close_shift.csv_downloaded': 'Csv downloaded',
    'reception.close_shift.export_csv_error': 'Export csv error',
    'reception_order.quyen_truy_cap_bi_tu_choi': 'Quyen truy cap bi tu choi',
    'reception_order.vui_long_chon_mot_ban_an_dang': 'Vui long chon mot ban an dang',
    'reception_order.di_toi_so_do_ban': 'Di toi so do ban',
    'reception_order.quay_lai_aria': 'Quay lai aria',
    'reception_order.quay_lai': 'Quay lai',
    'reception_order.nguu_cat_pos': 'Nguu cat pos',
    'reception_order.hoa_don': 'Hoa don',
    'reception_order.khach_hang': 'Khach hang',
    'reception_order.gio_mo': 'Gio mo',
    'reception_order.thoi_gian': 'Thoi gian',
    'reception_order.tim_kiem': 'Tim kiem',
    'reception_order.xem_hoa_don_tam_tinh': 'Xem hoa don tam tinh',
    'reception_order.cau_hinh_goi_ngon_ngu': 'Cau hinh goi ngon ngu',
    'reception_order.thoi_gian_do_uong_premium_da_k': 'Thoi gian do uong premium da k',
    'reception_order.mo_khoa_pin': 'Mo khoa pin',
    'reception_order.ban_phuc_vu': 'Ban phuc vu',
    'reception_order.ban_text': 'Ban text',
    'reception_order.xoa_het': 'Xoa het',
    'reception_order.ten_mon': 'Ten mon',
    'reception_order.don_gia': 'Don gia',
    'reception_order.thanh_tien': 'Thanh tien',
    'reception_order.hoa_don_trong': 'Hoa don trong',
    'reception_order.vui_long_chon_mon_an_tu_thuc_d': 'Vui long chon mon an tu thuc d',
    'reception_order.dvt': 'Dvt',
    'reception_order.xoa_mon_khoi_gio': 'Xoa mon khoi gio',
    'reception_order.trong_goi': 'Trong goi',
    'reception_order.0d': '0d',
    'reception_order.tam_tinh_mon_goi': 'Tam tinh mon goi',
    'reception_order.phi_dich_vu_5': 'Phi dich vu 5',
    'reception_order.thue_gtgt_vat_10': 'Thue gtgt vat 10',
    'reception_order.tong_so_luong_mon': 'Tong so luong mon',
    'reception_order.mon': 'Mon',
    'reception_order.tong_thanh_toan_label': 'Tong thanh toan label',
    'reception_order.tam_luu': 'Tam luu',
    'reception_order.gui_bep': 'Gui bep',
    'reception_order.in_thanh_toan_bill': 'In thanh toan bill',
    'reception_order.yeu_thich_star': 'Yeu thich star',
    'reception_order.ban_chay_fire': 'Ban chay fire',
    'reception_order.moi_goi_clock': 'Moi goi clock',
    'reception_order.tat_ca_mon': 'Tat ca mon',
    'reception_order.con_mon': 'Con mon',
    'reception_order.het_mon': 'Het mon',
    'reception_order.khong_sap_xep': 'Khong sap xep',
    'reception_order.gia_thap_cao': 'Gia thap cao',
    'reception_order.gia_cao_thap': 'Gia cao thap',
    'reception_order.chi_mon_trong_goi': 'Chi mon trong goi',
    'reception_order.dang_loc_danh_muc_san_pham': 'Dang loc danh muc san pham',
    'reception_order.khong_tim_thay_mon_an_nao_khop': 'Khong tim thay mon an nao khop',
    'reception_order.thuc_don_hien_tai_khong_co_mon': 'Thuc don hien tai khong co mon',
    'reception_order.trong_goi_upper': 'Trong goi upper',
    'reception_order.chi_tiet_title': 'タイトル',
    'reception_order.het_upper': 'Het upper',
    'reception_order.tat_ca': 'Tat ca',
    'reception_order.chi_tiet_mon_an': 'Chi tiet mon an',
    'reception_order.het_hang': 'Het hang',
    'reception_order.con_hang_phuc_vu_text': 'Con hang phuc vu text',
    'reception_order.het_hang_text': 'Het hang text',
    'reception_order.ma_mon': 'Ma mon',
    'reception_order.don_vi_tinh': 'Don vi tinh',
    'reception_order.so_luong': 'So luong',
    'reception_order.don_gia_vnd': 'Don gia vnd',
    'reception_order.0d_trong_goi': '0d trong goi',
    'reception_order.bao_gom_vat': 'Bao gom vat',
    'reception_order.bao_gom_ppv': 'Bao gom ppv',
    'reception_order.loai_tien_te': 'Loai tien te',
    'reception_order.vnd_viet_nam_dong': 'Vnd viet nam dong',
    'reception_order.usd_do_la_my': 'Usd do la my',
    'reception_order.ty_gia': 'Ty gia',
    'reception_order.ghi_chu': 'Ghi chu',
    'reception_order.them_ghi_chu_dac_thu_it_da_nhi': 'Them ghi chu dac thu it da nhi',
    'reception_order.phan_nhom_thuc_don_he_thong': 'Phan nhom thuc don he thong',
    'reception_order.nhom_san_pham': 'Nhom san pham',
    'reception_order.goi_buffet': 'Goi buffet',
    'reception_order.goi_set_menu': 'Goi set menu',
    'reception_order.goi_do_uong': 'Goi do uong',
    'reception_order.ma': 'Ma',
    'reception_order.don_vi': 'Don vi',
    'reception_order.vat_percent': 'Vat percent',
    'reception_order.ppv_percent': 'Ppv percent',
    'reception_order.tien_te': 'Tien te',
    'reception_order.ghi_chu_chung': 'Ghi chu chung',
    'reception_order.them_ghi_chu_cho_ca_mon_an': 'Them ghi chu cho ca mon an',
    'reception_order.toi_thieu': 'Toi thieu',
    'reception_order.toi_da': 'Toi da',
    'reception_order.them_ghi_chu_rieng_cho_lua_cho': 'Them ghi chu rieng cho lua cho',
    'reception_order.vui_long_chon_them_it_nhat': 'Vui long chon them it nhat',
    'reception_order.lua_chon_nua': 'Lua chon nua',
    'reception_order.da_vuot_qua_gioi_han_toi_da': 'Da vuot qua gioi han toi da',
    'reception_order.lua_chon': 'Lua chon',
    'reception_order.da_chon_du_so_luong': 'Da chon du so luong',
    'reception_order.huy_bo_esc': 'Huy bo esc',
    'reception_order.them_vao_gio_hang': 'Them vao gio hang',
    'reception_order.cau_hinh_goi_course_phuc_vu': 'Cau hinh goi course phuc vu',
    'reception_order.1_chon_goi_an_phuc_vu_course_p': '1 chon goi an phuc vu course p',
    'reception_order.thoi_luong_phuc_vu_2_tieng': 'Thoi luong phuc vu 2 tieng',
    'reception_order.menu_goi_theo_bua_tiec': 'Menu goi theo bua tiec',
    'reception_order.ve': 'Ve',
    'reception_order.2_chon_nhom_do_uong_kem_theo_d': '2 chon nhom do uong kem theo d',
    'reception_order.nhom_a_soft_drink': 'Nhom a soft drink',
    'reception_order.nuoc_ngot_uong_khong_gioi_han': 'Nuoc ngot uong khong gioi han',
    'reception_order.nhom_b_premium_drink': 'Nhom b premium drink',
    'reception_order.ruou_bia_cao_cap_uong_trong_2': 'Ruou bia cao cap uong trong 2',
    'reception_order.nhom_c_premium_alt': 'Nhom c premium alt',
    'reception_order.ruou_bia_thay_the_dung_2_gio_f': 'Ruou bia thay the dung 2 gio f',
    'reception_order.nhom_d_a_la_carte': 'Nhom d a la carte',
    'reception_order.goi_do_uong_le_tinh_tien_rieng': 'Goi do uong le tinh tien rieng',
    'reception_order.3_ngon_ngu_giao_dien_hien_thi': '3 ngon ngu giao dien hien thi',
    'reception_order.tieng_viet': 'Tieng viet',
    'reception_order.huy_bo_quay_lai': 'Huy bo quay lai',
    'reception_order.pin_sua_cau_hinh': 'Pin sua cau hinh',
    'reception_order.xac_nhan_khoa_course': 'Xac nhan khoa course',
    'reception_order.ma_pin_xac_thuc_quan_ly': 'Ma pin xac thuc quan ly',
    'reception_order.nhap_ma_pin_cua_quan_ly_de_mo': 'Nhap ma pin cua quan ly de mo',
    'reception_order.khach_text': 'Khach text',
    'reception_order.gio_mo_text': 'Gio mo text',
    'reception_order.con_lai_text': 'Con lai text',
    'reception_order.tam_tinh_text': 'Tam tinh text',
    'reception_order.thue_gtgt_10_text': 'Thue gtgt 10 text',
    'reception_order.phi_phuc_vu_text': 'Phi phuc vu text',
    'reception_order.tong_cong_text': 'Tong cong text',
    'reception_order.thanh_toan_text': 'Thanh toan text',
    'reception_order.xem_tam_tinh_text': 'Xem tam tinh text',
    'reception_order.gio_hang_trong_text': 'Gio hang trong text',
    'reception_order.hay_chon_mon_tu_menu_text': 'Hay chon mon tu menu text',
    'reception_order.mon_yeu_thich_text': 'Mon yeu thich text',
    'reception_order.moi_goi_text': 'Moi goi text',
    'reception_order.ban_chay_text': 'Ban chay text',
    'reception_order.tim_mon_an_theo_ten_text': 'Tim mon an theo ten text',
    'reception_order.con_hang_text': 'Con hang text',
    'reception_order.tat_ca_text': 'Tat ca text',
    'reception_order.quay_lai_text': 'Quay lai text',
    'reception_order.luu_thay_doi_text': 'Luu thay doi text',
    'reception_order.tam_luu_text': 'Tam luu text',
    'reception_order.gui_vao_bep_text': 'Gui vao bep text',
    'reception_order.huy_thay_doi_text': 'Huy thay doi text',
    'reception_order.khoa_course_text': 'Khoa course text',
    'reception_order.khach_vang_lai_text': 'Khach vang lai text',
    'reception_order.khoa_course_thanh_cong': 'Khoa course thanh cong',
    'reception_order.nuoc_lau_di_kem': 'Nuoc lau di kem',
    'reception_order.lau_sukiyaki_ngot_thanh': 'Lau sukiyaki ngot thanh',
    'reception_order.lau_kimchi_chua_cay': 'Lau kimchi chua cay',
    'reception_order.lau_mala_tu_xuyen': 'Lau mala tu xuyen',
    'reception_order.lau_nam_thao_duoc': 'Lau nam thao duoc',
    'reception_order.lau_sua_dau_nanh': 'Lau sua dau nanh',
    'reception_order.chon_nuoc_lau_goi_buffet': 'Chon nuoc lau goi buffet',
    'reception_order.lau_sukiyaki_tieu_chuan': 'Lau sukiyaki tieu chuan',
    'reception_order.lau_kimchi_han_quoc': 'Lau kimchi han quoc',
    'reception_order.lau_nam_thao_moc': 'Lau nam thao moc',
    'reception_order.chon_mon_tang_kem': 'Chon mon tang kem',
    'reception_order.than_vai_bo_uc': 'Than vai bo uc',
    'reception_order.lon_bia_sapporo': 'Lon bia sapporo',
    'reception_order.dia_salad_bap_cai': 'Dia salad bap cai',
    'reception_order.mon_an_kem_chon_1': 'Mon an kem chon 1',
    'reception_order.canh_rong_bien': 'Canh rong bien',
    'reception_order.dia_kimchi_cai_thao': 'Dia kimchi cai thao',
    'reception_order.ly_hong_tra': 'Ly hong tra',
    'reception_order.khu_vuc': 'Khu vuc',
    'reception_order.trong_text': 'Trong text',
    'reception_order.da_dat_text': 'Da dat text',
    'reception_order.khach_den_text': 'Khach den text',
    'reception_order.dang_an_text': 'Dang an text',
    'reception_order.thoi_gian_an_con_lai_30_phut': 'Thoi gian an con lai 30 phut',
    'reception_order.thoi_gian_sap_het_10_phut': 'Thoi gian sap het 10 phut',
    'reception_order.phien_an_2_gio_da_ket_thuc': 'Phien an 2 gio da ket thuc',
    'reception_order.buffet_lau_upper': 'Buffet lau upper',
    'reception_order.khong_ap_dung': 'Khong ap dung',
    'reception_order.mon_tam_thoi_het_hang': 'Mon tam thoi het hang',
    'reception_order.da_dat_gioi_han_toi_da_10_phan': 'Da dat gioi han toi da 10 phan',
    'reception_order.da_them_vao_hoa_don': 'Da them vao hoa don',
    'reception_order.moi_luot_goi_toi_da_10_phan': 'Moi luot goi toi da 10 phan',
    'reception_order.xoa_mon_nay_khoi_don': 'Xoa mon nay khoi don',
    'reception_order.da_xoa_mon_khoi_gio': 'Da xoa mon khoi gio',
    'reception_order.ban_co_chac_muon_xoa_toan_bo_mon': 'Ban co chac muon xoa toan bo mon',
    'reception_order.da_xoa_toan_bo_mon': 'Da xoa toan bo mon',
    'reception_order.da_chon_gioi_han_toi_da': 'Da chon gioi han toi da',
    'reception_order.so_luong_goi_mon_vuot_qua': 'So luong goi mon vuot qua',
    'reception_order.da_them_mon_phan': 'Da them mon phan',
    'reception_order.vui_long_hoan_thanh_lua_chon': 'Vui long hoan thanh lua chon',
    'reception_order.da_them_mon_co_tuy_chon': 'Da them mon co tuy chon',
    'reception_order.da_bo_yeu_thich_mon': 'Da bo yeu thich mon',
    'reception_order.da_luu_mon_vao_yeu_thich': 'Da luu mon vao yeu thich',
    'reception_order.cau_hinh_da_bi_khoa': 'Cau hinh da bi khoa',
    'reception_order.nhom_thuc_uong_da_bi_khoa': 'Nhom thuc uong da bi khoa',
    'reception_order.vui_long_chon_goi_buffet': 'Vui long chon goi buffet',
    'reception_order.guestWalkIn': 'GuestWalkIn',
    'reception_order.courseLockedSuccess': 'CourseLockedSuccess',
    'reception_order.mo_khoa_cau_hinh_thanh_cong': 'Mo khoa cau hinh thanh cong',
    'reception_order.ma_pin_sai': 'Ma pin sai',
    'reception_order.hoa_don_tam_tinh_alert': 'Hoa don tam tinh alert',
    'reception_order.da_gui_lenh_in_tam_tinh': 'Da gui lenh in tam tinh',
    'reception_order.xac_nhan_thanh_toan': 'Xac nhan thanh toan',
    'reception_order.dong_ban_tam_tinh': 'Dong ban tam tinh',
    'reception_order.tien_hanh_thanh_toan': 'Tien hanh thanh toan',
    'reception_order.huy_text': 'Huy text',
    'reception_order.tai_khoan_chua_gan_chi_nhanh': 'Tai khoan chua gan chi nhanh',
    'reception_order.khong_tim_thay_ban': 'Khong tim thay ban',
    'reception_order.loi_text': 'Loi text',
    'reception_order.huy_bo_toan_bo_mon_an': 'Huy bo toan bo mon an',
    'reception_order.da_lam_trong_gio_hang': 'Da lam trong gio hang',
    'reception_order.da_luu_tam_don_hang': 'Da luu tam don hang',
    'reception_order.chua_co_mon_an_de_gui_bep': 'Chua co mon an de gui bep',
    'reception_order.chua_chon_ban': 'Chua chon ban',
    'reception_order.da_gui_mon_den_kds': 'Da gui mon den kds',
    'reception_order.bo_qua_mon_chua_map_db': 'Bo qua mon chua map db',
    'reception_order.gui_bep_that_bai': 'Gui bep that bai',
    'reception_order.mot_phut': 'Mot phut',
    'reception_order.da_luu_cau_hinh_mon_an': 'Da luu cau hinh mon an',
    'reception_order.buffet_lau': 'Buffet lau',
    'reception_order.da_cau_hinh_goi': 'Da cau hinh goi',
  
    // Dashboard Keys
    'reception.dashboard.loading_data': 'Loading data',
    'reception.dashboard.shift_overview': '概要',
    'reception.dashboard.today': '今日',
    'reception.dashboard.tables_in_use': 'テーブル',
    'reception.dashboard.pending_checkout': 'チェックアウト',
    'reception.dashboard.today_reservations': '今日',
    'reception.dashboard.active_shift': 'シフト',
    'reception.dashboard.opened_at': 'Opened at',
    'reception.dashboard.opening_cash': 'Opening cash',
    'reception.dashboard.needs_action_now': 'アクション',
    'reception.dashboard.checkout_request': 'チェックアウト',
    'reception.dashboard.guests': 'ゲスト',
    'reception.dashboard.proceed_to_checkout': 'チェックアウト',
    'reception.dashboard.no_checkout_requests': 'チェックアウト',
    'reception.dashboard.tables_serving_list': 'テーブル',
    'reception.dashboard.table_code': 'テーブル',
    'reception.dashboard.guest_col': 'ゲスト',
    'reception.dashboard.time_col': '時間',
    'reception.dashboard.status_col': 'ステータス',
    'reception.dashboard.invoice_col': '請求書',
    'reception.dashboard.dining': 'Dining',
    'reception.dashboard.checkout_action': 'チェックアウト',
    'reception.dashboard.no_tables_serving': 'テーブル',
    'reception.dashboard.booking_code': 'コード',
    'reception.dashboard.hour': 'Hour',
    'reception.dashboard.num_guests': 'ゲスト',
    'reception.dashboard.no_bookings_today': '今日',
    'reception.dashboard.no_branch_error': 'No branch error',

    // Purchasing
    'purchasing.title': '購買',
    'purchasing.po_list': '発注書',
    'purchasing.create_po': '発注書作成',
    'purchasing.requisitions': '購買要求',
    'purchasing.suppliers': 'サプライヤー',

    // Accounting
    'accounting.title': '会計',
    'accounting.invoices': '請求書',
    'accounting.tax_export': '税金輸出',
    'accounting.inventory_valuation': '在庫評価',

    // CRM
    'crm.title': '顧客管理',
    'crm.customers': '顧客',
    'crm.vouchers': 'バウチャー',
    'crm.feedback': 'フィードバック',

    // Marketing
    'marketing.title': 'マーケティング',
    'marketing.campaigns': 'キャンペーン',
    'marketing.analytics': '分析',

    // BOD
    'bod.title': '取締役会',
    'bod.hq_dashboard': 'HQダッシュボード',
    'bod.branch_performance': '店舗パフォーマンス',
    'bod.audit_logs': '監査ログ',
    'bod.system_config': 'システム設定',
  }
};

export const useLanguageStore = defineStore('language', {
  state: () => ({
    lang: (localStorage.getItem('app_lang') ?? 'vi') as Lang,
  }),
  getters: {
    t: (state) => (key: string, defaultOrParams?: string | Record<string, string>, params?: Record<string, string>): string => {
      // Import the global i18n instance
      // Note: We use dynamic import or get it from global if possible to avoid circular dependency
      // but here we can just use it if we import it at the top.
      const hasI18nKey = i18n.global.te(key, state.lang);
      if (hasI18nKey) {
         if (typeof defaultOrParams === 'object') {
             return i18n.global.t(key, defaultOrParams) as string;
         } else if (params) {
             return i18n.global.t(key, params) as string;
         } else {
             return i18n.global.t(key) as string;
         }
      }

      // Fallback 1: Use internal dict
      let val = dict[state.lang]?.[key] ?? dict['vi']?.[key];
      
      // Fallback 2: Use provided default string if available
      if (!val && typeof defaultOrParams === 'string') {
          val = defaultOrParams;
      }
      
      // Fallback 3: Return key
      if (!val) {
          val = key;
      }

      const actualParams = typeof defaultOrParams === 'object' ? defaultOrParams : params;
      if (actualParams) {
        for (const [k, v] of Object.entries(actualParams)) {
          val = val.replace(`{${k}}`, v as string);
        }
      }
      return val;
    },
    langOptions: () => [
      { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
      { code: 'en', label: 'English',    flag: '🇬🇧' },
      { code: 'ja', label: '日本語',      flag: '🇯🇵' },
    ] as const,
  },
  actions: {
    setLanguage(lang: Lang) {
      this.lang = lang;
      localStorage.setItem('app_lang', lang);
      setI18nLocale(lang);
    }
  }
});
