import { defineStore } from 'pinia';
import { setI18nLocale, i18n } from '@/locales';

export type Lang = 'vi' | 'en' | 'ja';

const dict: Record<Lang, Record<string, string>> = {
  vi: {
    // Hall / Checkout
    'hall.title':              'Tiền Sảnh',
    'hall.dashboard':          'Bảng Điều Khiển',
    'hall.floor_plan':         'Sơ Đồ Bàn',
    'hall.service_requests':   'Yêu Cầu Phục Vụ',
    'hall.checkout':           'Thanh Toán',
    'checkout.subtotal':       'Tạm tính',
    'checkout.discount_tier':  'Ưu đãi hội viên',
    'checkout.discount_voucher':'Mã giảm giá',
    'checkout.discount_points':'Đổi điểm',
    'checkout.service_charge': 'Phụ thu dịch vụ',
    'checkout.vat':            'Thuế VAT',
    'checkout.grand_total':    'Tổng cộng',
    'checkout.payment_method': 'Phương thức thanh toán',
    'checkout.points_preview': '{points} điểm = -{amount}đ',
    'checkout.confirm':        'Xác nhận thanh toán',
    'checkout.success':        'Thanh toán thành công!',
    'checkout.receipt.print':  'In hóa đơn',
    // Service Requests
    'service.call_waiter':     'Gọi nhân viên',
    'service.request_bill':    'Yêu cầu thanh toán',
    'service.condiment':       'Yêu cầu gia vị',
    'service.complaint':       'Phản hồi',
    'service.open':            'Mới',
    'service.in_progress':     'Đang xử lý',
    'service.resolved':        'Đã xử lý',
    'service.urgent':          'Khẩn cấp',
    'service.sent':            'Yêu cầu đã được gửi!',
    // Reservations
    'reservation.title':       'Đặt Bàn',
    'reservation.create':      'Đặt bàn mới',
    'reservation.date':        'Ngày',
    'reservation.time':        'Giờ',
    'reservation.guests':      'Số khách',
    'reservation.status.pending':  'Chờ xác nhận',
    'reservation.status.confirmed':'Đã xác nhận',
    'reservation.status.seated':   'Đã vào bàn',
    'reservation.status.completed':'Hoàn thành',
    'reservation.status.no_show':  'Không đến',
    'reservation.confirm_table':   'Xác nhận bàn',
    'reservation.seat_now':        'Cho khách vào bàn',
    'reservation.no_show':         'Đánh dấu không đến',
    // Purchasing
    'purchasing.title':          'Mua Hàng',
    'purchasing.purchase_order': 'Đơn Đặt Hàng',
    'purchasing.po_number':      'Số PO',
    'purchasing.supplier':       'Nhà cung cấp',
    'purchasing.expected_delivery':'Ngày giao dự kiến',
    'purchasing.receive':        'Xác nhận nhận hàng',
    'purchasing.status.draft':   'Bản nháp',
    'purchasing.status.submitted':'Đã gửi',
    'purchasing.status.received':'Đã nhận',
    'purchasing.status.partial': 'Nhận một phần',
    // Accounting
    'accounting.title':          'Kế Toán',
    'accounting.revenue':        'Doanh Thu',
    'accounting.expense':        'Chi Phí',
    'accounting.profit_loss':    'Lợi Nhuận & Lỗ',
    'accounting.tax':            'Thuế',
    'accounting.gross_revenue':  'Doanh thu gộp',
    'accounting.net_revenue':    'Doanh thu thuần',
    'accounting.gross_profit':   'Lợi nhuận gộp',
    'accounting.profit_margin':  'Biên lợi nhuận',
    'accounting.vat_collected':  'VAT thu được',
    'accounting.generate_tax':   'Lập tờ khai thuế',
    'accounting.void_invoice':   'Hủy hóa đơn',
    // Campaigns
    'campaign.title':            'Chiến Dịch',
    'campaign.create':           'Tạo chiến dịch',
    'campaign.type.seasonal':    'Theo mùa',
    'campaign.type.loyalty':     'Khách thân thiết',
    'campaign.type.flash':       'Flash Sale',
    'campaign.status.draft':     'Bản nháp',
    'campaign.status.pending':   'Chờ phê duyệt',
    'campaign.status.approved':  'Đã phê duyệt',
    'campaign.status.active':    'Đang chạy',
    'campaign.submit_approval':  'Gửi phê duyệt',
    // BOD
    'bod.title':               'Ban Giám Đốc',
    'bod.dashboard':           'Tổng Quan',
    'bod.approvals':           'Phê Duyệt',
    'bod.kpi':                 'Chỉ Tiêu KPI',
    'bod.budget':              'Ngân Sách',
    'bod.revenue_target':      'Mục tiêu doanh thu',
    'bod.breakeven':           'Điểm hòa vốn',
    'bod.vs_target':           'Thực tế / Mục tiêu',
    'bod.approve':             'Phê duyệt',
    'bod.reject':              'Từ chối',
    // Feedback
    'feedback.title':          'Đánh Giá',
    'feedback.overall':        'Đánh giá tổng thể',
    'feedback.food':           'Chất lượng món ăn',
    'feedback.service':        'Chất lượng phục vụ',
    'feedback.ambiance':       'Không gian',
    'feedback.comment':        'Nhận xét',
    'feedback.submit':         'Gửi đánh giá',
    'feedback.thank_you':      'Cảm ơn bạn đã đánh giá!',
    'feedback.respond':        'Phản hồi',
    // Inventory
    'inventory.title':                'Quản Lý Kho',
    'inventory.lowStock':             'Tồn kho thấp',
    'inventory.expiryWarning':        'Sắp hết hạn',
    'inventory.addStock':             'Nhập kho',
    'inventory.adjust':               'Điều chỉnh',
    'inventory.unit':                 'ĐVT',
    'inventory.quantity':             'Số lượng',
    'inventory.threshold':            'Ngưỡng cảnh báo',
    'inventory.search':               'Tìm nguyên liệu...',
    // Requisition
    'req.title':                      'Phiếu Yêu Cầu',
    'req.create':                     'Tạo phiếu',
    'req.status.pending':             'Chờ duyệt',
    'req.status.approved':            'Đã duyệt',
    'req.status.rejected':            'Từ chối',
    'req.status.processing':          'Đang xử lý',
    'req.status.completed':           'Hoàn thành',
    'req.status.cancelled':           'Đã hủy',
    'req.type.outbound':              'Xuất kho',
    'req.type.inbound':               'Nhập kho',
    'req.type.return':                'Trả hàng',
    'req.approve':                    'Duyệt',
    'req.reject':                     'Từ chối',
    'req.confirm_delivery':           'Xác nhận nhận hàng',
    'req.rejection_reason':           'Lý do từ chối',
    'req.needed_by':                  'Cần trước ngày',
    // Shift
    'shift.start':                    'Bắt đầu ca',
    'shift.close':                    'Đóng ca',
    'shift.handover':                 'Bàn giao ca',
    'shift.type.morning':             'Ca Sáng',
    'shift.type.afternoon':           'Ca Chiều',
    'shift.type.evening':             'Ca Tối',
    'shift.count_ingredients':        'Kiểm kê nguyên liệu',
    'shift.discrepancy':              'Chênh lệch',
    // Tablet
    'tablet.touch_to_start':          'Chạm để bắt đầu',
    'tablet.select_language':         'Chọn ngôn ngữ',
    // Branch
    'branch.title':                   'Chi Nhánh',
    'branch.add':                     'Thêm chi nhánh',
    'branch.edit':                    'Chỉnh sửa',
    'branch.deactivate':              'Vô hiệu hóa',
    'branch.capacity':                'Sức chứa',
    'branch.manager':                 'Quản lý',
    // Integrations
    'integration.title':              'Tích hợp',
    'integration.payment':            'Thanh toán',
    'integration.delivery':           'Giao hàng',
    'integration.test_connection':    'Kiểm tra kết nối',
    'integration.api_key':            'API Key',
    'integration.webhook':            'Webhook URL',
    // Common
    'common.save':                    'Lưu',
    'common.cancel':                  'Hủy',
    'common.confirm':                 'Xác nhận',
    'common.loading':                 'Đang tải...',
    'common.error':                   'Lỗi',
    'common.success':                 'Thành công',
    'common.search':                  'Tìm kiếm',
    'common.no_data':                 'Không có dữ liệu',
  
    // Reception Keys
    'reception.restaurant': 'Nhà hàng',
    'reception.other_income': 'Thu khác',
    'reception.other_expense': 'Chi khác',
    'reception.configuration': 'Cấu hình',
    'reception.receipt': 'Phiếu',
    'reception.reports': 'Báo cáo',
    'reception.shift_details': 'Chi tiết ca',
    'reception.notifications': 'Thông báo',
    'reception.read': 'Đã đọc',
    'reception.urgent': 'Khẩn',
    'reception.tables_in_use': 'Bàn đang dùng',
    'reception.waiting_payment': 'Chờ thanh toán',
    'reception.reservations_today': 'Đặt bàn hôm nay',
    'reception.quick_actions': 'Chức năng nhanh',
    'reception.open_shift': 'Ca làm việc đang mở',
    'reception.started_at': 'Bắt đầu lúc',
    'reception.initial_cash': 'Số dư đầu ca',
    'reception.temp_amount': 'Tạm tính',
    'reception.upcoming': 'Sắp tới',
    'reception.reservation_count': 'đặt bàn',
    'reception.view_more': 'Xem thêm',
    'reception.payment_request': 'Yêu cầu thanh toán',
    'reception.new_order': 'Đơn mới từ khách',
    'reception.out_of_stock': 'Hết hàng',
    'reception.stock_notification': 'Thông báo hết hàng',
    'reception.just_now': 'Vừa xong',
    'reception.minutes_ago': 'phút trước',
    'reception.branch': 'Chi nhánh',
    'reception.system': 'Hệ thống',
    'reception.connection': 'Kết nối',
    'reception.close': 'Đóng',
    'reception.no_open_shift': 'Chưa mở ca làm việc',
    'reception.please_open_shift': 'Vui lòng mở ca làm việc để tiếp tục',
    'reception.open_shift_btn': 'Mở ca',
    'reception.other_income_short': 'Thu khác',
    'reception.other_expenses': 'Chi khác',
    'reception.current_shift_summary': 'Tóm tắt ca hiện tại',
    'reception.start_time': 'Giờ bắt đầu',
    'reception.opening_balance': 'Số dư đầu ca',
    'reception.current_revenue': 'Doanh thu hiện tại',
    'reception.processed_orders': 'Đơn đã xử lý',
    'reception.no_active_shifts': 'Không có ca nào đang hoạt động',
    'reception.serving_tables_list': 'Danh sách bàn đang phục vụ',
    'reception.guests': 'Khách',
    'reception.seated_time': 'Giờ vào bàn',
    'reception.ordered_items': 'Số lượng món',
    'reception.action_col': 'Thao tác',
    'reception.loading': 'Đang tải...',
    'reception.payment': 'Thanh toán',
    'reception.no_active_tables': 'Không có bàn nào đang hoạt động',
    'reception.reservation_code': 'Mã đặt bàn',
    'reception.customer_phone': 'Số điện thoại',
    'reception.reserved_time': 'Giờ đặt bàn',
    'reception.number_of_people': 'Số người',
    'reception.status': 'Trạng thái',
    'reception.confirm': 'Xác nhận',
    'reception.cancel': 'Hủy',
    'reception.no_action': 'Không có thao tác',
    'reception.no_reservations_today': 'Không có đặt bàn hôm nay',
    'reception.no_notifications': 'Không có thông báo',
    'reception.enter_target_name': 'Nhập tên đối tượng...',
    'reception.other': 'Khác',
    'reception.reason': 'Lý do',
    'reception.enter_reason': 'Nhập lý do...',
    'reception.auto_generated': 'Hệ thống tự động tạo',
    'reception.enter_booking_code': 'Nhập mã đặt chỗ...',
    'reception.cash': 'Tiền mặt',
    'reception.save_and_print': 'Lưu & In',
    'reception.save': 'Lưu',
    'reception.skip': 'Bỏ qua',
    'reception.username': 'Tên đăng nhập',
    'reception.enter_username': 'Nhập tên đăng nhập...',
    'reception.password': 'Mật khẩu',
    'reception.enter_password': 'Nhập mật khẩu...',
    'reception.ignore': 'Bỏ qua',
    'reception.checkout.title': 'Tiêu đề',
    'reception.checkout.no_open_invoice': 'No open invoice',
    'reception.checkout.script_title': 'Script Tiêu đề',
    'reception.checkout.script_content': 'Script content',
    'reception.checkout.step1_title': 'Step1 Tiêu đề',
    'reception.checkout.phone_placeholder': 'Số điện thoại placeholder',
    'reception.checkout.search': 'Tìm kiếm',
    'reception.checkout.member': 'Thành viên',
    'reception.checkout.customer_not_found': 'Customer not found',
    'reception.checkout.step2_title': 'Step2 Tiêu đề',
    'reception.checkout.revenue_type': 'Doanh thu type',
    'reception.checkout.dinner': 'Dinner',
    'reception.checkout.lunch': 'Lunch',
    'reception.checkout.wine': 'Wine',
    'reception.checkout.delivery': 'Delivery',
    'reception.checkout.other': 'Other',
    'reception.checkout.enter_voucher': 'Enter voucher',
    'reception.checkout.voucher_placeholder': 'Voucher placeholder',
    'reception.checkout.apply': 'Áp dụng',
    'reception.checkout.voucher_applied_notice': 'Voucher applied notice',
    'reception.checkout.step3_title': 'Step3 Tiêu đề',
    'reception.checkout.received_amount': 'Received Số tiền',
    'reception.checkout.change_amount': 'Tiền thừa Số tiền',
    'reception.checkout.insufficient_amount': 'Insufficient Số tiền',
    'reception.checkout.reference_code': 'Reference code',
    'reception.checkout.card_last_4': 'Card last 4',
    'reception.checkout.transaction_code': 'Transaction code',
    'reception.checkout.simulation_notice': 'Simulation notice',
    'reception.checkout.voucher_payment_notice': 'Voucher payment notice',
    'reception.checkout.invoice_summary': 'Invoice summary',
    'reception.checkout.guest_count': 'Khách count',
    'reception.checkout.loading_invoice': 'Đang tải invoice',
    'reception.checkout.no_items': 'Không có món',
    'reception.checkout.subtotal': 'SubTổng cộng',
    'reception.checkout.vat': 'VAT',
    'reception.checkout.voucher': 'Voucher',
    'reception.checkout.will_apply': 'Will Áp dụng',
    'reception.checkout.total_amount': 'Tổng cộng Số tiền',
    'reception.checkout.processing': 'Processing',
    'reception.checkout.print_invoice_close_table': 'Print invoice close Bàn',
    'reception.checkout.enter_amount_warning': 'Enter Số tiền warning',
    'reception.checkout.cash': 'Tiền mặt',
    'reception.checkout.card': 'Card',
    'reception.checkout.transfer': 'Transfer',
    'reception.checkout.voucher_label': 'Voucher label',
    'reception.checkout.loading': 'Đang tải',
    'reception.checkout.no_open_order': 'No open Gọi món',
    'reception.checkout.processing_payment': 'Processing payment',
    'reception.checkout.ready_to_pay': 'Ready to pay',
    'reception.checkout.voucher_will_be_checked': 'Voucher will be checked',
    'reception.checkout.voucher_check_msg': 'Voucher check msg',
    'reception.checkout.no_branch_error': 'No branch Lỗi',
    'reception.checkout.payment_condition_not_met': 'Payment condition not met',
    'reception.checkout.payment_success': 'Payment success',
    'reception.checkout.invoice_label': 'Invoice label',
    'reception.checkout.total_label': 'Tổng cộng label',
    'reception.checkout.change_label': 'Tiền thừa label',
    'reception.checkout.error': 'Lỗi',
    'reception.checkout.payment_failed': 'Payment failed',
    'reception.close_shift.title': 'Tiêu đề',
    'reception.close_shift.subtitle': 'SubTiêu đề',
    'reception.close_shift.export_csv': 'Export csv',
    'reception.close_shift.closing_shift': 'Closing shift',
    'reception.close_shift.confirm_close_shift': 'Confirm Đóng ca',
    'reception.close_shift.active_shift': 'Active shift',
    'reception.close_shift.opened_at': 'Opened at',
    'reception.close_shift.opening_cash': 'Opening Tiền mặt',
    'reception.close_shift.no_active_shift': 'No active shift',
    'reception.close_shift.revenue_by_type': 'Doanh thu by type',
    'reception.close_shift.loading': 'Đang tải',
    'reception.close_shift.dinner': 'Dinner',
    'reception.close_shift.bill_count': 'Bill count',
    'reception.close_shift.lunch': 'Lunch',
    'reception.close_shift.wine': 'Wine',
    'reception.close_shift.delivery': 'Delivery',
    'reception.close_shift.order_count': 'Gọi món count',
    'reception.close_shift.total_daily_revenue': 'Tổng cộng daily Doanh thu',
    'reception.close_shift.cash_reconciliation': 'Tiền mặt reconciliation',
    'reception.close_shift.initial_cash': 'Initial Tiền mặt',
    'reception.close_shift.cash_revenue': 'Tiền mặt Doanh thu',
    'reception.close_shift.expected_cash': 'Expected Tiền mặt',
    'reception.close_shift.non_cash_revenue': 'Non Tiền mặt Doanh thu',
    'reception.close_shift.payment_history': 'Payment Lịch sử',
    'reception.close_shift.turn_count': 'Turn count',
    'reception.close_shift.time': 'Time',
    'reception.close_shift.payment_method': 'Payment method',
    'reception.close_shift.revenue_category': 'Doanh thu category',
    'reception.close_shift.amount': 'Số tiền',
    'reception.close_shift.received_from_guest': 'Received from Khách',
    'reception.close_shift.change': 'Tiền thừa',
    'reception.close_shift.no_data': 'No data',
    'reception.close_shift.cash_label': 'Tiền mặt label',
    'reception.close_shift.card_label': 'Card label',
    'reception.close_shift.transfer_label': 'Transfer label',
    'reception.close_shift.voucher_label': 'Voucher label',
    'reception.close_shift.other_label': 'Other label',
    'reception.close_shift.dinner_label': 'Dinner label',
    'reception.close_shift.lunch_label': 'Lunch label',
    'reception.close_shift.wine_label': 'Wine label',
    'reception.close_shift.delivery_label': 'Delivery label',
    'reception.close_shift.notification': 'Notification',
    'reception.close_shift.no_active_shift_alert': 'No active shift alert',
    'reception.close_shift.close_shift_title': 'Đóng ca Tiêu đề',
    'reception.close_shift.expected_cash_sys': 'Expected Tiền mặt sys',
    'reception.close_shift.actual_cash_placeholder': 'Actual Tiền mặt placeholder',
    'reception.close_shift.handover_notes': 'Handover notes',
    'reception.close_shift.confirm_close_btn': 'Confirm close btn',
    'reception.close_shift.cancel_btn': 'Cancel btn',
    'reception.close_shift.enter_actual_cash_warning': 'Enter actual Tiền mặt warning',
    'reception.close_shift.close_shift_success': 'Đóng ca success',
    'reception.close_shift.cash_diff': 'Tiền mặt diff',
    'reception.close_shift.expected_label': 'Expected label',
    'reception.close_shift.actual_label': 'Actual label',
    'reception.close_shift.error_title': 'Lỗi Tiêu đề',
    'reception.close_shift.close_shift_error': 'Đóng ca Lỗi',
    'reception.close_shift.no_shift_export_alert': 'No shift export alert',
    'reception.close_shift.success_title': 'Success Tiêu đề',
    'reception.close_shift.csv_downloaded': 'Csv downloaded',
    'reception.close_shift.export_csv_error': 'Export csv Lỗi',
    'reception_order.quyen_truy_cap_bi_tu_choi': 'Quyen truy cap bi tu choi',
    'reception_order.vui_long_chon_mot_ban_an_dang': 'Vui long chon mot ban an dang',
    'reception_order.di_toi_so_do_ban': 'Di toi so do ban',
    'reception_order.quay_lai_aria': 'Quay lai aria',
    'reception_order.quay_lai': 'Quay lai',
    'reception_order.nguu_cat_pos': 'Nguu cat pos',
    'reception_order.hoa_don': 'Hoa don',
    'reception_order.khach_hang': 'Khach hang',
    'reception_order.gio_mo': 'Gio mo',
    'reception_order.thoi_gian': 'Thoi gian',
    'reception_order.tim_kiem': 'Tim kiem',
    'reception_order.xem_hoa_don_tam_tinh': 'Xem hoa don tam tinh',
    'reception_order.cau_hinh_goi_ngon_ngu': 'Cau hinh goi ngon ngu',
    'reception_order.thoi_gian_do_uong_premium_da_k': 'Thoi gian do uong premium da k',
    'reception_order.mo_khoa_pin': 'Mo khoa pin',
    'reception_order.ban_phuc_vu': 'Ban phuc vu',
    'reception_order.ban_text': 'Ban text',
    'reception_order.xoa_het': 'Xoa het',
    'reception_order.ten_mon': 'Ten mon',
    'reception_order.don_gia': 'Don gia',
    'reception_order.thanh_tien': 'Thanh tien',
    'reception_order.hoa_don_trong': 'Hoa don trong',
    'reception_order.vui_long_chon_mon_an_tu_thuc_d': 'Vui long chon mon an tu thuc d',
    'reception_order.dvt': 'Dvt',
    'reception_order.xoa_mon_khoi_gio': 'Xoa mon khoi gio',
    'reception_order.trong_goi': 'Trong goi',
    'reception_order.0d': '0d',
    'reception_order.tam_tinh_mon_goi': 'Tam tinh mon goi',
    'reception_order.phi_dich_vu_5': 'Phi dich vu 5',
    'reception_order.thue_gtgt_vat_10': 'Thue gtgt VAT 10',
    'reception_order.tong_so_luong_mon': 'Tong so luong mon',
    'reception_order.mon': 'Mon',
    'reception_order.tong_thanh_toan_label': 'Tong thanh toan label',
    'reception_order.tam_luu': 'Tam luu',
    'reception_order.gui_bep': 'Gui bep',
    'reception_order.in_thanh_toan_bill': 'In thanh toan bill',
    'reception_order.yeu_thich_star': 'Yeu thich star',
    'reception_order.ban_chay_fire': 'Ban chay fire',
    'reception_order.moi_goi_clock': 'Moi goi clock',
    'reception_order.tat_ca_mon': 'Tat ca mon',
    'reception_order.con_mon': 'Con mon',
    'reception_order.het_mon': 'Het mon',
    'reception_order.khong_sap_xep': 'Khong sap xep',
    'reception_order.gia_thap_cao': 'Gia thap cao',
    'reception_order.gia_cao_thap': 'Gia cao thap',
    'reception_order.chi_mon_trong_goi': 'Chi mon trong goi',
    'reception_order.dang_loc_danh_muc_san_pham': 'Dang loc danh muc san pham',
    'reception_order.khong_tim_thay_mon_an_nao_khop': 'Khong tim thay mon an nao khop',
    'reception_order.thuc_don_hien_tai_khong_co_mon': 'Thuc don hien tai khong co mon',
    'reception_order.trong_goi_upper': 'Trong goi upper',
    'reception_order.chi_tiet_title': 'Chi tiet Tiêu đề',
    'reception_order.het_upper': 'Het upper',
    'reception_order.tat_ca': 'Tat ca',
    'reception_order.chi_tiet_mon_an': 'Chi tiet mon an',
    'reception_order.het_hang': 'Het hang',
    'reception_order.con_hang_phuc_vu_text': 'Con hang phuc vu text',
    'reception_order.het_hang_text': 'Het hang text',
    'reception_order.ma_mon': 'Ma mon',
    'reception_order.don_vi_tinh': 'Don vi tinh',
    'reception_order.so_luong': 'So luong',
    'reception_order.don_gia_vnd': 'Don gia vnd',
    'reception_order.0d_trong_goi': '0d trong goi',
    'reception_order.bao_gom_vat': 'Bao gom VAT',
    'reception_order.bao_gom_ppv': 'Bao gom ppv',
    'reception_order.loai_tien_te': 'Loai tien te',
    'reception_order.vnd_viet_nam_dong': 'Vnd viet nam dong',
    'reception_order.usd_do_la_my': 'Usd do la my',
    'reception_order.ty_gia': 'Ty gia',
    'reception_order.ghi_chu': 'Ghi chu',
    'reception_order.them_ghi_chu_dac_thu_it_da_nhi': 'Them ghi chu dac thu it da nhi',
    'reception_order.phan_nhom_thuc_don_he_thong': 'Phan nhom thuc don he thong',
    'reception_order.nhom_san_pham': 'Nhom san pham',
    'reception_order.goi_buffet': 'Goi buffet',
    'reception_order.goi_set_menu': 'Goi set menu',
    'reception_order.goi_do_uong': 'Goi do uong',
    'reception_order.ma': 'Ma',
    'reception_order.don_vi': 'Don vi',
    'reception_order.vat_percent': 'VAT percent',
    'reception_order.ppv_percent': 'Ppv percent',
    'reception_order.tien_te': 'Tien te',
    'reception_order.ghi_chu_chung': 'Ghi chu chung',
    'reception_order.them_ghi_chu_cho_ca_mon_an': 'Them ghi chu cho ca mon an',
    'reception_order.toi_thieu': 'Toi thieu',
    'reception_order.toi_da': 'Toi da',
    'reception_order.them_ghi_chu_rieng_cho_lua_cho': 'Them ghi chu rieng cho lua cho',
    'reception_order.vui_long_chon_them_it_nhat': 'Vui long chon them it nhat',
    'reception_order.lua_chon_nua': 'Lua chon nua',
    'reception_order.da_vuot_qua_gioi_han_toi_da': 'Da vuot qua gioi han toi da',
    'reception_order.lua_chon': 'Lua chon',
    'reception_order.da_chon_du_so_luong': 'Da chon du so luong',
    'reception_order.huy_bo_esc': 'Huy bo esc',
    'reception_order.them_vao_gio_hang': 'Them vao gio hang',
    'reception_order.cau_hinh_goi_course_phuc_vu': 'Cau hinh goi course phuc vu',
    'reception_order.1_chon_goi_an_phuc_vu_course_p': '1 chon goi an phuc vu course p',
    'reception_order.thoi_luong_phuc_vu_2_tieng': 'Thoi luong phuc vu 2 tieng',
    'reception_order.menu_goi_theo_bua_tiec': 'Menu goi theo bua tiec',
    'reception_order.ve': 'Ve',
    'reception_order.2_chon_nhom_do_uong_kem_theo_d': '2 chon nhom do uong kem theo d',
    'reception_order.nhom_a_soft_drink': 'Nhom a soft drink',
    'reception_order.nuoc_ngot_uong_khong_gioi_han': 'Nuoc ngot uong khong gioi han',
    'reception_order.nhom_b_premium_drink': 'Nhom b premium drink',
    'reception_order.ruou_bia_cao_cap_uong_trong_2': 'Ruou bia cao cap uong trong 2',
    'reception_order.nhom_c_premium_alt': 'Nhom c premium alt',
    'reception_order.ruou_bia_thay_the_dung_2_gio_f': 'Ruou bia thay the dung 2 gio f',
    'reception_order.nhom_d_a_la_carte': 'Nhom d a la carte',
    'reception_order.goi_do_uong_le_tinh_tien_rieng': 'Goi do uong le tinh tien rieng',
    'reception_order.3_ngon_ngu_giao_dien_hien_thi': '3 ngon ngu giao dien hien thi',
    'reception_order.tieng_viet': 'Tieng viet',
    'reception_order.huy_bo_quay_lai': 'Huy bo quay lai',
    'reception_order.pin_sua_cau_hinh': 'Pin sua cau hinh',
    'reception_order.xac_nhan_khoa_course': 'Xac nhan khoa course',
    'reception_order.ma_pin_xac_thuc_quan_ly': 'Ma pin xac thuc quan ly',
    'reception_order.nhap_ma_pin_cua_quan_ly_de_mo': 'Nhap ma pin cua quan ly de mo',
    'reception_order.khach_text': 'Khach text',
    'reception_order.gio_mo_text': 'Gio mo text',
    'reception_order.con_lai_text': 'Con lai text',
    'reception_order.tam_tinh_text': 'Tam tinh text',
    'reception_order.thue_gtgt_10_text': 'Thue gtgt 10 text',
    'reception_order.phi_phuc_vu_text': 'Phi phuc vu text',
    'reception_order.tong_cong_text': 'Tong cong text',
    'reception_order.thanh_toan_text': 'Thanh toan text',
    'reception_order.xem_tam_tinh_text': 'Xem tam tinh text',
    'reception_order.gio_hang_trong_text': 'Gio hang trong text',
    'reception_order.hay_chon_mon_tu_menu_text': 'Hay chon mon tu menu text',
    'reception_order.mon_yeu_thich_text': 'Mon yeu thich text',
    'reception_order.moi_goi_text': 'Moi goi text',
    'reception_order.ban_chay_text': 'Ban chay text',
    'reception_order.tim_mon_an_theo_ten_text': 'Tim mon an theo ten text',
    'reception_order.con_hang_text': 'Con hang text',
    'reception_order.tat_ca_text': 'Tat ca text',
    'reception_order.quay_lai_text': 'Quay lai text',
    'reception_order.luu_thay_doi_text': 'Luu thay doi text',
    'reception_order.tam_luu_text': 'Tam luu text',
    'reception_order.gui_vao_bep_text': 'Gui vao bep text',
    'reception_order.huy_thay_doi_text': 'Huy thay doi text',
    'reception_order.khoa_course_text': 'Khoa course text',
    'reception_order.khach_vang_lai_text': 'Khach vang lai text',
    'reception_order.khoa_course_thanh_cong': 'Khoa course thanh cong',
    'reception_order.nuoc_lau_di_kem': 'Nuoc lau di kem',
    'reception_order.lau_sukiyaki_ngot_thanh': 'Lau sukiyaki ngot thanh',
    'reception_order.lau_kimchi_chua_cay': 'Lau kimchi chua cay',
    'reception_order.lau_mala_tu_xuyen': 'Lau mala tu xuyen',
    'reception_order.lau_nam_thao_duoc': 'Lau nam thao duoc',
    'reception_order.lau_sua_dau_nanh': 'Lau sua dau nanh',
    'reception_order.chon_nuoc_lau_goi_buffet': 'Chon nuoc lau goi buffet',
    'reception_order.lau_sukiyaki_tieu_chuan': 'Lau sukiyaki tieu chuan',
    'reception_order.lau_kimchi_han_quoc': 'Lau kimchi han quoc',
    'reception_order.lau_nam_thao_moc': 'Lau nam thao moc',
    'reception_order.chon_mon_tang_kem': 'Chon mon tang kem',
    'reception_order.than_vai_bo_uc': 'Than vai bo uc',
    'reception_order.lon_bia_sapporo': 'Lon bia sapporo',
    'reception_order.dia_salad_bap_cai': 'Dia salad bap cai',
    'reception_order.mon_an_kem_chon_1': 'Mon an kem chon 1',
    'reception_order.canh_rong_bien': 'Canh rong bien',
    'reception_order.dia_kimchi_cai_thao': 'Dia kimchi cai thao',
    'reception_order.ly_hong_tra': 'Ly hong tra',
    'reception_order.khu_vuc': 'Khu vuc',
    'reception_order.trong_text': 'Trong text',
    'reception_order.da_dat_text': 'Da dat text',
    'reception_order.khach_den_text': 'Khach den text',
    'reception_order.dang_an_text': 'Dang an text',
    'reception_order.thoi_gian_an_con_lai_30_phut': 'Thoi gian an con lai 30 phut',
    'reception_order.thoi_gian_sap_het_10_phut': 'Thoi gian sap het 10 phut',
    'reception_order.phien_an_2_gio_da_ket_thuc': 'Phien an 2 gio da ket thuc',
    'reception_order.buffet_lau_upper': 'Buffet lau upper',
    'reception_order.khong_ap_dung': 'Khong ap dung',
    'reception_order.mon_tam_thoi_het_hang': 'Mon tam thoi het hang',
    'reception_order.da_dat_gioi_han_toi_da_10_phan': 'Da dat gioi han toi da 10 phan',
    'reception_order.da_them_vao_hoa_don': 'Da them vao hoa don',
    'reception_order.moi_luot_goi_toi_da_10_phan': 'Moi luot goi toi da 10 phan',
    'reception_order.xoa_mon_nay_khoi_don': 'Xoa mon nay khoi don',
    'reception_order.da_xoa_mon_khoi_gio': 'Da xoa mon khoi gio',
    'reception_order.ban_co_chac_muon_xoa_toan_bo_mon': 'Ban co chac muon xoa toan bo mon',
    'reception_order.da_xoa_toan_bo_mon': 'Da xoa toan bo mon',
    'reception_order.da_chon_gioi_han_toi_da': 'Da chon gioi han toi da',
    'reception_order.so_luong_goi_mon_vuot_qua': 'So luong goi mon vuot qua',
    'reception_order.da_them_mon_phan': 'Da them mon phan',
    'reception_order.vui_long_hoan_thanh_lua_chon': 'Vui long hoan thanh lua chon',
    'reception_order.da_them_mon_co_tuy_chon': 'Da them mon co tuy chon',
    'reception_order.da_bo_yeu_thich_mon': 'Da bo yeu thich mon',
    'reception_order.da_luu_mon_vao_yeu_thich': 'Da luu mon vao yeu thich',
    'reception_order.cau_hinh_da_bi_khoa': 'Cau hinh da bi khoa',
    'reception_order.nhom_thuc_uong_da_bi_khoa': 'Nhom thuc uong da bi khoa',
    'reception_order.vui_long_chon_goi_buffet': 'Vui long chon goi buffet',
    'reception_order.guestWalkIn': 'KháchWalkIn',
    'reception_order.courseLockedSuccess': 'CourseLockedSuccess',
    'reception_order.mo_khoa_cau_hinh_thanh_cong': 'Mo khoa cau hinh thanh cong',
    'reception_order.ma_pin_sai': 'Ma pin sai',
    'reception_order.hoa_don_tam_tinh_alert': 'Hoa don tam tinh alert',
    'reception_order.da_gui_lenh_in_tam_tinh': 'Da gui lenh in tam tinh',
    'reception_order.xac_nhan_thanh_toan': 'Xac nhan thanh toan',
    'reception_order.dong_ban_tam_tinh': 'Dong ban tam tinh',
    'reception_order.tien_hanh_thanh_toan': 'Tien hanh thanh toan',
    'reception_order.huy_text': 'Huy text',
    'reception_order.tai_khoan_chua_gan_chi_nhanh': 'Tai khoan chua gan chi nhanh',
    'reception_order.khong_tim_thay_ban': 'Khong tim thay ban',
    'reception_order.loi_text': 'Loi text',
    'reception_order.huy_bo_toan_bo_mon_an': 'Huy bo toan bo mon an',
    'reception_order.da_lam_trong_gio_hang': 'Da lam trong gio hang',
    'reception_order.da_luu_tam_don_hang': 'Da luu tam don hang',
    'reception_order.chua_co_mon_an_de_gui_bep': 'Chua co mon an de gui bep',
    'reception_order.chua_chon_ban': 'Chua chon ban',
    'reception_order.da_gui_mon_den_kds': 'Da gui mon den kds',
    'reception_order.bo_qua_mon_chua_map_db': 'Bo qua mon chua map db',
    'reception_order.gui_bep_that_bai': 'Gui bep that bai',
    'reception_order.mot_phut': 'Mot phut',
    'reception_order.da_luu_cau_hinh_mon_an': 'Da luu cau hinh mon an',
    'reception_order.buffet_lau': 'Buffet lau',
    'reception_order.da_cau_hinh_goi': 'Da cau hinh goi',
  
    // Dashboard Keys
    'reception.dashboard.loading_data': 'Loading data',
    'reception.dashboard.shift_overview': 'Ca làm việc Tổng quan',
    'reception.dashboard.today': 'Hôm nay',
    'reception.dashboard.tables_in_use': 'Bàns in use',
    'reception.dashboard.pending_checkout': 'Pending Thanh toán',
    'reception.dashboard.today_reservations': 'Hôm nay Đặt bàns',
    'reception.dashboard.active_shift': 'Active Ca làm việc',
    'reception.dashboard.opened_at': 'Opened at',
    'reception.dashboard.opening_cash': 'Opening cash',
    'reception.dashboard.needs_action_now': 'Needs Hành động now',
    'reception.dashboard.checkout_request': 'Thanh toán request',
    'reception.dashboard.guests': 'Kháchs',
    'reception.dashboard.proceed_to_checkout': 'Proceed to Thanh toán',
    'reception.dashboard.no_checkout_requests': 'No Thanh toán requests',
    'reception.dashboard.tables_serving_list': 'Bàns serving list',
    'reception.dashboard.table_code': 'Bàn Mã',
    'reception.dashboard.guest_col': 'Khách col',
    'reception.dashboard.time_col': 'Thời gian col',
    'reception.dashboard.status_col': 'Trạng thái col',
    'reception.dashboard.invoice_col': 'Hóa đơn col',
    'reception.dashboard.dining': 'Dining',
    'reception.dashboard.checkout_action': 'Thanh toán Hành động',
    'reception.dashboard.no_tables_serving': 'No Bàns serving',
    'reception.dashboard.booking_code': 'Booking Mã',
    'reception.dashboard.hour': 'Hour',
    'reception.dashboard.num_guests': 'Num Kháchs',
    'reception.dashboard.no_bookings_today': 'No bookings Hôm nay',
    'reception.dashboard.no_branch_error': 'No branch error',

    // Purchasing
    'purchasing.po_list': 'Đơn Đặt Hàng',
    'purchasing.create_po': 'Tạo Đơn Hàng',
    'purchasing.requisitions': 'Yêu Cầu Mua Hàng',
    'purchasing.suppliers': 'Nhà Cung Cấp',

    // Accounting
    'accounting.invoices': 'Hóa Đơn',
    'accounting.tax_export': 'Xuất Thuế',
    'accounting.inventory_valuation': 'Giá Trị Tồn Kho',

    // Marketing
    'marketing.title': 'Marketing',
    'marketing.campaigns': 'Chiến Dịch',
    'marketing.analytics': 'Phân Tích',

    // BOD
    'bod.hq_dashboard': 'Tổng Quan HQ',
    'bod.branch_performance': 'Hiệu Suất CN',
    'bod.audit_logs': 'Nhật Ký Hệ Thống',
    'bod.system_config': 'Cấu Hình',

    // CRM
    'crm.title': 'CRM',
    'crm.customers': 'Khách hàng',
    'crm.vouchers': 'Vouchers',
    'crm.feedback': 'Phản hồi',
    'crm.dashboard': 'Bảng Điều Khiển',
    'crm.servingTables': 'Bàn Đang Phục Vụ',
    'crm.refresh': 'Làm mới',
    'crm.noTables': 'Không tìm thấy bàn nào.',
    'crm.guests': 'Khách',
    'crm.status.toDo': 'Cần Làm',
    'crm.status.assigned': 'Đã Giao',
    'crm.status.inProgress': 'Đang Xử Lý',
    'crm.status.done': 'Hoàn Thành',
    'crm.status.skipped': 'Bỏ Qua',
    'crm.status.refused': 'Khách Từ Chối',
    'crm.action.start': 'Bắt đầu Khảo sát',
    'crm.action.view': 'Xem',
    'crm.surveyTitle': 'Khảo sát - ',
    'crm.customerInfo': 'Thông tin Khách hàng',
    'crm.name': 'Tên',
    'crm.phone': 'SĐT',
    'crm.visitReason': 'Lý do',
    'crm.selectReason': 'Chọn lý do',
    'crm.reason.casual': 'Ăn Uống Đơn Thuần',
    'crm.reason.birthday': 'Sinh Nhật',
    'crm.reason.anniversary': 'Kỷ Niệm',
    'crm.reason.business': 'Gặp Gỡ Đối Tác',
    'crm.reason.other': 'Khác',
    'crm.generalFeedback': 'Đánh Giá Chung',
    'crm.feedbackPlaceholder': 'Trải nghiệm của quý khách như thế nào?',
    'crm.improvementNotes': 'Ghi chú Cải thiện',
    'crm.improvementPlaceholder': 'Chúng tôi có thể làm gì tốt hơn?',
    'crm.saving': 'Đang lưu...',
    'crm.submitSurvey': 'Gửi Khảo Sát',
    'crm.markInProgress': 'Đánh dấu "Đang Xử Lý"',
    'crm.skip': 'Khách Từ Chối / Bỏ Qua',
    'crm.surveyCompleted': 'Khảo sát Hoàn tất',
    'crm.alreadySurveyed': 'Bàn này đã được khảo sát.',
    'crm.noFeedback': 'Không có phản hồi.',
    'crm.anonymous': 'Khách Vãng Lai',
    'crm.noComment': 'Không để lại bình luận.',
    'crm.recentFeedback': "Phản hồi Gần đây",
    'crm.readCustomers': "Đọc đánh giá từ khách hàng",
    'crm.overview': "Tổng quan",
    'crm.stats.completed': "Đã Hoàn Thành",
    'crm.stats.customersPlus': "+12 tuần này",
    'crm.stats.avgRating': "Đánh giá TB",
    'crm.stats.ratingPlus': "+0.2 so với tuần trước",
    'crm.stats.today': "Hôm nay",
    'crm.stats.activeTables': "/ 30 bàn",
    'crm.quickActions': "Hành động Nhanh",
    'crm.startSurvey': "Bắt đầu Khảo sát",
    'crm.viewTablesToBegin': "Xem bàn để bắt đầu"
  },
  en: {
    // Hall / Checkout
    'hall.title':              'Hall',
    'hall.dashboard':          'Dashboard',
    'hall.floor_plan':         'Floor Plan',
    'hall.service_requests':   'Service Requests',
    'hall.checkout':           'Checkout',
    'checkout.subtotal':       'Subtotal',
    'checkout.discount_tier':  'Member Discount',
    'checkout.discount_voucher':'Voucher',
    'checkout.discount_points':'Redeem Points',
    'checkout.service_charge': 'Service Charge',
    'checkout.vat':            'VAT',
    'checkout.grand_total':    'Grand Total',
    'checkout.payment_method': 'Payment Method',
    'checkout.points_preview': '{points} points = -{amount}đ',
    'checkout.confirm':        'Confirm Payment',
    'checkout.success':        'Payment successful!',
    'checkout.receipt.print':  'Print Receipt',
    // Service Requests
    'service.call_waiter':     'Call Waiter',
    'service.request_bill':    'Request Bill',
    'service.condiment':       'Request Condiment',
    'service.complaint':       'Feedback',
    'service.open':            'New',
    'service.in_progress':     'In Progress',
    'service.resolved':        'Resolved',
    'service.urgent':          'Urgent',
    'service.sent':            'Request sent!',
    // Reservations
    'reservation.title':       'Reservations',
    'reservation.create':      'New Reservation',
    'reservation.date':        'Date',
    'reservation.time':        'Time',
    'reservation.guests':      'Guests',
    'reservation.status.pending':  'Pending',
    'reservation.status.confirmed':'Confirmed',
    'reservation.status.seated':   'Seated',
    'reservation.status.completed':'Completed',
    'reservation.status.no_show':  'No Show',
    'reservation.confirm_table':   'Confirm Table',
    'reservation.seat_now':        'Seat Now',
    'reservation.no_show':         'Mark No Show',
    // Purchasing
    'purchasing.title':          'Purchasing',
    'purchasing.purchase_order': 'Purchase Order',
    'purchasing.po_number':      'PO Number',
    'purchasing.supplier':       'Supplier',
    'purchasing.expected_delivery':'Expected Delivery',
    'purchasing.receive':        'Receive Goods',
    'purchasing.status.draft':   'Draft',
    'purchasing.status.submitted':'Submitted',
    'purchasing.status.received':'Received',
    'purchasing.status.partial': 'Partial',
    // Accounting
    'accounting.title':          'Accounting',
    'accounting.revenue':        'Revenue',
    'accounting.expense':        'Expense',
    'accounting.profit_loss':    'Profit & Loss',
    'accounting.tax':            'Tax',
    'accounting.gross_revenue':  'Gross Revenue',
    'accounting.net_revenue':    'Net Revenue',
    'accounting.gross_profit':   'Gross Profit',
    'accounting.profit_margin':  'Profit Margin',
    'accounting.vat_collected':  'VAT Collected',
    'accounting.generate_tax':   'Generate Tax Record',
    'accounting.void_invoice':   'Void Invoice',
    // Campaigns
    'campaign.title':            'Campaigns',
    'campaign.create':           'Create Campaign',
    'campaign.type.seasonal':    'Seasonal',
    'campaign.type.loyalty':     'Loyalty',
    'campaign.type.flash':       'Flash Sale',
    'campaign.status.draft':     'Draft',
    'campaign.status.pending':   'Pending Approval',
    'campaign.status.approved':  'Approved',
    'campaign.status.active':    'Active',
    'campaign.submit_approval':  'Submit for Approval',
    // BOD
    'bod.title':               'Board of Directors',
    'bod.dashboard':           'Dashboard',
    'bod.approvals':           'Approvals',
    'bod.kpi':                 'KPI Target',
    'bod.budget':              'Budget',
    'bod.revenue_target':      'Revenue Target',
    'bod.breakeven':           'Break-even',
    'bod.vs_target':           'Actual / Target',
    'bod.approve':             'Approve',
    'bod.reject':              'Reject',
    // Feedback
    'feedback.title':          'Feedback',
    'feedback.overall':        'Overall',
    'feedback.food':           'Food Quality',
    'feedback.service':        'Service Quality',
    'feedback.ambiance':       'Ambiance',
    'feedback.comment':        'Comment',
    'feedback.submit':         'Submit Feedback',
    'feedback.thank_you':      'Thank you for your feedback!',
    'feedback.respond':        'Respond',
    'inventory.title':                'Inventory Management',
    'inventory.lowStock':             'Low Stock',
    'inventory.expiryWarning':        'Expiring Soon',
    'inventory.addStock':             'Add Stock',
    'inventory.adjust':               'Adjust Count',
    'inventory.unit':                 'Unit',
    'inventory.quantity':             'Quantity',
    'inventory.threshold':            'Alert Threshold',
    'inventory.search':               'Search ingredients...',
    'req.title':                      'Requisitions',
    'req.create':                     'New Requisition',
    'req.status.pending':             'Pending Approval',
    'req.status.approved':            'Approved',
    'req.status.rejected':            'Rejected',
    'req.status.processing':          'Processing',
    'req.status.completed':           'Completed',
    'req.status.cancelled':           'Cancelled',
    'req.type.outbound':              'Outbound',
    'req.type.inbound':               'Inbound',
    'req.type.return':                'Return',
    'req.approve':                    'Approve',
    'req.reject':                     'Reject',
    'req.confirm_delivery':           'Confirm Delivery',
    'req.rejection_reason':           'Reason for rejection',
    'req.needed_by':                  'Needed by',
    'shift.start':                    'Start Shift',
    'shift.close':                    'Close Shift',
    'shift.handover':                 'Shift Handover',
    'shift.type.morning':             'Morning Shift',
    'shift.type.afternoon':           'Afternoon Shift',
    'shift.type.evening':             'Evening Shift',
    'shift.count_ingredients':        'Count Ingredients',
    'shift.discrepancy':              'Discrepancy',
    'tablet.touch_to_start':          'Touch to Begin',
    'tablet.select_language':         'Select Language',
    'branch.title':                   'Branches',
    'branch.add':                     'Add Branch',
    'branch.edit':                    'Edit',
    'branch.deactivate':              'Deactivate',
    'branch.capacity':                'Capacity',
    'branch.manager':                 'Manager',
    'integration.title':              'Integrations',
    'integration.payment':            'Payment',
    'integration.delivery':           'Delivery',
    'integration.test_connection':    'Test Connection',
    'integration.api_key':            'API Key',
    'integration.webhook':            'Webhook URL',
    'common.save':                    'Save',
    'common.cancel':                  'Cancel',
    'common.confirm':                 'Confirm',
    'common.loading':                 'Loading...',
    'common.error':                   'Error',
    'common.success':                 'Success',
    'common.search':                  'Search',
    'common.no_data':                 'No data',
  
    // Reception Keys
    'reception.restaurant': 'Restaurant',
    'reception.other_income': 'Other Income',
    'reception.other_expense': 'Other Expense',
    'reception.configuration': 'Configuration',
    'reception.receipt': 'Receipt',
    'reception.reports': 'Reports',
    'reception.shift_details': 'Shift Details',
    'reception.notifications': 'Notifications',
    'reception.read': 'Read',
    'reception.urgent': 'Urgent',
    'reception.tables_in_use': 'Tables in Use',
    'reception.waiting_payment': 'Waiting Payment',
    'reception.reservations_today': 'Reservations Today',
    'reception.quick_actions': 'Quick Actions',
    'reception.open_shift': 'Open Shift',
    'reception.started_at': 'Started at',
    'reception.initial_cash': 'Initial Cash',
    'reception.temp_amount': 'Temp Amount',
    'reception.upcoming': 'Upcoming',
    'reception.reservation_count': 'reservations',
    'reception.view_more': 'View More',
    'reception.payment_request': 'Payment Request',
    'reception.new_order': 'New Order',
    'reception.out_of_stock': 'Out of Stock',
    'reception.stock_notification': 'Stock Notification',
    'reception.just_now': 'Just now',
    'reception.minutes_ago': 'minutes ago',
    'reception.branch': 'Branch',
    'reception.system': 'System',
    'reception.connection': 'Connection',
    'reception.close': 'Close',
    'reception.no_open_shift': 'No Active Shift',
    'reception.please_open_shift': 'Please open a shift to continue',
    'reception.open_shift_btn': 'Open Shift',
    'reception.other_income_short': 'Other Income',
    'reception.other_expenses': 'Other Expense',
    'reception.current_shift_summary': 'Current Shift Summary',
    'reception.start_time': 'Start Time',
    'reception.opening_balance': 'Opening Balance',
    'reception.current_revenue': 'Current Revenue',
    'reception.processed_orders': 'Processed Orders',
    'reception.no_active_shifts': 'No active shifts',
    'reception.serving_tables_list': 'Serving Tables List',
    'reception.guests': 'Guests',
    'reception.seated_time': 'Seated Time',
    'reception.ordered_items': 'Ordered Items',
    'reception.action_col': 'Action',
    'reception.loading': 'Loading...',
    'reception.payment': 'Payment',
    'reception.no_active_tables': 'No active tables',
    'reception.reservation_code': 'Reservation Code',
    'reception.customer_phone': 'Phone Number',
    'reception.reserved_time': 'Reserved Time',
    'reception.number_of_people': 'Guests',
    'reception.status': 'Status',
    'reception.confirm': 'Confirm',
    'reception.cancel': 'Cancel',
    'reception.no_action': 'No Action',
    'reception.no_reservations_today': 'No reservations today',
    'reception.no_notifications': 'No notifications',
    'reception.enter_target_name': 'Enter target name...',
    'reception.other': 'Other',
    'reception.reason': 'Reason',
    'reception.enter_reason': 'Enter reason...',
    'reception.auto_generated': 'System generated',
    'reception.enter_booking_code': 'Enter booking code...',
    'reception.cash': 'Cash',
    'reception.save_and_print': 'Save & Print',
    'reception.save': 'Save',
    'reception.skip': 'Skip',
    'reception.username': 'Username',
    'reception.enter_username': 'Enter username...',
    'reception.password': 'Password',
    'reception.enter_password': 'Enter password...',
    'reception.ignore': 'Ignore',
    'reception.checkout.title': 'Title',
    'reception.checkout.no_open_invoice': 'No open invoice',
    'reception.checkout.script_title': 'Script title',
    'reception.checkout.script_content': 'Script content',
    'reception.checkout.step1_title': 'Step1 title',
    'reception.checkout.phone_placeholder': 'Phone placeholder',
    'reception.checkout.search': 'Search',
    'reception.checkout.member': 'Member',
    'reception.checkout.customer_not_found': 'Customer not found',
    'reception.checkout.step2_title': 'Step2 title',
    'reception.checkout.revenue_type': 'Revenue type',
    'reception.checkout.dinner': 'Dinner',
    'reception.checkout.lunch': 'Lunch',
    'reception.checkout.wine': 'Wine',
    'reception.checkout.delivery': 'Delivery',
    'reception.checkout.other': 'Other',
    'reception.checkout.enter_voucher': 'Enter voucher',
    'reception.checkout.voucher_placeholder': 'Voucher placeholder',
    'reception.checkout.apply': 'Apply',
    'reception.checkout.voucher_applied_notice': 'Voucher applied notice',
    'reception.checkout.step3_title': 'Step3 title',
    'reception.checkout.received_amount': 'Received amount',
    'reception.checkout.change_amount': 'Change amount',
    'reception.checkout.insufficient_amount': 'Insufficient amount',
    'reception.checkout.reference_code': 'Reference code',
    'reception.checkout.card_last_4': 'Card last 4',
    'reception.checkout.transaction_code': 'Transaction code',
    'reception.checkout.simulation_notice': 'Simulation notice',
    'reception.checkout.voucher_payment_notice': 'Voucher payment notice',
    'reception.checkout.invoice_summary': 'Invoice summary',
    'reception.checkout.guest_count': 'Guest count',
    'reception.checkout.loading_invoice': 'Loading invoice',
    'reception.checkout.no_items': 'No items',
    'reception.checkout.subtotal': 'Subtotal',
    'reception.checkout.vat': 'Vat',
    'reception.checkout.voucher': 'Voucher',
    'reception.checkout.will_apply': 'Will apply',
    'reception.checkout.total_amount': 'Total amount',
    'reception.checkout.processing': 'Processing',
    'reception.checkout.print_invoice_close_table': 'Print invoice close table',
    'reception.checkout.enter_amount_warning': 'Enter amount warning',
    'reception.checkout.cash': 'Cash',
    'reception.checkout.card': 'Card',
    'reception.checkout.transfer': 'Transfer',
    'reception.checkout.voucher_label': 'Voucher label',
    'reception.checkout.loading': 'Loading',
    'reception.checkout.no_open_order': 'No open order',
    'reception.checkout.processing_payment': 'Processing payment',
    'reception.checkout.ready_to_pay': 'Ready to pay',
    'reception.checkout.voucher_will_be_checked': 'Voucher will be checked',
    'reception.checkout.voucher_check_msg': 'Voucher check msg',
    'reception.checkout.no_branch_error': 'No branch error',
    'reception.checkout.payment_condition_not_met': 'Payment condition not met',
    'reception.checkout.payment_success': 'Payment success',
    'reception.checkout.invoice_label': 'Invoice label',
    'reception.checkout.total_label': 'Total label',
    'reception.checkout.change_label': 'Change label',
    'reception.checkout.error': 'Error',
    'reception.checkout.payment_failed': 'Payment failed',
    'reception.close_shift.title': 'Title',
    'reception.close_shift.subtitle': 'Subtitle',
    'reception.close_shift.export_csv': 'Export csv',
    'reception.close_shift.closing_shift': 'Closing shift',
    'reception.close_shift.confirm_close_shift': 'Confirm close shift',
    'reception.close_shift.active_shift': 'Active shift',
    'reception.close_shift.opened_at': 'Opened at',
    'reception.close_shift.opening_cash': 'Opening cash',
    'reception.close_shift.no_active_shift': 'No active shift',
    'reception.close_shift.revenue_by_type': 'Revenue by type',
    'reception.close_shift.loading': 'Loading',
    'reception.close_shift.dinner': 'Dinner',
    'reception.close_shift.bill_count': 'Bill count',
    'reception.close_shift.lunch': 'Lunch',
    'reception.close_shift.wine': 'Wine',
    'reception.close_shift.delivery': 'Delivery',
    'reception.close_shift.order_count': 'Order count',
    'reception.close_shift.total_daily_revenue': 'Total daily revenue',
    'reception.close_shift.cash_reconciliation': 'Cash reconciliation',
    'reception.close_shift.initial_cash': 'Initial cash',
    'reception.close_shift.cash_revenue': 'Cash revenue',
    'reception.close_shift.expected_cash': 'Expected cash',
    'reception.close_shift.non_cash_revenue': 'Non cash revenue',
    'reception.close_shift.payment_history': 'Payment history',
    'reception.close_shift.turn_count': 'Turn count',
    'reception.close_shift.time': 'Time',
    'reception.close_shift.payment_method': 'Payment method',
    'reception.close_shift.revenue_category': 'Revenue category',
    'reception.close_shift.amount': 'Amount',
    'reception.close_shift.received_from_guest': 'Received from guest',
    'reception.close_shift.change': 'Change',
    'reception.close_shift.no_data': 'No data',
    'reception.close_shift.cash_label': 'Cash label',
    'reception.close_shift.card_label': 'Card label',
    'reception.close_shift.transfer_label': 'Transfer label',
    'reception.close_shift.voucher_label': 'Voucher label',
    'reception.close_shift.other_label': 'Other label',
    'reception.close_shift.dinner_label': 'Dinner label',
    'reception.close_shift.lunch_label': 'Lunch label',
    'reception.close_shift.wine_label': 'Wine label',
    'reception.close_shift.delivery_label': 'Delivery label',
    'reception.close_shift.notification': 'Notification',
    'reception.close_shift.no_active_shift_alert': 'No active shift alert',
    'reception.close_shift.close_shift_title': 'Close shift title',
    'reception.close_shift.expected_cash_sys': 'Expected cash sys',
    'reception.close_shift.actual_cash_placeholder': 'Actual cash placeholder',
    'reception.close_shift.handover_notes': 'Handover notes',
    'reception.close_shift.confirm_close_btn': 'Confirm close btn',
    'reception.close_shift.cancel_btn': 'Cancel btn',
    'reception.close_shift.enter_actual_cash_warning': 'Enter actual cash warning',
    'reception.close_shift.close_shift_success': 'Close shift success',
    'reception.close_shift.cash_diff': 'Cash diff',
    'reception.close_shift.expected_label': 'Expected label',
    'reception.close_shift.actual_label': 'Actual label',
    'reception.close_shift.error_title': 'Error title',
    'reception.close_shift.close_shift_error': 'Close shift error',
    'reception.close_shift.no_shift_export_alert': 'No shift export alert',
    'reception.close_shift.success_title': 'Success title',
    'reception.close_shift.csv_downloaded': 'Csv downloaded',
    'reception.close_shift.export_csv_error': 'Export csv error',
    'reception_order.quyen_truy_cap_bi_tu_choi': 'Quyen truy cap bi tu choi',
    'reception_order.vui_long_chon_mot_ban_an_dang': 'Vui long chon mot ban an dang',
    'reception_order.di_toi_so_do_ban': 'Di toi so do ban',
    'reception_order.quay_lai_aria': 'Quay lai aria',
    'reception_order.quay_lai': 'Quay lai',
    'reception_order.nguu_cat_pos': 'Nguu cat pos',
    'reception_order.hoa_don': 'Hoa don',
    'reception_order.khach_hang': 'Khach hang',
    'reception_order.gio_mo': 'Gio mo',
    'reception_order.thoi_gian': 'Thoi gian',
    'reception_order.tim_kiem': 'Tim kiem',
    'reception_order.xem_hoa_don_tam_tinh': 'Xem hoa don tam tinh',
    'reception_order.cau_hinh_goi_ngon_ngu': 'Cau hinh goi ngon ngu',
    'reception_order.thoi_gian_do_uong_premium_da_k': 'Thoi gian do uong premium da k',
    'reception_order.mo_khoa_pin': 'Mo khoa pin',
    'reception_order.ban_phuc_vu': 'Ban phuc vu',
    'reception_order.ban_text': 'Ban text',
    'reception_order.xoa_het': 'Xoa het',
    'reception_order.ten_mon': 'Ten mon',
    'reception_order.don_gia': 'Don gia',
    'reception_order.thanh_tien': 'Thanh tien',
    'reception_order.hoa_don_trong': 'Hoa don trong',
    'reception_order.vui_long_chon_mon_an_tu_thuc_d': 'Vui long chon mon an tu thuc d',
    'reception_order.dvt': 'Dvt',
    'reception_order.xoa_mon_khoi_gio': 'Xoa mon khoi gio',
    'reception_order.trong_goi': 'Trong goi',
    'reception_order.0d': '0d',
    'reception_order.tam_tinh_mon_goi': 'Tam tinh mon goi',
    'reception_order.phi_dich_vu_5': 'Phi dich vu 5',
    'reception_order.thue_gtgt_vat_10': 'Thue gtgt vat 10',
    'reception_order.tong_so_luong_mon': 'Tong so luong mon',
    'reception_order.mon': 'Mon',
    'reception_order.tong_thanh_toan_label': 'Tong thanh toan label',
    'reception_order.tam_luu': 'Tam luu',
    'reception_order.gui_bep': 'Gui bep',
    'reception_order.in_thanh_toan_bill': 'In thanh toan bill',
    'reception_order.yeu_thich_star': 'Yeu thich star',
    'reception_order.ban_chay_fire': 'Ban chay fire',
    'reception_order.moi_goi_clock': 'Moi goi clock',
    'reception_order.tat_ca_mon': 'Tat ca mon',
    'reception_order.con_mon': 'Con mon',
    'reception_order.het_mon': 'Het mon',
    'reception_order.khong_sap_xep': 'Khong sap xep',
    'reception_order.gia_thap_cao': 'Gia thap cao',
    'reception_order.gia_cao_thap': 'Gia cao thap',
    'reception_order.chi_mon_trong_goi': 'Chi mon trong goi',
    'reception_order.dang_loc_danh_muc_san_pham': 'Dang loc danh muc san pham',
    'reception_order.khong_tim_thay_mon_an_nao_khop': 'Khong tim thay mon an nao khop',
    'reception_order.thuc_don_hien_tai_khong_co_mon': 'Thuc don hien tai khong co mon',
    'reception_order.trong_goi_upper': 'Trong goi upper',
    'reception_order.chi_tiet_title': 'Chi tiet title',
    'reception_order.het_upper': 'Het upper',
    'reception_order.tat_ca': 'Tat ca',
    'reception_order.chi_tiet_mon_an': 'Chi tiet mon an',
    'reception_order.het_hang': 'Het hang',
    'reception_order.con_hang_phuc_vu_text': 'Con hang phuc vu text',
    'reception_order.het_hang_text': 'Het hang text',
    'reception_order.ma_mon': 'Ma mon',
    'reception_order.don_vi_tinh': 'Don vi tinh',
    'reception_order.so_luong': 'So luong',
    'reception_order.don_gia_vnd': 'Don gia vnd',
    'reception_order.0d_trong_goi': '0d trong goi',
    'reception_order.bao_gom_vat': 'Bao gom vat',
    'reception_order.bao_gom_ppv': 'Bao gom ppv',
    'reception_order.loai_tien_te': 'Loai tien te',
    'reception_order.vnd_viet_nam_dong': 'Vnd viet nam dong',
    'reception_order.usd_do_la_my': 'Usd do la my',
    'reception_order.ty_gia': 'Ty gia',
    'reception_order.ghi_chu': 'Ghi chu',
    'reception_order.them_ghi_chu_dac_thu_it_da_nhi': 'Them ghi chu dac thu it da nhi',
    'reception_order.phan_nhom_thuc_don_he_thong': 'Phan nhom thuc don he thong',
    'reception_order.nhom_san_pham': 'Nhom san pham',
    'reception_order.goi_buffet': 'Goi buffet',
    'reception_order.goi_set_menu': 'Goi set menu',
    'reception_order.goi_do_uong': 'Goi do uong',
    'reception_order.ma': 'Ma',
    'reception_order.don_vi': 'Don vi',
    'reception_order.vat_percent': 'Vat percent',
    'reception_order.ppv_percent': 'Ppv percent',
    'reception_order.tien_te': 'Tien te',
    'reception_order.ghi_chu_chung': 'Ghi chu chung',
    'reception_order.them_ghi_chu_cho_ca_mon_an': 'Them ghi chu cho ca mon an',
    'reception_order.toi_thieu': 'Toi thieu',
    'reception_order.toi_da': 'Toi da',
    'reception_order.them_ghi_chu_rieng_cho_lua_cho': 'Them ghi chu rieng cho lua cho',
    'reception_order.vui_long_chon_them_it_nhat': 'Vui long chon them it nhat',
    'reception_order.lua_chon_nua': 'Lua chon nua',
    'reception_order.da_vuot_qua_gioi_han_toi_da': 'Da vuot qua gioi han toi da',
    'reception_order.lua_chon': 'Lua chon',
    'reception_order.da_chon_du_so_luong': 'Da chon du so luong',
    'reception_order.huy_bo_esc': 'Huy bo esc',
    'reception_order.them_vao_gio_hang': 'Them vao gio hang',
    'reception_order.cau_hinh_goi_course_phuc_vu': 'Cau hinh goi course phuc vu',
    'reception_order.1_chon_goi_an_phuc_vu_course_p': '1 chon goi an phuc vu course p',
    'reception_order.thoi_luong_phuc_vu_2_tieng': 'Thoi luong phuc vu 2 tieng',
    'reception_order.menu_goi_theo_bua_tiec': 'Menu goi theo bua tiec',
    'reception_order.ve': 'Ve',
    'reception_order.2_chon_nhom_do_uong_kem_theo_d': '2 chon nhom do uong kem theo d',
    'reception_order.nhom_a_soft_drink': 'Nhom a soft drink',
    'reception_order.nuoc_ngot_uong_khong_gioi_han': 'Nuoc ngot uong khong gioi han',
    'reception_order.nhom_b_premium_drink': 'Nhom b premium drink',
    'reception_order.ruou_bia_cao_cap_uong_trong_2': 'Ruou bia cao cap uong trong 2',
    'reception_order.nhom_c_premium_alt': 'Nhom c premium alt',
    'reception_order.ruou_bia_thay_the_dung_2_gio_f': 'Ruou bia thay the dung 2 gio f',
    'reception_order.nhom_d_a_la_carte': 'Nhom d a la carte',
    'reception_order.goi_do_uong_le_tinh_tien_rieng': 'Goi do uong le tinh tien rieng',
    'reception_order.3_ngon_ngu_giao_dien_hien_thi': '3 ngon ngu giao dien hien thi',
    'reception_order.tieng_viet': 'Tieng viet',
    'reception_order.huy_bo_quay_lai': 'Huy bo quay lai',
    'reception_order.pin_sua_cau_hinh': 'Pin sua cau hinh',
    'reception_order.xac_nhan_khoa_course': 'Xac nhan khoa course',
    'reception_order.ma_pin_xac_thuc_quan_ly': 'Ma pin xac thuc quan ly',
    'reception_order.nhap_ma_pin_cua_quan_ly_de_mo': 'Nhap ma pin cua quan ly de mo',
    'reception_order.khach_text': 'Khach text',
    'reception_order.gio_mo_text': 'Gio mo text',
    'reception_order.con_lai_text': 'Con lai text',
    'reception_order.tam_tinh_text': 'Tam tinh text',
    'reception_order.thue_gtgt_10_text': 'Thue gtgt 10 text',
    'reception_order.phi_phuc_vu_text': 'Phi phuc vu text',
    'reception_order.tong_cong_text': 'Tong cong text',
    'reception_order.thanh_toan_text': 'Thanh toan text',
    'reception_order.xem_tam_tinh_text': 'Xem tam tinh text',
    'reception_order.gio_hang_trong_text': 'Gio hang trong text',
    'reception_order.hay_chon_mon_tu_menu_text': 'Hay chon mon tu menu text',
    'reception_order.mon_yeu_thich_text': 'Mon yeu thich text',
    'reception_order.moi_goi_text': 'Moi goi text',
    'reception_order.ban_chay_text': 'Ban chay text',
    'reception_order.tim_mon_an_theo_ten_text': 'Tim mon an theo ten text',
    'reception_order.con_hang_text': 'Con hang text',
    'reception_order.tat_ca_text': 'Tat ca text',
    'reception_order.quay_lai_text': 'Quay lai text',
    'reception_order.luu_thay_doi_text': 'Luu thay doi text',
    'reception_order.tam_luu_text': 'Tam luu text',
    'reception_order.gui_vao_bep_text': 'Gui vao bep text',
    'reception_order.huy_thay_doi_text': 'Huy thay doi text',
    'reception_order.khoa_course_text': 'Khoa course text',
    'reception_order.khach_vang_lai_text': 'Khach vang lai text',
    'reception_order.khoa_course_thanh_cong': 'Khoa course thanh cong',
    'reception_order.nuoc_lau_di_kem': 'Nuoc lau di kem',
    'reception_order.lau_sukiyaki_ngot_thanh': 'Lau sukiyaki ngot thanh',
    'reception_order.lau_kimchi_chua_cay': 'Lau kimchi chua cay',
    'reception_order.lau_mala_tu_xuyen': 'Lau mala tu xuyen',
    'reception_order.lau_nam_thao_duoc': 'Lau nam thao duoc',
    'reception_order.lau_sua_dau_nanh': 'Lau sua dau nanh',
    'reception_order.chon_nuoc_lau_goi_buffet': 'Chon nuoc lau goi buffet',
    'reception_order.lau_sukiyaki_tieu_chuan': 'Lau sukiyaki tieu chuan',
    'reception_order.lau_kimchi_han_quoc': 'Lau kimchi han quoc',
    'reception_order.lau_nam_thao_moc': 'Lau nam thao moc',
    'reception_order.chon_mon_tang_kem': 'Chon mon tang kem',
    'reception_order.than_vai_bo_uc': 'Than vai bo uc',
    'reception_order.lon_bia_sapporo': 'Lon bia sapporo',
    'reception_order.dia_salad_bap_cai': 'Dia salad bap cai',
    'reception_order.mon_an_kem_chon_1': 'Mon an kem chon 1',
    'reception_order.canh_rong_bien': 'Canh rong bien',
    'reception_order.dia_kimchi_cai_thao': 'Dia kimchi cai thao',
    'reception_order.ly_hong_tra': 'Ly hong tra',
    'reception_order.khu_vuc': 'Khu vuc',
    'reception_order.trong_text': 'Trong text',
    'reception_order.da_dat_text': 'Da dat text',
    'reception_order.khach_den_text': 'Khach den text',
    'reception_order.dang_an_text': 'Dang an text',
    'reception_order.thoi_gian_an_con_lai_30_phut': 'Thoi gian an con lai 30 phut',
    'reception_order.thoi_gian_sap_het_10_phut': 'Thoi gian sap het 10 phut',
    'reception_order.phien_an_2_gio_da_ket_thuc': 'Phien an 2 gio da ket thuc',
    'reception_order.buffet_lau_upper': 'Buffet lau upper',
    'reception_order.khong_ap_dung': 'Khong ap dung',
    'reception_order.mon_tam_thoi_het_hang': 'Mon tam thoi het hang',
    'reception_order.da_dat_gioi_han_toi_da_10_phan': 'Da dat gioi han toi da 10 phan',
    'reception_order.da_them_vao_hoa_don': 'Da them vao hoa don',
    'reception_order.moi_luot_goi_toi_da_10_phan': 'Moi luot goi toi da 10 phan',
    'reception_order.xoa_mon_nay_khoi_don': 'Xoa mon nay khoi don',
    'reception_order.da_xoa_mon_khoi_gio': 'Da xoa mon khoi gio',
    'reception_order.ban_co_chac_muon_xoa_toan_bo_mon': 'Ban co chac muon xoa toan bo mon',
    'reception_order.da_xoa_toan_bo_mon': 'Da xoa toan bo mon',
    'reception_order.da_chon_gioi_han_toi_da': 'Da chon gioi han toi da',
    'reception_order.so_luong_goi_mon_vuot_qua': 'So luong goi mon vuot qua',
    'reception_order.da_them_mon_phan': 'Da them mon phan',
    'reception_order.vui_long_hoan_thanh_lua_chon': 'Vui long hoan thanh lua chon',
    'reception_order.da_them_mon_co_tuy_chon': 'Da them mon co tuy chon',
    'reception_order.da_bo_yeu_thich_mon': 'Da bo yeu thich mon',
    'reception_order.da_luu_mon_vao_yeu_thich': 'Da luu mon vao yeu thich',
    'reception_order.cau_hinh_da_bi_khoa': 'Cau hinh da bi khoa',
    'reception_order.nhom_thuc_uong_da_bi_khoa': 'Nhom thuc uong da bi khoa',
    'reception_order.vui_long_chon_goi_buffet': 'Vui long chon goi buffet',
    'reception_order.guestWalkIn': 'GuestWalkIn',
    'reception_order.courseLockedSuccess': 'CourseLockedSuccess',
    'reception_order.mo_khoa_cau_hinh_thanh_cong': 'Mo khoa cau hinh thanh cong',
    'reception_order.ma_pin_sai': 'Ma pin sai',
    'reception_order.hoa_don_tam_tinh_alert': 'Hoa don tam tinh alert',
    'reception_order.da_gui_lenh_in_tam_tinh': 'Da gui lenh in tam tinh',
    'reception_order.xac_nhan_thanh_toan': 'Xac nhan thanh toan',
    'reception_order.dong_ban_tam_tinh': 'Dong ban tam tinh',
    'reception_order.tien_hanh_thanh_toan': 'Tien hanh thanh toan',
    'reception_order.huy_text': 'Huy text',
    'reception_order.tai_khoan_chua_gan_chi_nhanh': 'Tai khoan chua gan chi nhanh',
    'reception_order.khong_tim_thay_ban': 'Khong tim thay ban',
    'reception_order.loi_text': 'Loi text',
    'reception_order.huy_bo_toan_bo_mon_an': 'Huy bo toan bo mon an',
    'reception_order.da_lam_trong_gio_hang': 'Da lam trong gio hang',
    'reception_order.da_luu_tam_don_hang': 'Da luu tam don hang',
    'reception_order.chua_co_mon_an_de_gui_bep': 'Chua co mon an de gui bep',
    'reception_order.chua_chon_ban': 'Chua chon ban',
    'reception_order.da_gui_mon_den_kds': 'Da gui mon den kds',
    'reception_order.bo_qua_mon_chua_map_db': 'Bo qua mon chua map db',
    'reception_order.gui_bep_that_bai': 'Gui bep that bai',
    'reception_order.mot_phut': 'Mot phut',
    'reception_order.da_luu_cau_hinh_mon_an': 'Da luu cau hinh mon an',
    'reception_order.buffet_lau': 'Buffet lau',
    'reception_order.da_cau_hinh_goi': 'Da cau hinh goi',
  
    // Dashboard Keys
    'reception.dashboard.loading_data': 'Loading data',
    'reception.dashboard.shift_overview': 'Shift overview',
    'reception.dashboard.today': 'Today',
    'reception.dashboard.tables_in_use': 'Tables in use',
    'reception.dashboard.pending_checkout': 'Pending checkout',
    'reception.dashboard.today_reservations': 'Today reservations',
    'reception.dashboard.active_shift': 'Active shift',
    'reception.dashboard.opened_at': 'Opened at',
    'reception.dashboard.opening_cash': 'Opening cash',
    'reception.dashboard.needs_action_now': 'Needs action now',
    'reception.dashboard.checkout_request': 'Checkout request',
    'reception.dashboard.guests': 'Guests',
    'reception.dashboard.proceed_to_checkout': 'Proceed to checkout',
    'reception.dashboard.no_checkout_requests': 'No checkout requests',
    'reception.dashboard.tables_serving_list': 'Tables serving list',
    'reception.dashboard.table_code': 'Table code',
    'reception.dashboard.guest_col': 'Guest col',
    'reception.dashboard.time_col': 'Time col',
    'reception.dashboard.status_col': 'Status col',
    'reception.dashboard.invoice_col': 'Invoice col',
    'reception.dashboard.dining': 'Dining',
    'reception.dashboard.checkout_action': 'Checkout action',
    'reception.dashboard.no_tables_serving': 'No tables serving',
    'reception.dashboard.booking_code': 'Booking code',
    'reception.dashboard.hour': 'Hour',
    'reception.dashboard.num_guests': 'Num guests',
    'reception.dashboard.no_bookings_today': 'No bookings today',
    'reception.dashboard.no_branch_error': 'No branch error',

    // Purchasing
    'purchasing.po_list': 'Purchase Orders',
    'purchasing.create_po': 'Create PO',
    'purchasing.requisitions': 'Requisitions',
    'purchasing.suppliers': 'Suppliers',

    // Accounting
    'accounting.invoices': 'Invoices',
    'accounting.tax_export': 'Tax Export',
    'accounting.inventory_valuation': 'Inventory Val.',

    // Marketing
    'marketing.title': 'Marketing',
    'marketing.campaigns': 'Campaigns',
    'marketing.analytics': 'Analytics',

    // BOD
    'bod.hq_dashboard': 'HQ Dashboard',
    'bod.branch_performance': 'Performance',
    'bod.audit_logs': 'Audit Logs',
    'bod.system_config': 'System Config',

    // CRM
    'crm.title': 'CRM',
    'crm.customers': 'Customers',
    'crm.vouchers': 'Vouchers',
    'crm.feedback': 'Feedback',
    'crm.dashboard': 'Dashboard',
    'crm.servingTables': 'Serving Tables',
    'crm.refresh': 'Refresh',
    'crm.noTables': 'No tables found.',
    'crm.guests': 'Guests',
    'crm.status.toDo': 'To Do',
    'crm.status.assigned': 'Assigned',
    'crm.status.inProgress': 'In Progress',
    'crm.status.done': 'Done',
    'crm.status.skipped': 'Skipped',
    'crm.status.refused': 'Refused',
    'crm.action.start': 'Start Survey',
    'crm.action.view': 'View',
    'crm.surveyTitle': 'Survey - ',
    'crm.customerInfo': 'Customer Info',
    'crm.name': 'Name',
    'crm.phone': 'Phone',
    'crm.visitReason': 'Visit Reason',
    'crm.selectReason': 'Select reason',
    'crm.reason.casual': 'Casual Dining',
    'crm.reason.birthday': 'Birthday',
    'crm.reason.anniversary': 'Anniversary',
    'crm.reason.business': 'Business Meeting',
    'crm.reason.other': 'Other',
    'crm.generalFeedback': 'General Feedback',
    'crm.feedbackPlaceholder': 'How was the experience?',
    'crm.improvementNotes': 'Improvement Notes',
    'crm.improvementPlaceholder': 'What can we do better?',
    'crm.saving': 'Saving...',
    'crm.submitSurvey': 'Submit Survey',
    'crm.markInProgress': 'Mark as "In Progress"',
    'crm.skip': 'Customer Refused / Skip',
    'crm.surveyCompleted': 'Survey Completed',
    'crm.alreadySurveyed': 'This table has already been surveyed.',
    'crm.noFeedback': 'No feedback found.',
    'crm.anonymous': 'Anonymous',
    'crm.noComment': 'No comment provided.',
    'crm.recentFeedback': 'Recent Feedback',
    'crm.readCustomers': 'Read what customers are saying',
    'crm.overview': 'Overview',
    'crm.stats.completed': 'Completed',
    'crm.stats.customersPlus': '+12 this week',
    'crm.stats.avgRating': 'Avg Rating',
    'crm.stats.ratingPlus': '+0.2 from last week',
    'crm.stats.today': 'Today',
    'crm.stats.activeTables': '/ 30 active tables',
    'crm.quickActions': 'Quick Actions',
    'crm.startSurvey': 'Start a Survey',
    'crm.viewTablesToBegin': 'View tables to begin'
  },
  ja: {
    // Hall / Checkout
    // Service Requests
    // Reservations
    // Purchasing
    // Accounting
    // Campaigns
    // BOD
    // Feedback
  
    // Reception Keys
    'reception.restaurant': 'レストラン',
    'reception.other_income': 'その他収入',
    'reception.other_expense': 'その他支出',
    'reception.configuration': '設定',
    'reception.receipt': '伝票',
    'reception.reports': '報告書',
    'reception.shift_details': 'シフト詳細',
    'reception.notifications': '通知',
    'reception.read': '既読',
    'reception.urgent': '緊急',
    'reception.tables_in_use': '利用中のテーブル',
    'reception.waiting_payment': '支払い待ち',
    'reception.reservations_today': '本日の予約',
    'reception.quick_actions': 'クイックアクション',
    'reception.open_shift': '営業中のシフト',
    'reception.started_at': '開始時刻',
    'reception.initial_cash': '開始残高',
    'reception.temp_amount': '仮売上',
    'reception.upcoming': '近日中',
    'reception.reservation_count': '件の予約',
    'reception.view_more': 'もっと見る',
    'reception.payment_request': '支払いリクエスト',
    'reception.new_order': '新規注文',
    'reception.out_of_stock': '品切れ',
    'reception.stock_notification': '在庫通知',
    'reception.just_now': 'たった今',
    'reception.minutes_ago': '分前',
    'reception.branch': '店舗',
    'reception.system': 'システム',
    'reception.connection': '接続',
    'reception.close': '閉じる',
    'reception.no_open_shift': 'アクティブなシフトがありません',
    'reception.please_open_shift': '続行するにはシフトを開いてください',
    'reception.open_shift_btn': 'シフトを開く',
    'reception.other_income_short': 'その他収入',
    'reception.other_expenses': 'その他支出',
    'reception.current_shift_summary': '現在のシフト要約',
    'reception.start_time': '開始時刻',
    'reception.opening_balance': '開始残高',
    'reception.current_revenue': '現在の売上',
    'reception.processed_orders': '処理済み注文',
    'reception.no_active_shifts': '有効なシフトはありません',
    'reception.serving_tables_list': '接客中のテーブル一覧',
    'reception.guests': '名',
    'reception.seated_time': '着席時間',
    'reception.ordered_items': '注文商品数',
    'reception.action_col': '操作',
    'reception.loading': '読み込み中...',
    'reception.payment': '会計',
    'reception.no_active_tables': '接客中のテーブルはありません',
    'reception.reservation_code': '予約コード',
    'reception.customer_phone': '電話番号',
    'reception.reserved_time': '予約時間',
    'reception.number_of_people': '人数',
    'reception.status': 'ステータス',
    'reception.confirm': '確認',
    'reception.cancel': 'キャンセル',
    'reception.no_action': '操作なし',
    'reception.no_reservations_today': '本日の予約はありません',
    'reception.no_notifications': '通知はありません',
    'reception.enter_target_name': '対象名を入力...',
    'reception.other': 'その他',
    'reception.reason': '理由',
    'reception.enter_reason': '理由を入力...',
    'reception.auto_generated': '自動生成',
    'reception.enter_booking_code': '予約コードを入力...',
    'reception.cash': '現金',
    'reception.save_and_print': '保存＆印刷',
    'reception.save': '保存',
    'reception.skip': 'スキップ',
    'reception.username': 'ユーザー名',
    'reception.enter_username': 'ユーザー名を入力...',
    'reception.password': 'パスワード',
    'reception.enter_password': 'パスワードを入力...',
    'reception.ignore': '無視',
  
    // Dashboard Keys

    // Purchasing

    // Accounting

    // Marketing

    // BOD
    
    // CRM
    'crm.title': 'CRM',
    'crm.customers': 'お客様',
    'crm.vouchers': 'バウチャー',
    'crm.feedback': 'フィードバック',
    'crm.dashboard': 'ダッシュボード',
    'crm.servingTables': '接客中のテーブル',
    'crm.refresh': '更新',
    'crm.noTables': 'テーブルが見つかりません。',
    'crm.guests': 'お客様',
    'crm.status.toDo': '未対応',
    'crm.status.assigned': '割り当て済み',
    'crm.status.inProgress': '対応中',
    'crm.status.done': '完了',
    'crm.status.skipped': 'スキップ',
    'crm.status.refused': '拒否',
    'crm.action.start': 'アンケート開始',
    'crm.action.view': '見る',
    'crm.surveyTitle': 'アンケート - ',
    'crm.customerInfo': 'お客様情報',
    'crm.name': '名前',
    'crm.phone': '電話番号',
    'crm.visitReason': '来店理由',
    'crm.selectReason': '理由を選択',
    'crm.reason.casual': '通常の食事',
    'crm.reason.birthday': '誕生日',
    'crm.reason.anniversary': '記念日',
    'crm.reason.business': 'ビジネス',
    'crm.reason.other': 'その他',
    'crm.generalFeedback': '一般的なフィードバック',
    'crm.feedbackPlaceholder': '体験はいかがでしたか？',
    'crm.improvementNotes': '改善メモ',
    'crm.improvementPlaceholder': 'どのようにより良くできますか？',
    'crm.saving': '保存中...',
    'crm.submitSurvey': 'アンケートを送信',
    'crm.markInProgress': '「対応中」にする',
    'crm.skip': 'お客様拒否 / スキップ',
    'crm.surveyCompleted': 'アンケート完了',
    'crm.alreadySurveyed': 'このテーブルはすでにアンケート済みです。',
    'crm.noFeedback': 'フィードバックがありません。',
    'crm.anonymous': '匿名',
    'crm.noComment': 'コメントなし。',
    'crm.recentFeedback': '最近のフィードバック',
    'crm.readCustomers': 'お客様の声を読んでください',
    'crm.overview': '概要',
    'crm.stats.completed': '完了',
    'crm.stats.customersPlus': '今週 +12',
    'crm.stats.avgRating': '平均評価',
    'crm.stats.ratingPlus': '先週から +0.2',
    'crm.stats.today': '今日',
    'crm.stats.activeTables': '/ 30稼働中',
    'crm.quickActions': 'クイックアクション',
    'crm.startSurvey': 'アンケートを開始する',
    'crm.viewTablesToBegin': '開始するにはテーブルを表示します'
  }
};

export const useLanguageStore = defineStore('language', {
  state: () => ({
    lang: (localStorage.getItem('app_lang') ?? 'vi') as Lang,
    loadedMessages: {} as Record<string, any>,
    dict: dict as Record<string, any>
  }),
  getters: {
    currentLang: (state) => state.lang,
    isVietnamese: (state) => state.lang === 'vi',
    isEnglish: (state) => state.lang === 'en',
    isJapanese: (state) => state.lang === 'ja',
    t: (state) => (key: string, defaultOrParams?: string | Record<string, string>, params?: Record<string, string>): string => {
      // Direct lookup from messages to bypass vue-i18n dot-splitting issue on flat keys
      const globalMessages = (i18n.global.messages as any).value || i18n.global.messages;
      const langMessages = globalMessages?.[state.lang];
      const directTranslation = langMessages?.[key] || globalMessages?.['vi']?.[key];
      
      if (directTranslation) {
         let val = directTranslation;
         const actualParams = typeof defaultOrParams === 'object' ? defaultOrParams : params;
         if (actualParams) {
           for (const [k, v] of Object.entries(actualParams)) {
             val = val.replace(`{${k}}`, v as string);
           }
         }
         return val;
      }

      // Import the global i18n instance
      // Note: We use dynamic import or get it from global if possible to avoid circular dependency
      // but here we can just use it if we import it at the top.
      const hasI18nKey = i18n.global.te(key, state.lang);
      if (hasI18nKey) {
         if (typeof defaultOrParams === 'object') {
             return i18n.global.t(key, defaultOrParams) as string;
         } else if (params) {
             return i18n.global.t(key, params) as string;
         } else {
             return i18n.global.t(key) as string;
         }
      }

      // Fallback 1: Use internal dict
      let val = state.dict[state.lang]?.[key] ?? state.dict['vi']?.[key];
      
      // Fallback 2: Use provided default string if available
      if (!val && typeof defaultOrParams === 'string') {
          val = defaultOrParams;
      }
      
      // Fallback 3: Return key
      if (!val) {
          val = key;
      }

      const actualParams = typeof defaultOrParams === 'object' ? defaultOrParams : params;
      if (actualParams) {
        for (const [k, v] of Object.entries(actualParams)) {
          val = val.replace(`{${k}}`, v as string);
        }
      }
      return val;
    },
    langOptions: () => [
      { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
      { code: 'en', label: 'English',    flag: '🇬🇧' },
      { code: 'ja', label: '日本語',      flag: '🇯🇵' },
    ] as const,
  },
  actions: {
    setLanguage(lang: Lang) {
      this.lang = lang;
      localStorage.setItem('app_lang', lang);
      this.setI18nLocale(lang);
    },
    setI18nLocale(lang: Lang) {
      setI18nLocale(lang);
    },
    loadMessages(messages: Record<string, any>) {
      this.loadedMessages = messages;
    }
  }
});
