graph TD
    classDef interaction fill:#9f9,stroke:#333,stroke-width:2px;

    subgraph "CRM Module Interaction"
        M_CRM[CRM Core] <--> M_Tablet[Tablet Survey Interface]
        M_CRM <--> M_Zalo[Zalo OA Integration]
        M_CRM <--> M_POS[Cashier Checkout POS]
    end

    class M_CRM,M_Tablet,M_Zalo,M_POS interaction;
