graph TD
    classDef lifecycle fill:#ffc,stroke:#333,stroke-width:2px;

    subgraph "Booking Lifecycle"
        L_State[Trạng thái Đặt bàn: Chờ đến -> Đã đến / Đã hủy / Trễ hẹn No-Show]
    end

    class L_State lifecycle;
